import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/core/localization/app_localizations_ar.dart';
import 'package:frontend/core/localization/app_localizations_en.dart';

void main() {
  group('AI Assistant & Lifecycle Navigator Localization Tests', () {
    const ar = AppLocalizationsAr();
    const en = AppLocalizationsEn();

    test('All getters return non-empty strings in Arabic and English', () {
      final gettersAr = [
        ar.aiAssistantTitle,
        ar.aiAssistantGreetingTitle,
        ar.aiAssistantGreetingBody,
        ar.aiAssistantOnlineStatus,
        ar.aiAssistantCloseTooltip,
        ar.aiAssistantOpenTooltip,
        ar.aiAssistantMyShipmentsTooltip,
        ar.aiAssistantClearChatTooltip,
        ar.aiAssistantApiKeySettingsTooltip,
        ar.aiAssistantExpandTooltip,
        ar.aiAssistantRestoreTooltip,
        ar.aiAssistantCopyTranscriptTooltip,
        ar.aiAssistantTranscriptCopied,
        ar.aiAssistantNoMessagesToCopy,
        ar.aiAssistantInputHint,
        ar.aiAssistantSendTooltip,
        ar.aiAssistantPasteTooltip,
        ar.aiAssistantCopyMessageSuccess,
        ar.aiAssistantUserMessageCopied,
        ar.aiAssistantAssistantMessageCopied,
        ar.aiAssistantCopyNotificationTooltip,
        ar.aiAssistantNotificationCopied,
        ar.aiAssistantRetry,
        ar.aiAssistantQuickSuggestionsTitle,
        ar.aiAssistantActivateTitle,
        ar.aiAssistantActivateDesc,
        ar.aiAssistantEnterApiKey,
        ar.aiAssistantGetApiKeyLabel,
        ar.aiAssistantApiKeyDialogTitle,
        ar.aiAssistantApiKeyFieldLabel,
        ar.aiAssistantApiKeyActiveStatus,
        ar.aiAssistantDisableKey,
        ar.aiAssistantSaveAndActivate,
        ar.aiAssistantClearContextTooltip,
        ar.aiAssistantViewDataShortcut,
        ar.aiAssistantUpdateDataShortcut,
        ar.aiAssistantAskAboutStepShortcut,
        ar.aiAssistantCopiedUrlSuccess,
        ar.aiAssistantOpenLink,
        ar.aiAssistantCancel,
        ar.aiLifecycleTitle,
        ar.aiLifecycleCloseTooltip,
        ar.aiLifecycleCopySummaryTooltip,
        ar.aiLifecycleSummaryCopied,
        ar.aiLifecycleNoShipments,
        ar.aiLifecycleStartNewShipment,
        ar.aiLifecycleAllCompleted,
        ar.aiLifecycleCompletionRate('🟢', 80, 8, 10),
        ar.aiLifecycleStatusOverdue,
        ar.aiLifecycleStatusCompleted,
        ar.aiLifecycleStatusActive,
        ar.aiLifecycleStatusUpcoming,
        ar.aiLifecycleHideStages,
        ar.aiLifecycleShowAllStages(6),
        ar.aiLifecycleActionsFor('المستندات'),
        ar.aiLifecycleActionView,
        ar.aiLifecycleActionUpdate,
        ar.aiLifecycleActionAsk,
        ar.aiLifecycleActionSkip,
        ar.aiLifecycleCopyFileCodeTooltip,
        ar.aiLifecycleFileCodeCopied,
      ];

      final gettersEn = [
        en.aiAssistantTitle,
        en.aiAssistantGreetingTitle,
        en.aiAssistantGreetingBody,
        en.aiAssistantOnlineStatus,
        en.aiAssistantCloseTooltip,
        en.aiAssistantOpenTooltip,
        en.aiAssistantMyShipmentsTooltip,
        en.aiAssistantClearChatTooltip,
        en.aiAssistantApiKeySettingsTooltip,
        en.aiAssistantExpandTooltip,
        en.aiAssistantRestoreTooltip,
        en.aiAssistantCopyTranscriptTooltip,
        en.aiAssistantTranscriptCopied,
        en.aiAssistantNoMessagesToCopy,
        en.aiAssistantInputHint,
        en.aiAssistantSendTooltip,
        en.aiAssistantPasteTooltip,
        en.aiAssistantCopyMessageSuccess,
        en.aiAssistantUserMessageCopied,
        en.aiAssistantAssistantMessageCopied,
        en.aiAssistantCopyNotificationTooltip,
        en.aiAssistantNotificationCopied,
        en.aiAssistantRetry,
        en.aiAssistantQuickSuggestionsTitle,
        en.aiAssistantActivateTitle,
        en.aiAssistantActivateDesc,
        en.aiAssistantEnterApiKey,
        en.aiAssistantGetApiKeyLabel,
        en.aiAssistantApiKeyDialogTitle,
        en.aiAssistantApiKeyFieldLabel,
        en.aiAssistantApiKeyActiveStatus,
        en.aiAssistantDisableKey,
        en.aiAssistantSaveAndActivate,
        en.aiAssistantClearContextTooltip,
        en.aiAssistantViewDataShortcut,
        en.aiAssistantUpdateDataShortcut,
        en.aiAssistantAskAboutStepShortcut,
        en.aiAssistantCopiedUrlSuccess,
        en.aiAssistantOpenLink,
        en.aiAssistantCancel,
        en.aiLifecycleTitle,
        en.aiLifecycleCloseTooltip,
        en.aiLifecycleCopySummaryTooltip,
        en.aiLifecycleSummaryCopied,
        en.aiLifecycleNoShipments,
        en.aiLifecycleStartNewShipment,
        en.aiLifecycleAllCompleted,
        en.aiLifecycleCompletionRate('🟢', 80, 8, 10),
        en.aiLifecycleStatusOverdue,
        en.aiLifecycleStatusCompleted,
        en.aiLifecycleStatusActive,
        en.aiLifecycleStatusUpcoming,
        en.aiLifecycleHideStages,
        en.aiLifecycleShowAllStages(6),
        en.aiLifecycleActionsFor('Documents'),
        en.aiLifecycleActionView,
        en.aiLifecycleActionUpdate,
        en.aiLifecycleActionAsk,
        en.aiLifecycleActionSkip,
        en.aiLifecycleCopyFileCodeTooltip,
        en.aiLifecycleFileCodeCopied,
      ];

      for (final s in gettersAr) {
        expect(s.trim(), isNotEmpty);
      }
      for (final s in gettersEn) {
        expect(s.trim(), isNotEmpty);
      }
    });

    test('Strict Pure Arabic: 0 Latin letters [a-zA-Z] in Arabic strings', () {
      final latinPattern = RegExp(r'[a-zA-Z]');
      final arabicStrings = [
        ar.aiAssistantTitle,
        ar.aiAssistantGreetingTitle,
        ar.aiAssistantGreetingBody,
        ar.aiAssistantOnlineStatus,
        ar.aiAssistantCloseTooltip,
        ar.aiAssistantOpenTooltip,
        ar.aiAssistantMyShipmentsTooltip,
        ar.aiAssistantClearChatTooltip,
        ar.aiAssistantApiKeySettingsTooltip,
        ar.aiAssistantExpandTooltip,
        ar.aiAssistantRestoreTooltip,
        ar.aiAssistantCopyTranscriptTooltip,
        ar.aiAssistantTranscriptCopied,
        ar.aiAssistantNoMessagesToCopy,
        ar.aiAssistantInputHint,
        ar.aiAssistantSendTooltip,
        ar.aiAssistantPasteTooltip,
        ar.aiAssistantCopyMessageSuccess,
        ar.aiAssistantUserMessageCopied,
        ar.aiAssistantAssistantMessageCopied,
        ar.aiAssistantCopyNotificationTooltip,
        ar.aiAssistantNotificationCopied,
        ar.aiAssistantRetry,
        ar.aiAssistantQuickSuggestionsTitle,
        ar.aiAssistantActivateTitle,
        ar.aiAssistantActivateDesc,
        ar.aiAssistantEnterApiKey,
        ar.aiAssistantGetApiKeyLabel,
        ar.aiAssistantApiKeyDialogTitle,
        ar.aiAssistantApiKeyFieldLabel,
        ar.aiAssistantApiKeyActiveStatus,
        ar.aiAssistantDisableKey,
        ar.aiAssistantSaveAndActivate,
        ar.aiAssistantClearContextTooltip,
        ar.aiAssistantViewDataShortcut,
        ar.aiAssistantUpdateDataShortcut,
        ar.aiAssistantAskAboutStepShortcut,
        ar.aiAssistantCopiedUrlSuccess,
        ar.aiAssistantOpenLink,
        ar.aiAssistantCancel,
        ar.aiLifecycleTitle,
        ar.aiLifecycleCloseTooltip,
        ar.aiLifecycleCopySummaryTooltip,
        ar.aiLifecycleSummaryCopied,
        ar.aiLifecycleNoShipments,
        ar.aiLifecycleStartNewShipment,
        ar.aiLifecycleAllCompleted,
        ar.aiLifecycleCompletionRate('🟢', 80, 8, 10),
        ar.aiLifecycleStatusOverdue,
        ar.aiLifecycleStatusCompleted,
        ar.aiLifecycleStatusActive,
        ar.aiLifecycleStatusUpcoming,
        ar.aiLifecycleHideStages,
        ar.aiLifecycleShowAllStages(6),
        ar.aiLifecycleActionsFor('المستندات'),
        ar.aiLifecycleActionView,
        ar.aiLifecycleActionUpdate,
        ar.aiLifecycleActionAsk,
        ar.aiLifecycleActionSkip,
        ar.aiLifecycleCopyFileCodeTooltip,
        ar.aiLifecycleFileCodeCopied,
      ];

      for (final s in arabicStrings) {
        expect(
          latinPattern.hasMatch(s),
          isFalse,
          reason: 'String contains Latin character: "$s"',
        );
      }
    });

    test('Zero bilingual slashes (/) in Arabic strings', () {
      final arabicStrings = [
        ar.aiAssistantTitle,
        ar.aiAssistantGreetingTitle,
        ar.aiAssistantGreetingBody,
        ar.aiAssistantOnlineStatus,
        ar.aiAssistantCloseTooltip,
        ar.aiAssistantOpenTooltip,
        ar.aiAssistantMyShipmentsTooltip,
        ar.aiAssistantClearChatTooltip,
        ar.aiAssistantApiKeySettingsTooltip,
        ar.aiAssistantExpandTooltip,
        ar.aiAssistantRestoreTooltip,
        ar.aiAssistantCopyTranscriptTooltip,
        ar.aiAssistantTranscriptCopied,
        ar.aiAssistantNoMessagesToCopy,
        ar.aiAssistantInputHint,
        ar.aiAssistantSendTooltip,
        ar.aiAssistantPasteTooltip,
        ar.aiAssistantCopyMessageSuccess,
        ar.aiAssistantUserMessageCopied,
        ar.aiAssistantAssistantMessageCopied,
        ar.aiAssistantCopyNotificationTooltip,
        ar.aiAssistantNotificationCopied,
        ar.aiAssistantRetry,
        ar.aiAssistantQuickSuggestionsTitle,
        ar.aiAssistantActivateTitle,
        ar.aiAssistantActivateDesc,
        ar.aiAssistantEnterApiKey,
        ar.aiAssistantGetApiKeyLabel,
        ar.aiAssistantApiKeyDialogTitle,
        ar.aiAssistantApiKeyFieldLabel,
        ar.aiAssistantApiKeyActiveStatus,
        ar.aiAssistantDisableKey,
        ar.aiAssistantSaveAndActivate,
        ar.aiAssistantClearContextTooltip,
        ar.aiAssistantViewDataShortcut,
        ar.aiAssistantUpdateDataShortcut,
        ar.aiAssistantAskAboutStepShortcut,
        ar.aiAssistantCopiedUrlSuccess,
        ar.aiAssistantOpenLink,
        ar.aiAssistantCancel,
        ar.aiLifecycleTitle,
        ar.aiLifecycleCloseTooltip,
        ar.aiLifecycleCopySummaryTooltip,
        ar.aiLifecycleSummaryCopied,
        ar.aiLifecycleNoShipments,
        ar.aiLifecycleStartNewShipment,
        ar.aiLifecycleAllCompleted,
        ar.aiLifecycleCompletionRate('🟢', 80, 8, 10),
        ar.aiLifecycleStatusOverdue,
        ar.aiLifecycleStatusCompleted,
        ar.aiLifecycleStatusActive,
        ar.aiLifecycleStatusUpcoming,
        ar.aiLifecycleHideStages,
        ar.aiLifecycleShowAllStages(6),
        ar.aiLifecycleActionsFor('المستندات'),
        ar.aiLifecycleActionView,
        ar.aiLifecycleActionUpdate,
        ar.aiLifecycleActionAsk,
        ar.aiLifecycleActionSkip,
        ar.aiLifecycleCopyFileCodeTooltip,
        ar.aiLifecycleFileCodeCopied,
      ];

      for (final s in arabicStrings) {
        expect(
          s.contains('/'),
          isFalse,
          reason: 'String contains bilingual slash: "$s"',
        );
      }
    });
  });
}
