import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/core/localization/app_localizations.dart';
import 'package:frontend/core/localization/app_localizations_ar.dart';
import 'package:frontend/core/localization/app_localizations_en.dart';

void main() {
  group('Screen 51: Central Docs Hub Localization Tests', () {
    late AppLocalizations ar;
    late AppLocalizations en;

    setUp(() {
      ar = const AppLocalizationsAr();
      en = const AppLocalizationsEn();
    });

    test('All Screen 51 getters should return non-empty strings in Arabic and English', () {
      expect(ar.centralDocsArchiveTitle, isNotEmpty);
      expect(en.centralDocsArchiveTitle, isNotEmpty);
      expect(ar.closeAndReturn, isNotEmpty);
      expect(en.closeAndReturn, isNotEmpty);
      expect(ar.selectCentralArchiveFileLabel, isNotEmpty);
      expect(en.selectCentralArchiveFileLabel, isNotEmpty);
      expect(ar.selectCentralArchiveFileHint, isNotEmpty);
      expect(en.selectCentralArchiveFileHint, isNotEmpty);
      expect(ar.refreshArchiveBtn, isNotEmpty);
      expect(en.refreshArchiveBtn, isNotEmpty);
      expect(ar.selectShipmentFilePrompt, isNotEmpty);
      expect(en.selectShipmentFilePrompt, isNotEmpty);
      expect(ar.centralArchivePlaceholderDesc, isNotEmpty);
      expect(en.centralArchivePlaceholderDesc, isNotEmpty);
      expect(ar.centralArchiveLoadingPrompt, isNotEmpty);
      expect(en.centralArchiveLoadingPrompt, isNotEmpty);
      expect(ar.centralArchiveLoadError('Network Fail'), contains('Network Fail'));
      expect(en.centralArchiveLoadError('Network Fail'), contains('Network Fail'));
      expect(ar.readinessReadyForRelease, isNotEmpty);
      expect(en.readinessReadyForRelease, isNotEmpty);
      expect(ar.readinessActionRequired, isNotEmpty);
      expect(en.readinessActionRequired, isNotEmpty);
      expect(ar.readinessInReview, isNotEmpty);
      expect(en.readinessInReview, isNotEmpty);
      expect(ar.fileCodeLabel('IMP-001'), contains('IMP-001'));
      expect(en.fileCodeLabel('IMP-001'), contains('IMP-001'));
      expect(ar.customsFileNumberLabel('CUST-999'), contains('CUST-999'));
      expect(en.customsFileNumberLabel('CUST-999'), contains('CUST-999'));
      expect(ar.importerCompanyLabel, isNotEmpty);
      expect(en.importerCompanyLabel, isNotEmpty);
      expect(ar.exporterSupplierLabel, isNotEmpty);
      expect(en.exporterSupplierLabel, isNotEmpty);
      expect(ar.acidNumberLabel, isNotEmpty);
      expect(en.acidNumberLabel, isNotEmpty);
      expect(ar.shippingRouteLabel, isNotEmpty);
      expect(en.shippingRouteLabel, isNotEmpty);
      expect(ar.totalPackagesAndWeightLabel, isNotEmpty);
      expect(en.totalPackagesAndWeightLabel, isNotEmpty);
      expect(ar.totalInvoiceValueLabel, isNotEmpty);
      expect(en.totalInvoiceValueLabel, isNotEmpty);
      expect(ar.packagesCountText('10', '500'), contains('10'));
      expect(en.packagesCountText('10', '500'), contains('10'));
      expect(ar.complianceReportHeader, isNotEmpty);
      expect(en.complianceReportHeader, isNotEmpty);
      expect(ar.complianceSummaryTag('Italy', '8418', 'Motors'), contains('8418'));
      expect(en.complianceSummaryTag('Italy', '8418', 'Motors'), contains('8418'));
      expect(ar.chipCooLabel, isNotEmpty);
      expect(en.chipCooLabel, isNotEmpty);
      expect(ar.cooRequiredText('EUR.1'), contains('EUR.1'));
      expect(en.cooRequiredText('EUR.1'), contains('EUR.1'));
      expect(ar.cooNotRequiredText, isNotEmpty);
      expect(en.cooNotRequiredText, isNotEmpty);
      expect(ar.chipVocLabel, isNotEmpty);
      expect(en.chipVocLabel, isNotEmpty);
      expect(ar.inspRequiredText('SGS'), contains('SGS'));
      expect(en.inspRequiredText('SGS'), contains('SGS'));
      expect(ar.inspNotRequiredText, isNotEmpty);
      expect(en.inspNotRequiredText, isNotEmpty);
      expect(ar.chipDecree43Label, isNotEmpty);
      expect(en.chipDecree43Label, isNotEmpty);
      expect(ar.decree43WhiteListed, isNotEmpty);
      expect(en.decree43WhiteListed, isNotEmpty);
      expect(ar.decree43RegistrationRequired, isNotEmpty);
      expect(en.decree43RegistrationRequired, isNotEmpty);
      expect(ar.decree43NotApplicable, isNotEmpty);
      expect(en.decree43NotApplicable, isNotEmpty);
      expect(ar.masterRectificationsHeader, isNotEmpty);
      expect(en.masterRectificationsHeader, isNotEmpty);
      expect(ar.copySupplierEmailBtn, isNotEmpty);
      expect(en.copySupplierEmailBtn, isNotEmpty);
      expect(ar.copySupplierEmailSuccess, isNotEmpty);
      expect(en.copySupplierEmailSuccess, isNotEmpty);
      expect(ar.copyWhatsAppBtn, isNotEmpty);
      expect(en.copyWhatsAppBtn, isNotEmpty);
      expect(ar.copyWhatsAppSuccess, isNotEmpty);
      expect(en.copyWhatsAppSuccess, isNotEmpty);
      expect(ar.noDiscrepanciesSuccessMessage, isNotEmpty);
      expect(en.noDiscrepanciesSuccessMessage, isNotEmpty);
      expect(ar.severityCritical, isNotEmpty);
      expect(en.severityCritical, isNotEmpty);
      expect(ar.severityWarning, isNotEmpty);
      expect(en.severityWarning, isNotEmpty);
      expect(ar.discrepancyIssueLabel('Weight Mismatch'), contains('Weight Mismatch'));
      expect(en.discrepancyIssueLabel('Weight Mismatch'), contains('Weight Mismatch'));
      expect(ar.discrepancyRectificationLabel('Fix Gross Weight'), contains('Fix Gross Weight'));
      expect(en.discrepancyRectificationLabel('Fix Gross Weight'), contains('Fix Gross Weight'));
      expect(ar.fiveCoreDocsSectionTitle, isNotEmpty);
      expect(en.fiveCoreDocsSectionTitle, isNotEmpty);
      expect(ar.docTitleCommercialInvoice, isNotEmpty);
      expect(en.docTitleCommercialInvoice, isNotEmpty);
      expect(ar.docTitlePackingList, isNotEmpty);
      expect(en.docTitlePackingList, isNotEmpty);
      expect(ar.docTitleBillOfLading, isNotEmpty);
      expect(en.docTitleBillOfLading, isNotEmpty);
      expect(ar.docTitleCertificateOfOrigin, isNotEmpty);
      expect(en.docTitleCertificateOfOrigin, isNotEmpty);
      expect(ar.docTitleInspectionCertificate, isNotEmpty);
      expect(en.docTitleInspectionCertificate, isNotEmpty);
      expect(ar.docMandatoryCore, isNotEmpty);
      expect(en.docMandatoryCore, isNotEmpty);
      expect(ar.docConditional, isNotEmpty);
      expect(en.docConditional, isNotEmpty);
      expect(ar.docReferenceLabel('INV-99'), contains('INV-99'));
      expect(en.docReferenceLabel('INV-99'), contains('INV-99'));
      expect(ar.docStatusWaived, isNotEmpty);
      expect(en.docStatusWaived, isNotEmpty);
      expect(ar.docStatusApproved, isNotEmpty);
      expect(en.docStatusApproved, isNotEmpty);
      expect(ar.docStatusModificationsRequested, isNotEmpty);
      expect(en.docStatusModificationsRequested, isNotEmpty);
      expect(ar.docStatusReviewPending, isNotEmpty);
      expect(en.docStatusReviewPending, isNotEmpty);
      expect(ar.docStatusNotStarted, isNotEmpty);
      expect(en.docStatusNotStarted, isNotEmpty);
      expect(ar.docModificationsRequestedTitle, isNotEmpty);
      expect(en.docModificationsRequestedTitle, isNotEmpty);
      expect(ar.docWaivedDefaultDesc, isNotEmpty);
      expect(en.docWaivedDefaultDesc, isNotEmpty);
      expect(ar.docNoDiscrepanciesDesc, isNotEmpty);
      expect(en.docNoDiscrepanciesDesc, isNotEmpty);
    });

    test('Arabic static strings should not contain English or Latin characters', () {
      final latinPattern = RegExp(r'[a-zA-Z]');
      expect(latinPattern.hasMatch(ar.centralDocsArchiveTitle), isFalse);
      expect(latinPattern.hasMatch(ar.closeAndReturn), isFalse);
      expect(latinPattern.hasMatch(ar.selectCentralArchiveFileLabel), isFalse);
      expect(latinPattern.hasMatch(ar.selectCentralArchiveFileHint), isFalse);
      expect(latinPattern.hasMatch(ar.refreshArchiveBtn), isFalse);
      expect(latinPattern.hasMatch(ar.selectShipmentFilePrompt), isFalse);
      expect(latinPattern.hasMatch(ar.centralArchivePlaceholderDesc), isFalse);
      expect(latinPattern.hasMatch(ar.centralArchiveLoadingPrompt), isFalse);
      expect(latinPattern.hasMatch(ar.readinessReadyForRelease), isFalse);
      expect(latinPattern.hasMatch(ar.readinessActionRequired), isFalse);
      expect(latinPattern.hasMatch(ar.readinessInReview), isFalse);
      expect(latinPattern.hasMatch(ar.importerCompanyLabel), isFalse);
      expect(latinPattern.hasMatch(ar.exporterSupplierLabel), isFalse);
      expect(latinPattern.hasMatch(ar.acidNumberLabel), isFalse);
      expect(latinPattern.hasMatch(ar.shippingRouteLabel), isFalse);
      expect(latinPattern.hasMatch(ar.totalPackagesAndWeightLabel), isFalse);
      expect(latinPattern.hasMatch(ar.totalInvoiceValueLabel), isFalse);
      expect(latinPattern.hasMatch(ar.complianceReportHeader), isFalse);
      expect(latinPattern.hasMatch(ar.chipCooLabel), isFalse);
      expect(latinPattern.hasMatch(ar.cooNotRequiredText), isFalse);
      expect(latinPattern.hasMatch(ar.chipVocLabel), isFalse);
      expect(latinPattern.hasMatch(ar.inspNotRequiredText), isFalse);
      expect(latinPattern.hasMatch(ar.chipDecree43Label), isFalse);
      expect(latinPattern.hasMatch(ar.decree43WhiteListed), isFalse);
      expect(latinPattern.hasMatch(ar.decree43RegistrationRequired), isFalse);
      expect(latinPattern.hasMatch(ar.decree43NotApplicable), isFalse);
      expect(latinPattern.hasMatch(ar.masterRectificationsHeader), isFalse);
      expect(latinPattern.hasMatch(ar.copySupplierEmailBtn), isFalse);
      expect(latinPattern.hasMatch(ar.copySupplierEmailSuccess), isFalse);
      expect(latinPattern.hasMatch(ar.copyWhatsAppBtn), isFalse);
      expect(latinPattern.hasMatch(ar.copyWhatsAppSuccess), isFalse);
      expect(latinPattern.hasMatch(ar.noDiscrepanciesSuccessMessage), isFalse);
      expect(latinPattern.hasMatch(ar.severityCritical), isFalse);
      expect(latinPattern.hasMatch(ar.severityWarning), isFalse);
      expect(latinPattern.hasMatch(ar.fiveCoreDocsSectionTitle), isFalse);
      expect(latinPattern.hasMatch(ar.docTitleCommercialInvoice), isFalse);
      expect(latinPattern.hasMatch(ar.docTitlePackingList), isFalse);
      expect(latinPattern.hasMatch(ar.docTitleBillOfLading), isFalse);
      expect(latinPattern.hasMatch(ar.docTitleCertificateOfOrigin), isFalse);
      expect(latinPattern.hasMatch(ar.docTitleInspectionCertificate), isFalse);
      expect(latinPattern.hasMatch(ar.docMandatoryCore), isFalse);
      expect(latinPattern.hasMatch(ar.docConditional), isFalse);
      expect(latinPattern.hasMatch(ar.docStatusWaived), isFalse);
      expect(latinPattern.hasMatch(ar.docStatusApproved), isFalse);
      expect(latinPattern.hasMatch(ar.docStatusModificationsRequested), isFalse);
      expect(latinPattern.hasMatch(ar.docStatusReviewPending), isFalse);
      expect(latinPattern.hasMatch(ar.docStatusNotStarted), isFalse);
      expect(latinPattern.hasMatch(ar.docModificationsRequestedTitle), isFalse);
      expect(latinPattern.hasMatch(ar.docWaivedDefaultDesc), isFalse);
      expect(latinPattern.hasMatch(ar.docNoDiscrepanciesDesc), isFalse);
    });
  });
}
