import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/core/localization/app_localizations.dart';
import 'package:frontend/core/localization/app_localizations_ar.dart';
import 'package:frontend/core/localization/app_localizations_en.dart';

void main() {
  group('Screen 36: Customs Tariff Schedule Localization Tests', () {
    const AppLocalizations ar = AppLocalizationsAr();
    const AppLocalizations en = AppLocalizationsEn();

    test('All Screen 36 getters should have non-empty Arabic and English translations', () {
      final List<String> arStrings = [
        ar.customsTariffScreenTitle,
        ar.customsTariffScreenSubtitle,
        ar.importExcelCsvBtn,
        ar.hsExplorerBtn,
        ar.smartNafezaDiffEngineBtn,
        ar.dutyCalculatorBtn,
        ar.addTariffManualBtn,
        ar.searchTariffsHint,
        ar.showInactiveTariffsLabel,
        ar.noTariffsMatchingQuery('8415'),
        ar.noTariffsFound,
        ar.tariffHsCodeCol,
        ar.tariffDescAndAuthorityCol,
        ar.tariffCategoryCol,
        ar.tariffTaxRatesBreakdownCol,
        ar.tariffRequirementsCol,
        ar.tariffStatusCol,
        ar.tariffActionsCol,
        ar.rateDutyBadge('10%'),
        ar.rateVatBadge('14%'),
        ar.rateSchedBadge('5%'),
        ar.rateDevBadge('3%'),
        ar.govAuthorityPrefix('GOEIC'),
        ar.printTariffSnack('8415.82', 'Air Conditioner'),
        ar.confirmDeactivateTariff('8415.82'),
        ar.confirmActivateTariff('8415.82'),
        ar.deactivateTariffTooltip,
        ar.activateTariffTooltip,
        ar.importingTariffDataset,
        ar.importCompletedTitle,
        ar.importSummaryContent(100, 20, 80),
        ar.importFailedSnack('Network error'),
        ar.nafezaDetailsModalTitle,
        ar.itemNumberLabel,
        ar.itemDescriptionLabel,
        ar.taxesSectionHeader,
        ar.importDutyLabel,
        ar.vatLabel,
        ar.scheduleTaxLabel,
        ar.developmentFeeLabel,
        ar.importFeeLabel,
        ar.customsServiceFeeLabel,
        ar.basicFeesLabel,
        ar.documentsAndProceduresHeader,
        ar.preferentialAgreementsSubheader,
        ar.addPreferentialAgreementBtn,
        ar.noPreferentialAgreements,
        ar.fullExemptionBadge,
        ar.reductionPercentageBadge('100'),
        ar.applicableCountriesLabel('EU, JO'),
        ar.conditionsLabel('EUR.1'),
        ar.regulatoryApprovalsSubheader,
        ar.requiresCooRule,
        ar.requiresInspectionRule,
        ar.requiresAcidRule,
        ar.addAgreementDialogTitle('8415.82'),
        ar.agreementNameLabel,
        ar.agreementNameHint,
        ar.agreementCountriesLabel,
        ar.agreementCountriesHint,
        ar.dutyReductionPctLabel,
        ar.dutyReductionPctHint,
        ar.agreementConditionsLabel,
        ar.agreementConditionsHint,
        ar.saveAgreementBtn,
        ar.verifyTariffDialogTitle('8415.82'),
        ar.verificationProtocolHeader,
        ar.verificationProtocolText,
        ar.verifiedByAuditorLabel,
        ar.sourceUrlLabel,
        ar.confidenceLevelLabel,
        ar.confirmVerificationBtn,
        ar.verifyTariffBtn,
        ar.editTariffBtn,
        ar.agreementNameRequired,
        ar.agreementCountriesRequired,
        ar.invalidNumberError,
        ar.agreementAddedSuccess,
        ar.agreementAddFailed('Duplicate'),
        ar.auditorNameRequired,
        ar.verificationSuccessSnack,
        ar.verificationFailedSnack('Invalid'),
        ar.confidenceManualAudit,
        ar.confidenceOfficialGazette,
        ar.confidenceDraft,
        ar.priorApprovalSpecialConditionsLabel,
        ar.taxRatesVerificationHeader,
        ar.dutyRateLabel,
        ar.vatRateLabel,
        ar.scheduleTaxRateLabel,
        ar.tariffVerifiedSuccess('8415.82'),
      ];

      final List<String> enStrings = [
        en.customsTariffScreenTitle,
        en.customsTariffScreenSubtitle,
        en.importExcelCsvBtn,
        en.hsExplorerBtn,
        en.smartNafezaDiffEngineBtn,
        en.dutyCalculatorBtn,
        en.addTariffManualBtn,
        en.searchTariffsHint,
        en.showInactiveTariffsLabel,
        en.noTariffsMatchingQuery('8415'),
        en.noTariffsFound,
        en.tariffHsCodeCol,
        en.tariffDescAndAuthorityCol,
        en.tariffCategoryCol,
        en.tariffTaxRatesBreakdownCol,
        en.tariffRequirementsCol,
        en.tariffStatusCol,
        en.tariffActionsCol,
        en.rateDutyBadge('10%'),
        en.rateVatBadge('14%'),
        en.rateSchedBadge('5%'),
        en.rateDevBadge('3%'),
        en.govAuthorityPrefix('GOEIC'),
        en.printTariffSnack('8415.82', 'Air Conditioner'),
        en.confirmDeactivateTariff('8415.82'),
        en.confirmActivateTariff('8415.82'),
        en.deactivateTariffTooltip,
        en.activateTariffTooltip,
        en.importingTariffDataset,
        en.importCompletedTitle,
        en.importSummaryContent(100, 20, 80),
        en.importFailedSnack('Network error'),
        en.nafezaDetailsModalTitle,
        en.itemNumberLabel,
        en.itemDescriptionLabel,
        en.taxesSectionHeader,
        en.importDutyLabel,
        en.vatLabel,
        en.scheduleTaxLabel,
        en.developmentFeeLabel,
        en.importFeeLabel,
        en.customsServiceFeeLabel,
        en.basicFeesLabel,
        en.documentsAndProceduresHeader,
        en.preferentialAgreementsSubheader,
        en.addPreferentialAgreementBtn,
        en.noPreferentialAgreements,
        en.fullExemptionBadge,
        en.reductionPercentageBadge('100'),
        en.applicableCountriesLabel('EU, JO'),
        en.conditionsLabel('EUR.1'),
        en.regulatoryApprovalsSubheader,
        en.requiresCooRule,
        en.requiresInspectionRule,
        en.requiresAcidRule,
        en.addAgreementDialogTitle('8415.82'),
        en.agreementNameLabel,
        en.agreementNameHint,
        en.agreementCountriesLabel,
        en.agreementCountriesHint,
        en.dutyReductionPctLabel,
        en.dutyReductionPctHint,
        en.agreementConditionsLabel,
        en.agreementConditionsHint,
        en.saveAgreementBtn,
        en.verifyTariffDialogTitle('8415.82'),
        en.verificationProtocolHeader,
        en.verificationProtocolText,
        en.verifiedByAuditorLabel,
        en.sourceUrlLabel,
        en.confidenceLevelLabel,
        en.confirmVerificationBtn,
        en.verifyTariffBtn,
        en.editTariffBtn,
        en.agreementNameRequired,
        en.agreementCountriesRequired,
        en.invalidNumberError,
        en.agreementAddedSuccess,
        en.agreementAddFailed('Duplicate'),
        en.auditorNameRequired,
        en.verificationSuccessSnack,
        en.verificationFailedSnack('Invalid'),
        en.confidenceManualAudit,
        en.confidenceOfficialGazette,
        en.confidenceDraft,
        en.priorApprovalSpecialConditionsLabel,
        en.taxRatesVerificationHeader,
        en.dutyRateLabel,
        en.vatRateLabel,
        en.scheduleTaxRateLabel,
        en.tariffVerifiedSuccess('8415.82'),
      ];

      expect(arStrings.length, enStrings.length);
      for (int i = 0; i < arStrings.length; i++) {
        expect(arStrings[i].trim().isNotEmpty, isTrue, reason: 'Arabic string at index $i is empty');
        expect(enStrings[i].trim().isNotEmpty, isTrue, reason: 'English string at index $i is empty');
      }
    });

    test('Verify pure Arabic translations without stacked or Latin characters in static keys', () {
      final List<String> arStaticStrings = [
        ar.customsTariffScreenSubtitle,
        ar.importExcelCsvBtn,
        ar.dutyCalculatorBtn,
        ar.addTariffManualBtn,
        ar.searchTariffsHint,
        ar.showInactiveTariffsLabel,
        ar.noTariffsFound,
        ar.tariffHsCodeCol,
        ar.tariffDescAndAuthorityCol,
        ar.tariffCategoryCol,
        ar.tariffTaxRatesBreakdownCol,
        ar.tariffRequirementsCol,
        ar.tariffStatusCol,
        ar.tariffActionsCol,
        ar.deactivateTariffTooltip,
        ar.activateTariffTooltip,
        ar.importingTariffDataset,
        ar.importCompletedTitle,
        ar.nafezaDetailsModalTitle,
        ar.itemNumberLabel,
        ar.itemDescriptionLabel,
        ar.taxesSectionHeader,
        ar.importDutyLabel,
        ar.vatLabel,
        ar.scheduleTaxLabel,
        ar.developmentFeeLabel,
        ar.importFeeLabel,
        ar.customsServiceFeeLabel,
        ar.basicFeesLabel,
        ar.documentsAndProceduresHeader,
        ar.preferentialAgreementsSubheader,
        ar.addPreferentialAgreementBtn,
        ar.noPreferentialAgreements,
        ar.fullExemptionBadge,
        ar.regulatoryApprovalsSubheader,
        ar.requiresCooRule,
        ar.requiresInspectionRule,
        ar.requiresAcidRule,
        ar.agreementNameLabel,
        ar.agreementNameHint,
        ar.agreementCountriesLabel,
        ar.agreementCountriesHint,
        ar.dutyReductionPctLabel,
        ar.dutyReductionPctHint,
        ar.agreementConditionsLabel,
        ar.agreementConditionsHint,
        ar.saveAgreementBtn,
        ar.verificationProtocolHeader,
        ar.verificationProtocolText,
        ar.verifiedByAuditorLabel,
        ar.sourceUrlLabel,
        ar.confidenceLevelLabel,
        ar.confirmVerificationBtn,
        ar.verifyTariffBtn,
        ar.editTariffBtn,
        ar.agreementNameRequired,
        ar.agreementCountriesRequired,
        ar.invalidNumberError,
        ar.agreementAddedSuccess,
        ar.auditorNameRequired,
        ar.verificationSuccessSnack,
        ar.confidenceManualAudit,
        ar.confidenceOfficialGazette,
        ar.confidenceDraft,
        ar.priorApprovalSpecialConditionsLabel,
        ar.taxRatesVerificationHeader,
        ar.dutyRateLabel,
        ar.vatRateLabel,
        ar.scheduleTaxRateLabel,
      ];

      for (final s in arStaticStrings) {
        expect(RegExp(r'[a-zA-Z]').hasMatch(s), isFalse, reason: 'Arabic string contains Latin characters: $s');
      }
    });
  });
}
