import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/core/localization/app_localizations.dart';
import 'package:frontend/core/localization/app_localizations_ar.dart';
import 'package:frontend/core/localization/app_localizations_en.dart';

void main() {
  group('Screen 20: Customs Docs Approval Localization Tests', () {
    const AppLocalizations ar = AppLocalizationsAr();
    const AppLocalizations en = AppLocalizationsEn();

    test('All Screen 20 getters should have non-empty Arabic and English translations', () {
      final List<String> arStrings = [
        ar.customsApprovalSelectFileForMatrixWarning,
        ar.customsApprovalMatrixCheckCompleted('Fully Compliant'),
        ar.customsApprovalMatrixCheckFailed('Connection Timeout'),
        ar.customsApprovalSelectFileWarning,
        ar.customsApprovalStandardListGeneratedSuccess,
        ar.customsApprovalGenerateFailed('DB Error'),
        ar.customsApprovalSelectFileForTicketWarning,
        ar.customsApprovalImportFileLabel,
        ar.customsApprovalSearchFileHint,
        ar.customsApprovalRunAiMatrixButton,
        ar.customsApprovalAutoGenerateStandardListButton,
        ar.customsApprovalRaiseTicketButton,
        ar.customsApprovalFilterAll,
        ar.customsApprovalFilterPending,
        ar.customsApprovalFilterApproved,
        ar.customsApprovalFilterRejected,
        ar.customsApprovalFilterDiscrepancy,
        ar.customsApprovalTabDualSignoff,
        ar.customsApprovalTabCentralArchive,
        ar.customsApprovalMatrixComplianceResult('Fully Compliant', 5, 5),
        ar.customsApprovalMatrixRecommendations('Check HS codes'),
        ar.customsApprovalMatrixOpenTicketsCount(2),
        ar.customsApprovalDualTierHeader,
        ar.customsApprovalNoDocuments,
        ar.customsApprovalError('Network Error'),
        ar.customsApprovalDocRef('INV-902'),
        ar.customsApprovalCommercialReviewStatus('Approved'),
        ar.customsApprovalBrokerReviewStatus('Approved'),
        ar.customsApprovalTicketsHeader,
        ar.customsApprovalNewTicketButton,
        ar.customsApprovalNoTickets,
        ar.customsApprovalTicketExpectedVsFound('100 kg', '120 kg'),
        ar.customsApprovalResolveTicketButton,
        ar.customsApprovalCommercialDialogTitle('Commercial Invoice'),
        ar.customsApprovalCommercialReviewerLabel,
        ar.customsApprovalRequiredField,
        ar.customsApprovalCommercialDecisionLabel,
        ar.customsApprovalSelectDecisionHint,
        ar.customsApprovalDecisionCommercialApproved,
        ar.customsApprovalDecisionCommercialUnderReview,
        ar.customsApprovalDecisionCommercialRejected,
        ar.customsApprovalCommercialNotesLabel,
        ar.customsApprovalSaveApprovalButton,
        ar.customsApprovalBrokerDialogTitle('Bill of Lading'),
        ar.customsApprovalBrokerOfficeLabel,
        ar.customsApprovalBrokerReviewerNameLabel,
        ar.customsApprovalBrokerDecisionLabel,
        ar.customsApprovalDecisionBrokerApproved,
        ar.customsApprovalDecisionBrokerConditionallyApproved,
        ar.customsApprovalDecisionBrokerRejected,
        ar.customsApprovalBrokerNotesLabel,
        ar.customsApprovalBrokerSaveStampButton,
        ar.customsApprovalRaiseTicketDialogTitle,
        ar.customsApprovalIssueCategoryLabel,
        ar.customsApprovalSelectCategoryHint,
        ar.customsApprovalCatHsMismatch,
        ar.customsApprovalCatWeightDiscrepancy,
        ar.customsApprovalCatCbmDiscrepancy,
        ar.customsApprovalCatValueMismatch,
        ar.customsApprovalCatMissingAcid,
        ar.customsApprovalCatIncotermConflict,
        ar.customsApprovalCatOther,
        ar.customsApprovalSeverityLabel,
        ar.customsApprovalSelectSeverityHint,
        ar.customsApprovalSevCritical,
        ar.customsApprovalSevMajor,
        ar.customsApprovalSevMinor,
        ar.customsApprovalIssueDescLabel,
        ar.customsApprovalIssueDescMinLength,
        ar.customsApprovalExpectedValueLabel,
        ar.customsApprovalFoundValueLabel,
        ar.customsApprovalSupplierActionLabel,
        ar.customsApprovalCreateTicketSubmitButton,
        ar.customsApprovalResolveTicketDialogTitle('TCK-001'),
        ar.customsApprovalSupplierResponseLabel,
        ar.customsApprovalResolverNameLabel,
        ar.customsApprovalFinalStatusLabel,
        ar.customsApprovalSelectStatusHint,
        ar.customsApprovalStatusResolved,
        ar.customsApprovalStatusWaived,
        ar.customsApprovalStatusClosed,
        ar.customsApprovalConfirmResolveTicketButton,
      ];

      final List<String> enStrings = [
        en.customsApprovalSelectFileForMatrixWarning,
        en.customsApprovalMatrixCheckCompleted('Fully Compliant'),
        en.customsApprovalMatrixCheckFailed('Connection Timeout'),
        en.customsApprovalSelectFileWarning,
        en.customsApprovalStandardListGeneratedSuccess,
        en.customsApprovalGenerateFailed('DB Error'),
        en.customsApprovalSelectFileForTicketWarning,
        en.customsApprovalImportFileLabel,
        en.customsApprovalSearchFileHint,
        en.customsApprovalRunAiMatrixButton,
        en.customsApprovalAutoGenerateStandardListButton,
        en.customsApprovalRaiseTicketButton,
        en.customsApprovalFilterAll,
        en.customsApprovalFilterPending,
        en.customsApprovalFilterApproved,
        en.customsApprovalFilterRejected,
        en.customsApprovalFilterDiscrepancy,
        en.customsApprovalTabDualSignoff,
        en.customsApprovalTabCentralArchive,
        en.customsApprovalMatrixComplianceResult('Fully Compliant', 5, 5),
        en.customsApprovalMatrixRecommendations('Check HS codes'),
        en.customsApprovalMatrixOpenTicketsCount(2),
        en.customsApprovalDualTierHeader,
        en.customsApprovalNoDocuments,
        en.customsApprovalError('Network Error'),
        en.customsApprovalDocRef('INV-902'),
        en.customsApprovalCommercialReviewStatus('Approved'),
        en.customsApprovalBrokerReviewStatus('Approved'),
        en.customsApprovalTicketsHeader,
        en.customsApprovalNewTicketButton,
        en.customsApprovalNoTickets,
        en.customsApprovalTicketExpectedVsFound('100 kg', '120 kg'),
        en.customsApprovalResolveTicketButton,
        en.customsApprovalCommercialDialogTitle('Commercial Invoice'),
        en.customsApprovalCommercialReviewerLabel,
        en.customsApprovalRequiredField,
        en.customsApprovalCommercialDecisionLabel,
        en.customsApprovalSelectDecisionHint,
        en.customsApprovalDecisionCommercialApproved,
        en.customsApprovalDecisionCommercialUnderReview,
        en.customsApprovalDecisionCommercialRejected,
        en.customsApprovalCommercialNotesLabel,
        en.customsApprovalSaveApprovalButton,
        en.customsApprovalBrokerDialogTitle('Bill of Lading'),
        en.customsApprovalBrokerOfficeLabel,
        en.customsApprovalBrokerReviewerNameLabel,
        en.customsApprovalBrokerDecisionLabel,
        en.customsApprovalDecisionBrokerApproved,
        en.customsApprovalDecisionBrokerConditionallyApproved,
        en.customsApprovalDecisionBrokerRejected,
        en.customsApprovalBrokerNotesLabel,
        en.customsApprovalBrokerSaveStampButton,
        en.customsApprovalRaiseTicketDialogTitle,
        en.customsApprovalIssueCategoryLabel,
        en.customsApprovalSelectCategoryHint,
        en.customsApprovalCatHsMismatch,
        en.customsApprovalCatWeightDiscrepancy,
        en.customsApprovalCatCbmDiscrepancy,
        en.customsApprovalCatValueMismatch,
        en.customsApprovalCatMissingAcid,
        en.customsApprovalCatIncotermConflict,
        en.customsApprovalCatOther,
        en.customsApprovalSeverityLabel,
        en.customsApprovalSelectSeverityHint,
        en.customsApprovalSevCritical,
        en.customsApprovalSevMajor,
        en.customsApprovalSevMinor,
        en.customsApprovalIssueDescLabel,
        en.customsApprovalIssueDescMinLength,
        en.customsApprovalExpectedValueLabel,
        en.customsApprovalFoundValueLabel,
        en.customsApprovalSupplierActionLabel,
        en.customsApprovalCreateTicketSubmitButton,
        en.customsApprovalResolveTicketDialogTitle('TCK-001'),
        en.customsApprovalSupplierResponseLabel,
        en.customsApprovalResolverNameLabel,
        en.customsApprovalFinalStatusLabel,
        en.customsApprovalSelectStatusHint,
        en.customsApprovalStatusResolved,
        en.customsApprovalStatusWaived,
        en.customsApprovalStatusClosed,
        en.customsApprovalConfirmResolveTicketButton,
      ];

      expect(arStrings.length, equals(enStrings.length));

      for (final s in arStrings) {
        expect(s.trim().isNotEmpty, isTrue, reason: 'Arabic string must not be empty');
      }

      for (final s in enStrings) {
        expect(s.trim().isNotEmpty, isTrue, reason: 'English string must not be empty');
      }
    });

    test('English translations should not contain Arabic characters', () {
      final arabicRegex = RegExp(r'[\u0600-\u06FF]');
      final List<String> enStrings = [
        en.customsApprovalSelectFileForMatrixWarning,
        en.customsApprovalMatrixCheckCompleted('Fully Compliant'),
        en.customsApprovalMatrixCheckFailed('Timeout'),
        en.customsApprovalSelectFileWarning,
        en.customsApprovalStandardListGeneratedSuccess,
        en.customsApprovalGenerateFailed('DB Error'),
        en.customsApprovalSelectFileForTicketWarning,
        en.customsApprovalImportFileLabel,
        en.customsApprovalSearchFileHint,
        en.customsApprovalRunAiMatrixButton,
        en.customsApprovalAutoGenerateStandardListButton,
        en.customsApprovalRaiseTicketButton,
        en.customsApprovalFilterAll,
        en.customsApprovalFilterPending,
        en.customsApprovalFilterApproved,
        en.customsApprovalFilterRejected,
        en.customsApprovalFilterDiscrepancy,
        en.customsApprovalTabDualSignoff,
        en.customsApprovalTabCentralArchive,
        en.customsApprovalMatrixComplianceResult('Fully Compliant', 5, 5),
        en.customsApprovalMatrixRecommendations('Check HS codes'),
        en.customsApprovalMatrixOpenTicketsCount(2),
        en.customsApprovalDualTierHeader,
        en.customsApprovalNoDocuments,
        en.customsApprovalError('Network Error'),
        en.customsApprovalDocRef('INV-902'),
        en.customsApprovalCommercialReviewStatus('Approved'),
        en.customsApprovalBrokerReviewStatus('Approved'),
        en.customsApprovalTicketsHeader,
        en.customsApprovalNewTicketButton,
        en.customsApprovalNoTickets,
        en.customsApprovalTicketExpectedVsFound('100 kg', '120 kg'),
        en.customsApprovalResolveTicketButton,
        en.customsApprovalCommercialDialogTitle('Commercial Invoice'),
        en.customsApprovalCommercialReviewerLabel,
        en.customsApprovalRequiredField,
        en.customsApprovalCommercialDecisionLabel,
        en.customsApprovalSelectDecisionHint,
        en.customsApprovalDecisionCommercialApproved,
        en.customsApprovalDecisionCommercialUnderReview,
        en.customsApprovalDecisionCommercialRejected,
        en.customsApprovalCommercialNotesLabel,
        en.customsApprovalSaveApprovalButton,
        en.customsApprovalBrokerDialogTitle('Bill of Lading'),
        en.customsApprovalBrokerOfficeLabel,
        en.customsApprovalBrokerReviewerNameLabel,
        en.customsApprovalBrokerDecisionLabel,
        en.customsApprovalDecisionBrokerApproved,
        en.customsApprovalDecisionBrokerConditionallyApproved,
        en.customsApprovalDecisionBrokerRejected,
        en.customsApprovalBrokerNotesLabel,
        en.customsApprovalBrokerSaveStampButton,
        en.customsApprovalRaiseTicketDialogTitle,
        en.customsApprovalIssueCategoryLabel,
        en.customsApprovalSelectCategoryHint,
        en.customsApprovalCatHsMismatch,
        en.customsApprovalCatWeightDiscrepancy,
        en.customsApprovalCatCbmDiscrepancy,
        en.customsApprovalCatValueMismatch,
        en.customsApprovalCatMissingAcid,
        en.customsApprovalCatIncotermConflict,
        en.customsApprovalCatOther,
        en.customsApprovalSeverityLabel,
        en.customsApprovalSelectSeverityHint,
        en.customsApprovalSevCritical,
        en.customsApprovalSevMajor,
        en.customsApprovalSevMinor,
        en.customsApprovalIssueDescLabel,
        en.customsApprovalIssueDescMinLength,
        en.customsApprovalExpectedValueLabel,
        en.customsApprovalFoundValueLabel,
        en.customsApprovalSupplierActionLabel,
        en.customsApprovalCreateTicketSubmitButton,
        en.customsApprovalResolveTicketDialogTitle('TCK-001'),
        en.customsApprovalSupplierResponseLabel,
        en.customsApprovalResolverNameLabel,
        en.customsApprovalFinalStatusLabel,
        en.customsApprovalSelectStatusHint,
        en.customsApprovalStatusResolved,
        en.customsApprovalStatusWaived,
        en.customsApprovalStatusClosed,
        en.customsApprovalConfirmResolveTicketButton,
      ];

      for (final s in enStrings) {
        expect(arabicRegex.hasMatch(s), isFalse, reason: 'English string should not contain Arabic: "$s"');
      }
    });

    test('Translations should not contain stacked bilingual formatting like "Arabic / English"', () {
      final List<String> labels = [
        ar.customsApprovalImportFileLabel,
        en.customsApprovalImportFileLabel,
        ar.customsApprovalRunAiMatrixButton,
        en.customsApprovalRunAiMatrixButton,
        ar.customsApprovalFilterAll,
        en.customsApprovalFilterAll,
        ar.customsApprovalFilterPending,
        en.customsApprovalFilterPending,
        ar.customsApprovalFilterApproved,
        en.customsApprovalFilterApproved,
        ar.customsApprovalFilterRejected,
        en.customsApprovalFilterRejected,
        ar.customsApprovalFilterDiscrepancy,
        en.customsApprovalFilterDiscrepancy,
        ar.customsApprovalDualTierHeader,
        en.customsApprovalDualTierHeader,
        ar.customsApprovalCatHsMismatch,
        en.customsApprovalCatHsMismatch,
        ar.customsApprovalCatWeightDiscrepancy,
        en.customsApprovalCatWeightDiscrepancy,
        ar.customsApprovalCatCbmDiscrepancy,
        en.customsApprovalCatCbmDiscrepancy,
        ar.customsApprovalSevCritical,
        en.customsApprovalSevCritical,
        ar.customsApprovalSevMajor,
        en.customsApprovalSevMajor,
        ar.customsApprovalStatusResolved,
        en.customsApprovalStatusResolved,
      ];

      for (final label in labels) {
        expect(label.contains(' / '), isFalse, reason: 'Must not contain " / " stacking: $label');
      }
    });
  });
}
