import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/core/localization/app_localizations.dart';
import 'package:frontend/core/localization/app_localizations_ar.dart';
import 'package:frontend/core/localization/app_localizations_en.dart';

void main() {
  group('Screen 24: Customs Clearance Management Localization Tests', () {
    const AppLocalizations ar = AppLocalizationsAr();
    const AppLocalizations en = AppLocalizationsEn();

    test('All Screen 24 getters should have non-empty Arabic and English translations', () {
      final List<String> arStrings = [
        ar.customsClearanceStageTitle,
        ar.customsClearanceTabFollowUp,
        ar.customsClearanceTabSamples,
        ar.customsClearanceTabDiscrepancy,
        ar.customsClearanceTabDutyPayment,
        ar.customsClearanceErrorFetch('error'),
        ar.customsClearanceSearchHint,
        ar.customsClearanceFilterAll,
        ar.customsClearanceFilterInspection,
        ar.customsClearanceFilterDutyRequested,
        ar.customsClearanceFilterDutyPaid,
        ar.customsClearanceFilterFinalRelease,
        ar.customsClearanceNewRecordButton,
        ar.customsClearanceEmptyRecords,
        ar.customsClearanceDeclaration46Label,
        ar.customsClearanceDeliveryOrderLabel,
        ar.customsClearanceOfficeLabel,
        ar.customsClearanceFileRefLabel,
        ar.customsClearanceFreeDaysLabel(14),
        ar.customsClearanceTotalDutiesCard,
        ar.customsClearanceEstimatedDutiesCard('1000', '+50', '5.0'),
        ar.customsClearancePaymentStatusLabel,
        ar.customsClearanceStatusPaid,
        ar.customsClearanceStatusPendingPayment,
        ar.customsClearanceEditTooltip,
        ar.customsClearancePayTooltip,
        ar.customsClearanceReleaseTooltip,
        ar.customsClearanceSamplesBannerTitle,
        ar.customsClearanceSamplesBannerDesc,
        ar.customsClearanceAddSampleButton,
        ar.customsClearanceSamplesTableTitle,
        ar.customsClearanceColSampleCode,
        ar.customsClearanceColAuthority,
        ar.customsClearanceColDrawingDate,
        ar.customsClearanceColReceiptNo,
        ar.customsClearanceColTestType,
        ar.customsClearanceColTestResult,
        ar.customsClearanceColNotes,
        ar.customsClearanceSamplePassed,
        ar.customsClearanceSamplePending,
        ar.customsClearanceAddSampleDialogTitle,
        ar.customsClearanceSampleAuthLabel,
        ar.customsClearanceSampleReceiptLabel,
        ar.customsClearanceSampleTestTypeLabel,
        ar.customsClearanceSampleNotesLabel,
        ar.customsClearanceSampleSaveButton,
        ar.customsClearanceSampleSaveSuccess,
        ar.customsClearanceDamageBannerTitle,
        ar.customsClearanceDamageBannerDesc,
        ar.customsClearanceAddDamageButton,
        ar.customsClearanceDamageTableTitle,
        ar.customsClearanceColProtocolNo,
        ar.customsClearanceColDeclarationNo,
        ar.customsClearanceColContainerNo,
        ar.customsClearanceColDamageType,
        ar.customsClearanceColDamagedQty,
        ar.customsClearanceColEstimatedLoss,
        ar.customsClearanceColResponsibleParty,
        ar.customsClearanceColClaimStatus,
        ar.customsClearanceColDate,
        ar.customsClearanceClaimApproved,
        ar.customsClearanceClaimSubmitted,
        ar.customsClearanceAddDamageDialogTitle,
        ar.customsClearanceDamageDeclLabel,
        ar.customsClearanceDamageContainerLabel,
        ar.customsClearanceDamageTypeLabel,
        ar.customsClearanceDamagedQtyLabel,
        ar.customsClearanceDamageLossLabel,
        ar.customsClearanceDamagePartyLabel,
        ar.customsClearanceDamageNotesLabel,
        ar.customsClearanceDamageSaveButton,
        ar.customsClearanceDamageSaveSuccess,
        ar.customsClearancePaymentBannerTitle,
        ar.customsClearancePaymentBannerDesc,
        ar.customsClearanceDutyLedgerTableTitle,
        ar.customsClearanceEmptyDutyLedger,
        ar.customsClearanceColClearanceCode,
        ar.customsClearanceColDecl46,
        ar.customsClearanceColCustomsOffice,
        ar.customsClearanceColActualDuty,
        ar.customsClearanceColEstimatedDuty,
        ar.customsClearanceColDutyVariance,
        ar.customsClearanceColPaymentStatus,
        ar.customsClearanceColActions,
        ar.customsClearanceBtnPaymentDetails,
        ar.customsClearanceBtnPayReconcile,
        ar.customsClearanceBtnFinalRelease,
        ar.customsClearanceNewDialogTitle,
        ar.customsClearanceEditDialogTitle('CLR-001'),
        ar.customsClearanceExtractNafezaBtn,
        ar.customsClearanceExtractNafezaSuccess,
        ar.customsClearanceImportFileLabel,
        ar.customsClearanceImportFileSearchHint,
        ar.customsClearanceSelectFileValidator,
        ar.customsClearanceDecl46Label,
        ar.customsClearanceDoNumberLabel,
        ar.customsClearanceFreeDaysInputLabel,
        ar.customsClearanceOfficeInputLabel,
        ar.customsClearanceOfficeValidator,
        ar.customsClearanceChannelLabel,
        ar.customsClearanceChannelRed,
        ar.customsClearanceChannelGreen,
        ar.customsClearanceChannelYellow,
        ar.customsClearanceDutyBreakdownHeader,
        ar.customsClearanceImportDutyInput,
        ar.customsClearanceVatInput,
        ar.customsClearanceScheduleTaxInput,
        ar.customsClearanceWhtInput,
        ar.customsClearanceLabFeesInput,
        ar.customsClearanceEstimatedDutyInput,
        ar.customsClearanceSaveRecordBtn,
        ar.customsClearanceSaveRecordSuccess,
        ar.customsClearanceSaveRecordError('err'),
        ar.customsClearanceDutyPaymentDialogTitle('CLR-001'),
        ar.customsClearanceExtractReceiptBtn,
        ar.customsClearanceEstimatorDutyBoxLabel('5000.00'),
        ar.customsClearanceNafezaDutyBoxLabel('5200.00'),
        ar.customsClearanceVarianceBoxLabel,
        ar.customsClearanceActualPaidInput,
        ar.customsClearanceBankReceiptInput,
        ar.customsClearanceVarianceReasonInput,
        ar.customsClearanceConfirmPaymentBtn,
        ar.customsClearancePaymentSuccess,
        ar.customsClearancePaymentError('err'),
        ar.customsClearanceFinalReleaseDialogTitle,
        ar.customsClearanceFinalReleaseDialogDesc,
        ar.customsClearanceReleasePermitInput,
        ar.customsClearanceConfirmReleaseBtn,
        ar.customsClearanceReleaseSuccess,
        ar.customsClearanceReleaseError('err'),
      ];

      final List<String> enStrings = [
        en.customsClearanceStageTitle,
        en.customsClearanceTabFollowUp,
        en.customsClearanceTabSamples,
        en.customsClearanceTabDiscrepancy,
        en.customsClearanceTabDutyPayment,
        en.customsClearanceErrorFetch('error'),
        en.customsClearanceSearchHint,
        en.customsClearanceFilterAll,
        en.customsClearanceFilterInspection,
        en.customsClearanceFilterDutyRequested,
        en.customsClearanceFilterDutyPaid,
        en.customsClearanceFilterFinalRelease,
        en.customsClearanceNewRecordButton,
        en.customsClearanceEmptyRecords,
        en.customsClearanceDeclaration46Label,
        en.customsClearanceDeliveryOrderLabel,
        en.customsClearanceOfficeLabel,
        en.customsClearanceFileRefLabel,
        en.customsClearanceFreeDaysLabel(14),
        en.customsClearanceTotalDutiesCard,
        en.customsClearanceEstimatedDutiesCard('1000', '+50', '5.0'),
        en.customsClearancePaymentStatusLabel,
        en.customsClearanceStatusPaid,
        en.customsClearanceStatusPendingPayment,
        en.customsClearanceEditTooltip,
        en.customsClearancePayTooltip,
        en.customsClearanceReleaseTooltip,
        en.customsClearanceSamplesBannerTitle,
        en.customsClearanceSamplesBannerDesc,
        en.customsClearanceAddSampleButton,
        en.customsClearanceSamplesTableTitle,
        en.customsClearanceColSampleCode,
        en.customsClearanceColAuthority,
        en.customsClearanceColDrawingDate,
        en.customsClearanceColReceiptNo,
        en.customsClearanceColTestType,
        en.customsClearanceColTestResult,
        en.customsClearanceColNotes,
        en.customsClearanceSamplePassed,
        en.customsClearanceSamplePending,
        en.customsClearanceAddSampleDialogTitle,
        en.customsClearanceSampleAuthLabel,
        en.customsClearanceSampleReceiptLabel,
        en.customsClearanceSampleTestTypeLabel,
        en.customsClearanceSampleNotesLabel,
        en.customsClearanceSampleSaveButton,
        en.customsClearanceSampleSaveSuccess,
        en.customsClearanceDamageBannerTitle,
        en.customsClearanceDamageBannerDesc,
        en.customsClearanceAddDamageButton,
        en.customsClearanceDamageTableTitle,
        en.customsClearanceColProtocolNo,
        en.customsClearanceColDeclarationNo,
        en.customsClearanceColContainerNo,
        en.customsClearanceColDamageType,
        en.customsClearanceColDamagedQty,
        en.customsClearanceColEstimatedLoss,
        en.customsClearanceColResponsibleParty,
        en.customsClearanceColClaimStatus,
        en.customsClearanceColDate,
        en.customsClearanceClaimApproved,
        en.customsClearanceClaimSubmitted,
        en.customsClearanceAddDamageDialogTitle,
        en.customsClearanceDamageDeclLabel,
        en.customsClearanceDamageContainerLabel,
        en.customsClearanceDamageTypeLabel,
        en.customsClearanceDamagedQtyLabel,
        en.customsClearanceDamageLossLabel,
        en.customsClearanceDamagePartyLabel,
        en.customsClearanceDamageNotesLabel,
        en.customsClearanceDamageSaveButton,
        en.customsClearanceDamageSaveSuccess,
        en.customsClearancePaymentBannerTitle,
        en.customsClearancePaymentBannerDesc,
        en.customsClearanceDutyLedgerTableTitle,
        en.customsClearanceEmptyDutyLedger,
        en.customsClearanceColClearanceCode,
        en.customsClearanceColDecl46,
        en.customsClearanceColCustomsOffice,
        en.customsClearanceColActualDuty,
        en.customsClearanceColEstimatedDuty,
        en.customsClearanceColDutyVariance,
        en.customsClearanceColPaymentStatus,
        en.customsClearanceColActions,
        en.customsClearanceBtnPaymentDetails,
        en.customsClearanceBtnPayReconcile,
        en.customsClearanceBtnFinalRelease,
        en.customsClearanceNewDialogTitle,
        en.customsClearanceEditDialogTitle('CLR-001'),
        en.customsClearanceExtractNafezaBtn,
        en.customsClearanceExtractNafezaSuccess,
        en.customsClearanceImportFileLabel,
        en.customsClearanceImportFileSearchHint,
        en.customsClearanceSelectFileValidator,
        en.customsClearanceDecl46Label,
        en.customsClearanceDoNumberLabel,
        en.customsClearanceFreeDaysInputLabel,
        en.customsClearanceOfficeInputLabel,
        en.customsClearanceOfficeValidator,
        en.customsClearanceChannelLabel,
        en.customsClearanceChannelRed,
        en.customsClearanceChannelGreen,
        en.customsClearanceChannelYellow,
        en.customsClearanceDutyBreakdownHeader,
        en.customsClearanceImportDutyInput,
        en.customsClearanceVatInput,
        en.customsClearanceScheduleTaxInput,
        en.customsClearanceWhtInput,
        en.customsClearanceLabFeesInput,
        en.customsClearanceEstimatedDutyInput,
        en.customsClearanceSaveRecordBtn,
        en.customsClearanceSaveRecordSuccess,
        en.customsClearanceSaveRecordError('err'),
        en.customsClearanceDutyPaymentDialogTitle('CLR-001'),
        en.customsClearanceExtractReceiptBtn,
        en.customsClearanceEstimatorDutyBoxLabel('5000.00'),
        en.customsClearanceNafezaDutyBoxLabel('5200.00'),
        en.customsClearanceVarianceBoxLabel,
        en.customsClearanceActualPaidInput,
        en.customsClearanceBankReceiptInput,
        en.customsClearanceVarianceReasonInput,
        en.customsClearanceConfirmPaymentBtn,
        en.customsClearancePaymentSuccess,
        en.customsClearancePaymentError('err'),
        en.customsClearanceFinalReleaseDialogTitle,
        en.customsClearanceFinalReleaseDialogDesc,
        en.customsClearanceReleasePermitInput,
        en.customsClearanceConfirmReleaseBtn,
        en.customsClearanceReleaseSuccess,
        en.customsClearanceReleaseError('err'),
      ];

      for (final s in arStrings) {
        expect(s.trim().isNotEmpty, isTrue, reason: 'Arabic translation string must not be empty');
      }

      for (final s in enStrings) {
        expect(s.trim().isNotEmpty, isTrue, reason: 'English translation string must not be empty');
      }
    });

    test('Translations should NOT contain stacked bilingual text patterns', () {
      final List<String> allAr = [
        ar.customsClearanceStageTitle,
        ar.customsClearanceTabFollowUp,
        ar.customsClearanceTabSamples,
        ar.customsClearanceTabDiscrepancy,
        ar.customsClearanceTabDutyPayment,
        ar.customsClearanceSamplesBannerTitle,
        ar.customsClearanceSamplesBannerDesc,
        ar.customsClearanceSamplesTableTitle,
        ar.customsClearanceDamageBannerTitle,
        ar.customsClearanceDamageBannerDesc,
        ar.customsClearanceDamageTableTitle,
        ar.customsClearancePaymentBannerTitle,
        ar.customsClearancePaymentBannerDesc,
        ar.customsClearanceDutyLedgerTableTitle,
        ar.customsClearanceDutyBreakdownHeader,
      ];

      final List<String> allEn = [
        en.customsClearanceStageTitle,
        en.customsClearanceTabFollowUp,
        en.customsClearanceTabSamples,
        en.customsClearanceTabDiscrepancy,
        en.customsClearanceTabDutyPayment,
        en.customsClearanceSamplesBannerTitle,
        en.customsClearanceSamplesBannerDesc,
        en.customsClearanceSamplesTableTitle,
        en.customsClearanceDamageBannerTitle,
        en.customsClearanceDamageBannerDesc,
        en.customsClearanceDamageTableTitle,
        en.customsClearancePaymentBannerTitle,
        en.customsClearancePaymentBannerDesc,
        en.customsClearanceDutyLedgerTableTitle,
        en.customsClearanceDutyBreakdownHeader,
      ];

      // Verify no stacked patterns like "Arabic (English)" or slash combinations
      for (final s in allAr) {
        expect(s.contains('Drawing Samples & Shortage'), isFalse);
        expect(s.contains('Discrepancy & Damage Protocols'), isFalse);
        expect(s.contains('Final Duty Payment & Gate Pass'), isFalse);
        expect(s.contains('Nafeza Duty Assessment & Ledger'), isFalse);
        expect(s.contains('Duty Breakdown EGP'), isFalse);
      }

      for (final s in allEn) {
        expect(s.contains('الميناء والتخليص'), isFalse);
        expect(s.contains('سحب العينات'), isFalse);
        expect(s.contains('إثبات الفاقد'), isFalse);
        expect(s.contains('سداد الرسوم'), isFalse);
      }
    });

    test('Parameterized methods produce correct dynamic output', () {
      expect(ar.customsClearanceFreeDaysLabel(14), contains('14'));
      expect(en.customsClearanceFreeDaysLabel(14), contains('14'));
      expect(ar.customsClearanceEditDialogTitle('CLR-99'), contains('CLR-99'));
      expect(en.customsClearanceEditDialogTitle('CLR-99'), contains('CLR-99'));
      expect(ar.customsClearanceDutyPaymentDialogTitle('CLR-99'), contains('CLR-99'));
      expect(en.customsClearanceDutyPaymentDialogTitle('CLR-99'), contains('CLR-99'));
      expect(ar.customsClearanceEstimatedDutiesCard('100.00', '+10.00', '10'), contains('100.00'));
      expect(en.customsClearanceEstimatedDutiesCard('100.00', '+10.00', '10'), contains('100.00'));
    });
  });
}
