import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/core/localization/app_localizations.dart';
import 'package:frontend/core/localization/app_localizations_ar.dart';
import 'package:frontend/core/localization/app_localizations_en.dart';

void main() {
  group('Screen 44: Demurrage & Detention Localization Tests', () {
    late AppLocalizations ar;
    late AppLocalizations en;

    setUp(() {
      ar = const AppLocalizationsAr();
      en = const AppLocalizationsEn();
    });

    test('All Screen 44 getters should return non-empty strings in Arabic and English', () {
      // Screen title & Tabs
      expect(ar.demurrageScreenTitle, isNotEmpty);
      expect(en.demurrageScreenTitle, isNotEmpty);
      expect(ar.containerTrackingsTab, isNotEmpty);
      expect(en.containerTrackingsTab, isNotEmpty);
      expect(ar.simulatorAndTierCalcTab, isNotEmpty);
      expect(en.simulatorAndTierCalcTab, isNotEmpty);
      expect(ar.carrierTariffPoliciesTab, isNotEmpty);
      expect(en.carrierTariffPoliciesTab, isNotEmpty);

      // Tab 1: KPIs & Filter
      expect(ar.totalActiveTrackingsMetric, isNotEmpty);
      expect(en.totalActiveTrackingsMetric, isNotEmpty);
      expect(ar.activeShipmentsCount(5), contains('5'));
      expect(en.activeShipmentsCount(5), contains('5'));
      expect(ar.incurredDemurrageShipmentsMetric, isNotEmpty);
      expect(en.incurredDemurrageShipmentsMetric, isNotEmpty);
      expect(ar.totalCalculatedDemurrageMetric, isNotEmpty);
      expect(en.totalCalculatedDemurrageMetric, isNotEmpty);
      expect(ar.searchDemurrageHint, isNotEmpty);
      expect(en.searchDemurrageHint, isNotEmpty);
      expect(ar.statusFilterLabel, isNotEmpty);
      expect(en.statusFilterLabel, isNotEmpty);
      expect(ar.allStatusesOption, isNotEmpty);
      expect(en.allStatusesOption, isNotEmpty);
      expect(ar.statusFreeTimeActive, isNotEmpty);
      expect(en.statusFreeTimeActive, isNotEmpty);
      expect(ar.statusDemurrageIncurred, isNotEmpty);
      expect(en.statusDemurrageIncurred, isNotEmpty);
      expect(ar.statusDetentionIncurred, isNotEmpty);
      expect(en.statusDetentionIncurred, isNotEmpty);
      expect(ar.statusPushedToSettlement, isNotEmpty);
      expect(en.statusPushedToSettlement, isNotEmpty);
      expect(ar.startNewTrackingBtn, isNotEmpty);
      expect(en.startNewTrackingBtn, isNotEmpty);
      expect(ar.noTrackingsFound, isNotEmpty);
      expect(en.noTrackingsFound, isNotEmpty);

      // Tracking Card
      expect(ar.billOfLadingLabel('BL12345'), contains('BL12345'));
      expect(en.billOfLadingLabel('BL12345'), contains('BL12345'));
      expect(ar.dischargeDateLabel, isNotEmpty);
      expect(en.dischargeDateLabel, isNotEmpty);
      expect(ar.gateOutDateLabel, isNotEmpty);
      expect(en.gateOutDateLabel, isNotEmpty);
      expect(ar.notGatedOutYet, isNotEmpty);
      expect(en.notGatedOutYet, isNotEmpty);
      expect(ar.emptyReturnDateLabel, isNotEmpty);
      expect(en.emptyReturnDateLabel, isNotEmpty);
      expect(ar.notReturnedYet, isNotEmpty);
      expect(en.notReturnedYet, isNotEmpty);
      expect(ar.containersCountLabel, isNotEmpty);
      expect(en.containersCountLabel, isNotEmpty);
      expect(ar.containersCountValue(3), contains('3'));
      expect(en.containersCountValue(3), contains('3'));
      expect(ar.totalEstimatedCostLabel, isNotEmpty);
      expect(en.totalEstimatedCostLabel, isNotEmpty);
      expect(ar.updateGateOutAndReturnDatesBtn, isNotEmpty);
      expect(en.updateGateOutAndReturnDatesBtn, isNotEmpty);
      expect(ar.pushToFinancialSettlementBtn, isNotEmpty);
      expect(en.pushToFinancialSettlementBtn, isNotEmpty);
      expect(ar.alreadyPushedToSettlementBtn, isNotEmpty);
      expect(en.alreadyPushedToSettlementBtn, isNotEmpty);

      // Tab 2: Simulator Form
      expect(ar.calculationSettingsTitle, isNotEmpty);
      expect(en.calculationSettingsTitle, isNotEmpty);
      expect(ar.shippingLineFieldLabel, isNotEmpty);
      expect(en.shippingLineFieldLabel, isNotEmpty);
      expect(ar.containerTypeFieldLabel, isNotEmpty);
      expect(en.containerTypeFieldLabel, isNotEmpty);
      expect(ar.containersCountFieldLabel, isNotEmpty);
      expect(en.containersCountFieldLabel, isNotEmpty);
      expect(ar.exchangeRateFieldLabel, isNotEmpty);
      expect(en.exchangeRateFieldLabel, isNotEmpty);
      expect(ar.grantedFreeDaysHeader, isNotEmpty);
      expect(en.grantedFreeDaysHeader, isNotEmpty);
      expect(ar.portDemurrageFreeDaysLabel, isNotEmpty);
      expect(en.portDemurrageFreeDaysLabel, isNotEmpty);
      expect(ar.emptyReturnFreeDaysLabel, isNotEmpty);
      expect(en.emptyReturnFreeDaysLabel, isNotEmpty);
      expect(ar.operationalMilestonesHeader, isNotEmpty);
      expect(en.operationalMilestonesHeader, isNotEmpty);
      expect(ar.vesselDischargeDateMilestone, isNotEmpty);
      expect(en.vesselDischargeDateMilestone, isNotEmpty);
      expect(ar.portGateOutDateMilestone, isNotEmpty);
      expect(en.portGateOutDateMilestone, isNotEmpty);
      expect(ar.notGatedOutCalculatedToday, isNotEmpty);
      expect(en.notGatedOutCalculatedToday, isNotEmpty);
      expect(ar.emptyReturnToDepotMilestone, isNotEmpty);
      expect(en.emptyReturnToDepotMilestone, isNotEmpty);
      expect(ar.recalculateDemurrageNowBtn, isNotEmpty);
      expect(en.recalculateDemurrageNowBtn, isNotEmpty);

      // Simulator Results
      expect(ar.initializingSimulationResults, isNotEmpty);
      expect(en.initializingSimulationResults, isNotEmpty);
      expect(ar.totalDemurrageCostSummaryTitle, isNotEmpty);
      expect(en.totalDemurrageCostSummaryTitle, isNotEmpty);
      expect(ar.demurrageFeeMetric, isNotEmpty);
      expect(en.demurrageFeeMetric, isNotEmpty);
      expect(ar.detentionFeeMetric, isNotEmpty);
      expect(en.detentionFeeMetric, isNotEmpty);
      expect(ar.portStorageFeeMetric, isNotEmpty);
      expect(en.portStorageFeeMetric, isNotEmpty);
      expect(ar.daysOverdueFormatted(4), contains('4'));
      expect(en.daysOverdueFormatted(4), contains('4'));
      expect(ar.totalDueComprehensiveCost, isNotEmpty);
      expect(en.totalDueComprehensiveCost, isNotEmpty);
      expect(ar.egpCurrencyAmount(1200), contains('1200'));
      expect(en.egpCurrencyAmount(1200), contains('1200'));
      expect(ar.tieredBreakdownTitle, isNotEmpty);
      expect(en.tieredBreakdownTitle, isNotEmpty);
      expect(ar.colCategory, isNotEmpty);
      expect(en.colCategory, isNotEmpty);
      expect(ar.colConsumedDays, isNotEmpty);
      expect(en.colConsumedDays, isNotEmpty);
      expect(ar.colFreeDays, isNotEmpty);
      expect(en.colFreeDays, isNotEmpty);
      expect(ar.colOverdueDays, isNotEmpty);
      expect(en.colOverdueDays, isNotEmpty);
      expect(ar.colFeeAmount, isNotEmpty);
      expect(en.colFeeAmount, isNotEmpty);
      expect(ar.daysCountFormatted(7), contains('7'));
      expect(en.daysCountFormatted(7), contains('7'));
      expect(ar.demurrageCategoryLabel('Demurrage'), isNotEmpty);
      expect(en.demurrageCategoryLabel('Demurrage'), equals('Demurrage'));

      // Tab 3: Carrier Policies
      expect(ar.carrierTariffPoliciesTitle, isNotEmpty);
      expect(en.carrierTariffPoliciesTitle, isNotEmpty);
      expect(ar.carrierTariffPoliciesSubtitle, isNotEmpty);
      expect(en.carrierTariffPoliciesSubtitle, isNotEmpty);
      expect(ar.addCarrierPolicyBtn, isNotEmpty);
      expect(en.addCarrierPolicyBtn, isNotEmpty);
      expect(ar.noCarrierPoliciesFound, isNotEmpty);
      expect(en.noCarrierPoliciesFound, isNotEmpty);
      expect(ar.currencyLabelFormatted('USD'), contains('USD'));
      expect(en.currencyLabelFormatted('USD'), contains('USD'));
      expect(ar.demurrageFreeLabel, isNotEmpty);
      expect(en.demurrageFreeLabel, isNotEmpty);
      expect(ar.detentionFreeLabel, isNotEmpty);
      expect(en.detentionFreeLabel, isNotEmpty);
      expect(ar.portStorageFreeLabel, isNotEmpty);
      expect(en.portStorageFreeLabel, isNotEmpty);
      expect(ar.dailyStorageRateLabel, isNotEmpty);
      expect(en.dailyStorageRateLabel, isNotEmpty);
      expect(ar.egpPerDayFormatted(250), contains('250'));
      expect(en.egpPerDayFormatted(250), contains('250'));

      // Dialogs & Actions
      expect(ar.addTrackingDialogTitle, isNotEmpty);
      expect(en.addTrackingDialogTitle, isNotEmpty);
      expect(ar.arrivalPortFieldLabel, isNotEmpty);
      expect(en.arrivalPortFieldLabel, isNotEmpty);
      expect(ar.blNumberFieldLabel, isNotEmpty);
      expect(en.blNumberFieldLabel, isNotEmpty);
      expect(ar.containerNumberFieldLabel, isNotEmpty);
      expect(en.containerNumberFieldLabel, isNotEmpty);
      expect(ar.portDischargeDateTile, isNotEmpty);
      expect(en.portDischargeDateTile, isNotEmpty);
      expect(ar.saveAndStartTrackingBtn, isNotEmpty);
      expect(en.saveAndStartTrackingBtn, isNotEmpty);
      expect(ar.trackingCreatedSuccessSnack, isNotEmpty);
      expect(en.trackingCreatedSuccessSnack, isNotEmpty);
      expect(ar.saveTrackingErrorSnack, isNotEmpty);
      expect(en.saveTrackingErrorSnack, isNotEmpty);
      expect(ar.updateTrackingDatesDialogTitle('TRK-001'), contains('TRK-001'));
      expect(en.updateTrackingDatesDialogTitle('TRK-001'), contains('TRK-001'));
      expect(ar.gateOutDateTile, isNotEmpty);
      expect(en.gateOutDateTile, isNotEmpty);
      expect(ar.emptyReturnDateTile, isNotEmpty);
      expect(en.emptyReturnDateTile, isNotEmpty);
      expect(ar.notRecordedOption, isNotEmpty);
      expect(en.notRecordedOption, isNotEmpty);
      expect(ar.saveAndRecalculateBtn, isNotEmpty);
      expect(en.saveAndRecalculateBtn, isNotEmpty);
      expect(ar.datesUpdatedAndRecalculatedSuccessSnack, isNotEmpty);
      expect(en.datesUpdatedAndRecalculatedSuccessSnack, isNotEmpty);
      expect(ar.datesUpdateErrorSnack, isNotEmpty);
      expect(en.datesUpdateErrorSnack, isNotEmpty);
      expect(ar.pushedToSettlementSuccessSnack, isNotEmpty);
      expect(en.pushedToSettlementSuccessSnack, isNotEmpty);
      expect(ar.pushToSettlementErrorSnack, isNotEmpty);
      expect(en.pushToSettlementErrorSnack, isNotEmpty);
      expect(ar.addPolicyDialogTitle, isNotEmpty);
      expect(en.addPolicyDialogTitle, isNotEmpty);
      expect(ar.demurrageFreeDaysFieldLabel, isNotEmpty);
      expect(en.demurrageFreeDaysFieldLabel, isNotEmpty);
      expect(ar.detentionFreeDaysFieldLabel, isNotEmpty);
      expect(en.detentionFreeDaysFieldLabel, isNotEmpty);
      expect(ar.portStorageFreeDaysFieldLabel, isNotEmpty);
      expect(en.portStorageFreeDaysFieldLabel, isNotEmpty);
      expect(ar.dailyStorageRateEgpFieldLabel, isNotEmpty);
      expect(en.dailyStorageRateEgpFieldLabel, isNotEmpty);
      expect(ar.savePolicyBtn, isNotEmpty);
      expect(en.savePolicyBtn, isNotEmpty);
      expect(ar.policyCreatedSuccessSnack, isNotEmpty);
      expect(en.policyCreatedSuccessSnack, isNotEmpty);
      expect(ar.genericErrorSnack, isNotEmpty);
      expect(en.genericErrorSnack, isNotEmpty);
      expect(ar.requiredFieldValidation, isNotEmpty);
      expect(en.requiredFieldValidation, isNotEmpty);
      expect(ar.localizedDemurrageStatus('Free Time Active'), isNotEmpty);
      expect(en.localizedDemurrageStatus('Free Time Active'), equals('Free Time Active'));
    });

    test('Arabic static strings should not contain English or Latin characters', () {
      final latinPattern = RegExp(r'[a-zA-Z]');
      expect(latinPattern.hasMatch(ar.demurrageScreenTitle), isFalse);
      expect(latinPattern.hasMatch(ar.containerTrackingsTab), isFalse);
      expect(latinPattern.hasMatch(ar.simulatorAndTierCalcTab), isFalse);
      expect(latinPattern.hasMatch(ar.carrierTariffPoliciesTab), isFalse);
      expect(latinPattern.hasMatch(ar.totalActiveTrackingsMetric), isFalse);
      expect(latinPattern.hasMatch(ar.incurredDemurrageShipmentsMetric), isFalse);
      expect(latinPattern.hasMatch(ar.totalCalculatedDemurrageMetric), isFalse);
      expect(latinPattern.hasMatch(ar.searchDemurrageHint), isFalse);
      expect(latinPattern.hasMatch(ar.statusFilterLabel), isFalse);
      expect(latinPattern.hasMatch(ar.allStatusesOption), isFalse);
      expect(latinPattern.hasMatch(ar.statusFreeTimeActive), isFalse);
      expect(latinPattern.hasMatch(ar.statusDemurrageIncurred), isFalse);
      expect(latinPattern.hasMatch(ar.statusDetentionIncurred), isFalse);
      expect(latinPattern.hasMatch(ar.statusPushedToSettlement), isFalse);
      expect(latinPattern.hasMatch(ar.startNewTrackingBtn), isFalse);
      expect(latinPattern.hasMatch(ar.noTrackingsFound), isFalse);
      expect(latinPattern.hasMatch(ar.dischargeDateLabel), isFalse);
      expect(latinPattern.hasMatch(ar.gateOutDateLabel), isFalse);
      expect(latinPattern.hasMatch(ar.notGatedOutYet), isFalse);
      expect(latinPattern.hasMatch(ar.emptyReturnDateLabel), isFalse);
      expect(latinPattern.hasMatch(ar.notReturnedYet), isFalse);
      expect(latinPattern.hasMatch(ar.containersCountLabel), isFalse);
      expect(latinPattern.hasMatch(ar.totalEstimatedCostLabel), isFalse);
      expect(latinPattern.hasMatch(ar.updateGateOutAndReturnDatesBtn), isFalse);
      expect(latinPattern.hasMatch(ar.pushToFinancialSettlementBtn), isFalse);
      expect(latinPattern.hasMatch(ar.alreadyPushedToSettlementBtn), isFalse);
      expect(latinPattern.hasMatch(ar.calculationSettingsTitle), isFalse);
      expect(latinPattern.hasMatch(ar.shippingLineFieldLabel), isFalse);
      expect(latinPattern.hasMatch(ar.containerTypeFieldLabel), isFalse);
      expect(latinPattern.hasMatch(ar.containersCountFieldLabel), isFalse);
      expect(latinPattern.hasMatch(ar.exchangeRateFieldLabel), isFalse);
      expect(latinPattern.hasMatch(ar.grantedFreeDaysHeader), isFalse);
      expect(latinPattern.hasMatch(ar.portDemurrageFreeDaysLabel), isFalse);
      expect(latinPattern.hasMatch(ar.emptyReturnFreeDaysLabel), isFalse);
      expect(latinPattern.hasMatch(ar.operationalMilestonesHeader), isFalse);
      expect(latinPattern.hasMatch(ar.vesselDischargeDateMilestone), isFalse);
      expect(latinPattern.hasMatch(ar.portGateOutDateMilestone), isFalse);
      expect(latinPattern.hasMatch(ar.notGatedOutCalculatedToday), isFalse);
      expect(latinPattern.hasMatch(ar.emptyReturnToDepotMilestone), isFalse);
      expect(latinPattern.hasMatch(ar.recalculateDemurrageNowBtn), isFalse);
      expect(latinPattern.hasMatch(ar.initializingSimulationResults), isFalse);
      expect(latinPattern.hasMatch(ar.totalDemurrageCostSummaryTitle), isFalse);
      expect(latinPattern.hasMatch(ar.demurrageFeeMetric), isFalse);
      expect(latinPattern.hasMatch(ar.detentionFeeMetric), isFalse);
      expect(latinPattern.hasMatch(ar.portStorageFeeMetric), isFalse);
      expect(latinPattern.hasMatch(ar.totalDueComprehensiveCost), isFalse);
      expect(latinPattern.hasMatch(ar.tieredBreakdownTitle), isFalse);
      expect(latinPattern.hasMatch(ar.colCategory), isFalse);
      expect(latinPattern.hasMatch(ar.colConsumedDays), isFalse);
      expect(latinPattern.hasMatch(ar.colFreeDays), isFalse);
      expect(latinPattern.hasMatch(ar.colOverdueDays), isFalse);
      expect(latinPattern.hasMatch(ar.colFeeAmount), isFalse);
      expect(latinPattern.hasMatch(ar.carrierTariffPoliciesTitle), isFalse);
      expect(latinPattern.hasMatch(ar.carrierTariffPoliciesSubtitle), isFalse);
      expect(latinPattern.hasMatch(ar.addCarrierPolicyBtn), isFalse);
      expect(latinPattern.hasMatch(ar.noCarrierPoliciesFound), isFalse);
      expect(latinPattern.hasMatch(ar.demurrageFreeLabel), isFalse);
      expect(latinPattern.hasMatch(ar.detentionFreeLabel), isFalse);
      expect(latinPattern.hasMatch(ar.portStorageFreeLabel), isFalse);
      expect(latinPattern.hasMatch(ar.dailyStorageRateLabel), isFalse);
      expect(latinPattern.hasMatch(ar.addTrackingDialogTitle), isFalse);
      expect(latinPattern.hasMatch(ar.arrivalPortFieldLabel), isFalse);
      expect(latinPattern.hasMatch(ar.blNumberFieldLabel), isFalse);
      expect(latinPattern.hasMatch(ar.containerNumberFieldLabel), isFalse);
      expect(latinPattern.hasMatch(ar.portDischargeDateTile), isFalse);
      expect(latinPattern.hasMatch(ar.saveAndStartTrackingBtn), isFalse);
      expect(latinPattern.hasMatch(ar.trackingCreatedSuccessSnack), isFalse);
      expect(latinPattern.hasMatch(ar.saveTrackingErrorSnack), isFalse);
      expect(latinPattern.hasMatch(ar.gateOutDateTile), isFalse);
      expect(latinPattern.hasMatch(ar.emptyReturnDateTile), isFalse);
      expect(latinPattern.hasMatch(ar.notRecordedOption), isFalse);
      expect(latinPattern.hasMatch(ar.saveAndRecalculateBtn), isFalse);
      expect(latinPattern.hasMatch(ar.datesUpdatedAndRecalculatedSuccessSnack), isFalse);
      expect(latinPattern.hasMatch(ar.datesUpdateErrorSnack), isFalse);
      expect(latinPattern.hasMatch(ar.pushedToSettlementSuccessSnack), isFalse);
      expect(latinPattern.hasMatch(ar.pushToSettlementErrorSnack), isFalse);
      expect(latinPattern.hasMatch(ar.addPolicyDialogTitle), isFalse);
      expect(latinPattern.hasMatch(ar.demurrageFreeDaysFieldLabel), isFalse);
      expect(latinPattern.hasMatch(ar.detentionFreeDaysFieldLabel), isFalse);
      expect(latinPattern.hasMatch(ar.portStorageFreeDaysFieldLabel), isFalse);
      expect(latinPattern.hasMatch(ar.dailyStorageRateEgpFieldLabel), isFalse);
      expect(latinPattern.hasMatch(ar.savePolicyBtn), isFalse);
      expect(latinPattern.hasMatch(ar.policyCreatedSuccessSnack), isFalse);
      expect(latinPattern.hasMatch(ar.genericErrorSnack), isFalse);
      expect(latinPattern.hasMatch(ar.requiredFieldValidation), isFalse);
    });
  });
}
