import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/core/localization/app_localizations_ar.dart';
import 'package:frontend/core/localization/app_localizations_en.dart';

void main() {
  group('Screen 60: Customs Clearance - Drawing Samples & Shortage Localization Tests', () {
    final ar = AppLocalizationsAr();
    final en = AppLocalizationsEn();

    test('All Screen 60 getters return non-empty strings in AR and EN', () {
      final gettersAr = [
        ar.drawingSamplesScreenTitle,
        ar.drawingSamplesScreenSubtitle,
        ar.drawingSamplesTabDrawnSamples,
        ar.drawingSamplesTabShortageReconciliation,
        ar.drawingSamplesKpiTotalSamples,
        ar.drawingSamplesKpiPassedSamples,
        ar.drawingSamplesKpiPendingSamples,
        ar.drawingSamplesKpiShortageCount,
        ar.drawingSamplesExportTsvBtn,
        ar.drawingSamplesExportExcelBtn,
        ar.drawingSamplesPrintPdfBtn,
        ar.drawingSamplesCopyDossierBtn,
        ar.drawingSamplesCopiedDossierSuccess,
        ar.drawingSamplesCopiedTsvSuccess,
        ar.drawingSamplesCopiedExcelSuccess,
        ar.drawingSamplesCopyRowSummaryBtn,
        ar.drawingSamplesCopyRowSummarySuccess,
        ar.drawingSamplesCopyFieldTooltip,
        ar.drawingSamplesSearchHint,
        ar.drawingSamplesFilterAll,
        ar.drawingSamplesFilterPassed,
        ar.drawingSamplesFilterPending,
        ar.drawingSamplesEmptySamples,
        ar.drawingSamplesEmptyShortage,
        ar.drawingSamplesShortageSectionTitle,
        ar.drawingSamplesShortageSectionDesc,
        ar.drawingSamplesAddShortageBtn,
        ar.drawingSamplesAddShortageDialogTitle,
        ar.drawingSamplesSummaryHeader,
        ar.drawingSamplesColSampleCode,
        ar.drawingSamplesColShortageCode,
        ar.drawingSamplesColContainerPkg,
        ar.drawingSamplesColItemDesc,
        ar.drawingSamplesColManifestQty,
        ar.drawingSamplesColLandedQty,
        ar.drawingSamplesColShortageQty,
        ar.drawingSamplesColShortagePct,
        ar.drawingSamplesColShortageAction,
        ar.drawingSamplesColShortageNotes,
        ar.drawingSamplesShortageActionDeductDuty,
        ar.drawingSamplesShortageActionCarrierClaim,
        ar.drawingSamplesShortageActionSurveyEndorsement,
        ar.drawingSamplesShortageSaveSuccess,
        ar.drawingSamplesFieldSampleId,
        ar.drawingSamplesFieldAuthority,
        ar.drawingSamplesFieldReceiptNo,
        ar.drawingSamplesFieldDrawingDate,
        ar.drawingSamplesFieldTestType,
        ar.drawingSamplesFieldDeclarationNo,
        ar.drawingSamplesFieldStatus,
        ar.drawingSamplesFieldNotes,
        ar.drawingSamplesFieldContainerNo,
        ar.drawingSamplesFieldItemDesc,
        ar.drawingSamplesFieldManifestQty,
        ar.drawingSamplesFieldLandedQty,
        ar.drawingSamplesValidationRequired,
        ar.drawingSamplesValidationPositiveNumber,
        ar.drawingSamplesValidationLandedExceeds,
        ar.customsClearanceSamplesBannerTitle,
        ar.customsClearanceSamplesBannerDesc,
        ar.customsClearanceColAuthority,
        ar.customsClearanceSampleAuthLabel,
      ];

      final gettersEn = [
        en.drawingSamplesScreenTitle,
        en.drawingSamplesScreenSubtitle,
        en.drawingSamplesTabDrawnSamples,
        en.drawingSamplesTabShortageReconciliation,
        en.drawingSamplesKpiTotalSamples,
        en.drawingSamplesKpiPassedSamples,
        en.drawingSamplesKpiPendingSamples,
        en.drawingSamplesKpiShortageCount,
        en.drawingSamplesExportTsvBtn,
        en.drawingSamplesExportExcelBtn,
        en.drawingSamplesPrintPdfBtn,
        en.drawingSamplesCopyDossierBtn,
        en.drawingSamplesCopiedDossierSuccess,
        en.drawingSamplesCopiedTsvSuccess,
        en.drawingSamplesCopiedExcelSuccess,
        en.drawingSamplesCopyRowSummaryBtn,
        en.drawingSamplesCopyRowSummarySuccess,
        en.drawingSamplesCopyFieldTooltip,
        en.drawingSamplesSearchHint,
        en.drawingSamplesFilterAll,
        en.drawingSamplesFilterPassed,
        en.drawingSamplesFilterPending,
        en.drawingSamplesEmptySamples,
        en.drawingSamplesEmptyShortage,
        en.drawingSamplesShortageSectionTitle,
        en.drawingSamplesShortageSectionDesc,
        en.drawingSamplesAddShortageBtn,
        en.drawingSamplesAddShortageDialogTitle,
        en.drawingSamplesSummaryHeader,
        en.drawingSamplesColSampleCode,
        en.drawingSamplesColShortageCode,
        en.drawingSamplesColContainerPkg,
        en.drawingSamplesColItemDesc,
        en.drawingSamplesColManifestQty,
        en.drawingSamplesColLandedQty,
        en.drawingSamplesColShortageQty,
        en.drawingSamplesColShortagePct,
        en.drawingSamplesColShortageAction,
        en.drawingSamplesColShortageNotes,
        en.drawingSamplesShortageActionDeductDuty,
        en.drawingSamplesShortageActionCarrierClaim,
        en.drawingSamplesShortageActionSurveyEndorsement,
        en.drawingSamplesShortageSaveSuccess,
        en.drawingSamplesFieldSampleId,
        en.drawingSamplesFieldAuthority,
        en.drawingSamplesFieldReceiptNo,
        en.drawingSamplesFieldDrawingDate,
        en.drawingSamplesFieldTestType,
        en.drawingSamplesFieldDeclarationNo,
        en.drawingSamplesFieldStatus,
        en.drawingSamplesFieldNotes,
        en.drawingSamplesFieldContainerNo,
        en.drawingSamplesFieldItemDesc,
        en.drawingSamplesFieldManifestQty,
        en.drawingSamplesFieldLandedQty,
        en.drawingSamplesValidationRequired,
        en.drawingSamplesValidationPositiveNumber,
        en.drawingSamplesValidationLandedExceeds,
        en.customsClearanceSamplesBannerTitle,
        en.customsClearanceSamplesBannerDesc,
        en.customsClearanceColAuthority,
        en.customsClearanceSampleAuthLabel,
      ];

      for (final s in gettersAr) {
        expect(s.trim().isNotEmpty, isTrue);
      }
      for (final s in gettersEn) {
        expect(s.trim().isNotEmpty, isTrue);
      }
    });

    test('All Screen 60 Arabic strings are pure Arabic with 0 Latin characters [a-zA-Z]', () {
      final latinRegex = RegExp(r'[a-zA-Z]');
      final gettersAr = [
        ar.drawingSamplesScreenTitle,
        ar.drawingSamplesScreenSubtitle,
        ar.drawingSamplesTabDrawnSamples,
        ar.drawingSamplesTabShortageReconciliation,
        ar.drawingSamplesKpiTotalSamples,
        ar.drawingSamplesKpiPassedSamples,
        ar.drawingSamplesKpiPendingSamples,
        ar.drawingSamplesKpiShortageCount,
        ar.drawingSamplesExportTsvBtn,
        ar.drawingSamplesExportExcelBtn,
        ar.drawingSamplesPrintPdfBtn,
        ar.drawingSamplesCopyDossierBtn,
        ar.drawingSamplesCopiedDossierSuccess,
        ar.drawingSamplesCopiedTsvSuccess,
        ar.drawingSamplesCopiedExcelSuccess,
        ar.drawingSamplesCopyRowSummaryBtn,
        ar.drawingSamplesCopyRowSummarySuccess,
        ar.drawingSamplesCopyFieldTooltip,
        ar.drawingSamplesSearchHint,
        ar.drawingSamplesFilterAll,
        ar.drawingSamplesFilterPassed,
        ar.drawingSamplesFilterPending,
        ar.drawingSamplesEmptySamples,
        ar.drawingSamplesEmptyShortage,
        ar.drawingSamplesShortageSectionTitle,
        ar.drawingSamplesShortageSectionDesc,
        ar.drawingSamplesAddShortageBtn,
        ar.drawingSamplesAddShortageDialogTitle,
        ar.drawingSamplesSummaryHeader,
        ar.drawingSamplesColSampleCode,
        ar.drawingSamplesColShortageCode,
        ar.drawingSamplesColContainerPkg,
        ar.drawingSamplesColItemDesc,
        ar.drawingSamplesColManifestQty,
        ar.drawingSamplesColLandedQty,
        ar.drawingSamplesColShortageQty,
        ar.drawingSamplesColShortagePct,
        ar.drawingSamplesColShortageAction,
        ar.drawingSamplesColShortageNotes,
        ar.drawingSamplesShortageActionDeductDuty,
        ar.drawingSamplesShortageActionCarrierClaim,
        ar.drawingSamplesShortageActionSurveyEndorsement,
        ar.drawingSamplesShortageSaveSuccess,
        ar.drawingSamplesFieldSampleId,
        ar.drawingSamplesFieldAuthority,
        ar.drawingSamplesFieldReceiptNo,
        ar.drawingSamplesFieldDrawingDate,
        ar.drawingSamplesFieldTestType,
        ar.drawingSamplesFieldDeclarationNo,
        ar.drawingSamplesFieldStatus,
        ar.drawingSamplesFieldNotes,
        ar.drawingSamplesFieldContainerNo,
        ar.drawingSamplesFieldItemDesc,
        ar.drawingSamplesFieldManifestQty,
        ar.drawingSamplesFieldLandedQty,
        ar.drawingSamplesValidationRequired,
        ar.drawingSamplesValidationPositiveNumber,
        ar.drawingSamplesValidationLandedExceeds,
        ar.customsClearanceSamplesBannerTitle,
        ar.customsClearanceSamplesBannerDesc,
        ar.customsClearanceColAuthority,
        ar.customsClearanceSampleAuthLabel,
        ar.customsClearanceExportTsvBtn,
      ];

      for (final s in gettersAr) {
        final matches = latinRegex.allMatches(s).map((m) => m.group(0)).toList();
        expect(matches, isEmpty, reason: 'String "$s" contains Latin characters: $matches');
      }
    });

    test('Screen 60 Arabic strings contain no bilingual slashes', () {
      final slashRegex = RegExp(r'\s*/\s*');
      final checkedStrings = [
        ar.drawingSamplesTabDrawnSamples,
        ar.drawingSamplesTabShortageReconciliation,
        ar.drawingSamplesShortageSectionTitle,
        ar.customsClearanceColAuthority,
        ar.customsClearanceSampleAuthLabel,
        ar.drawingSamplesColContainerPkg,
        ar.drawingSamplesColItemDesc,
        ar.drawingSamplesFieldAuthority,
        ar.drawingSamplesFieldContainerNo,
      ];

      for (final s in checkedStrings) {
        expect(slashRegex.hasMatch(s), isFalse, reason: 'String "$s" contains bilingual slashes');
      }
    });
  });
}
