import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/core/localization/app_localizations.dart';
import 'package:frontend/core/localization/app_localizations_ar.dart';
import 'package:frontend/core/localization/app_localizations_en.dart';

void main() {
  group('Screen 30: Import File Closure & Archival Localization Tests', () {
    const AppLocalizations ar = AppLocalizationsAr();
    const AppLocalizations en = AppLocalizationsEn();

    test('All Screen 30 getters should have non-empty Arabic and English translations', () {
      final List<String> arStrings = [
        ar.fileClosureStageTitle,
        ar.fileClosureTabArchivedRegistry,
        ar.fileClosureTabCloseFile,
        ar.fileClosureRefreshTooltip,
        ar.fileClosureNewCertificateBtn,
        ar.fileClosureSearchHint,
        ar.fileClosureFetchError,
        ar.fileClosureEmptyRecords,
        ar.fileClosureClosedFilesBannerTitle(3),
        ar.fileClosureClosedBadge,
        ar.fileClosureStopReason('Cancelled'),
        ar.fileClosureReopenBtn,
        ar.fileClosureFileRefLabel(10),
        ar.fileClosureVaultLabel('Vault-1'),
        ar.fileClosureStatusBadgeClosed,
        ar.fileClosureChecklistHeader,
        ar.fileClosureChecklistDocsOriginals,
        ar.fileClosureChecklistCustomsCleared,
        ar.fileClosureChecklistWarehouseGrn,
        ar.fileClosureChecklistLandedCost,
        ar.fileClosureChecklistTasksClosed,
        ar.fileClosureArchivalNotes('All clear'),
        ar.fileClosureAuditorLabel('Auditor A'),
        ar.fileClosureCertificateDialogTitle('CLR-2026-001'),
        ar.fileClosureCertFileNo(10),
        ar.fileClosureCertLocation('Vault-1'),
        ar.fileClosureCertAuditor('Auditor A'),
        ar.fileClosureCertClosedDate('2026-08-24'),
        ar.fileClosureCertNotes('Archived permanently'),
        ar.fileClosureEditSnack('CLR-2026-001'),
        ar.fileClosurePrintSnack('CLR-2026-001', 10),
        ar.fileClosureDeleteTitle,
        ar.fileClosureDeleteMessage,
        ar.fileClosureViewTooltip,
        ar.fileClosureEditTooltip,
        ar.fileClosurePrintTooltip,
        ar.fileClosureDeleteTooltip,
        ar.fileClosureDialogTitle,
        ar.fileClosureSelectImportFile,
        ar.fileClosureSelectImportFileHint,
        ar.fileClosureSelectImportFileValidator,
        ar.fileClosureMandatoryChecklistHeader,
        ar.fileClosureCheck1Docs,
        ar.fileClosureCheck2Customs,
        ar.fileClosureCheck3Warehouse,
        ar.fileClosureCheck4LandedCost,
        ar.fileClosureCheck5Tasks,
        ar.fileClosureAuditorNameLabel,
        ar.fileClosureAuditorNameValidator,
        ar.fileClosureVaultLocationLabel,
        ar.fileClosureArchivalNotesLabel,
        ar.fileClosureLiveReloadBtn,
        ar.fileClosureResetFormBtn,
        ar.fileClosureCertifySubmitBtn,
        ar.fileClosureChecklistIncompleteWarning,
        ar.fileClosureSaveError('Server timeout'),
        ar.reopenShipmentDialogTitle('IMP-2026-001'),
        ar.reopenShipmentRestoredPhase('Phase 1'),
        ar.reopenShipmentNotice,
        ar.reopenShipmentReasonLabel,
        ar.reopenShipmentReasonHint,
        ar.reopenShipmentReasonValidatorEmpty,
        ar.reopenShipmentReasonValidatorMin,
        ar.reopenShipmentSuccessSnack('IMP-2026-001', 'Phase 1'),
        ar.reopenShipmentErrorSnack('DB Error'),
        ar.reopenShipmentConfirmBtn,
      ];

      final List<String> enStrings = [
        en.fileClosureStageTitle,
        en.fileClosureTabArchivedRegistry,
        en.fileClosureTabCloseFile,
        en.fileClosureRefreshTooltip,
        en.fileClosureNewCertificateBtn,
        en.fileClosureSearchHint,
        en.fileClosureFetchError,
        en.fileClosureEmptyRecords,
        en.fileClosureClosedFilesBannerTitle(3),
        en.fileClosureClosedBadge,
        en.fileClosureStopReason('Cancelled'),
        en.fileClosureReopenBtn,
        en.fileClosureFileRefLabel(10),
        en.fileClosureVaultLabel('Vault-1'),
        en.fileClosureStatusBadgeClosed,
        en.fileClosureChecklistHeader,
        en.fileClosureChecklistDocsOriginals,
        en.fileClosureChecklistCustomsCleared,
        en.fileClosureChecklistWarehouseGrn,
        en.fileClosureChecklistLandedCost,
        en.fileClosureChecklistTasksClosed,
        en.fileClosureArchivalNotes('All clear'),
        en.fileClosureAuditorLabel('Auditor A'),
        en.fileClosureCertificateDialogTitle('CLR-2026-001'),
        en.fileClosureCertFileNo(10),
        en.fileClosureCertLocation('Vault-1'),
        en.fileClosureCertAuditor('Auditor A'),
        en.fileClosureCertClosedDate('2026-08-24'),
        en.fileClosureCertNotes('Archived permanently'),
        en.fileClosureEditSnack('CLR-2026-001'),
        en.fileClosurePrintSnack('CLR-2026-001', 10),
        en.fileClosureDeleteTitle,
        en.fileClosureDeleteMessage,
        en.fileClosureViewTooltip,
        en.fileClosureEditTooltip,
        en.fileClosurePrintTooltip,
        en.fileClosureDeleteTooltip,
        en.fileClosureDialogTitle,
        en.fileClosureSelectImportFile,
        en.fileClosureSelectImportFileHint,
        en.fileClosureSelectImportFileValidator,
        en.fileClosureMandatoryChecklistHeader,
        en.fileClosureCheck1Docs,
        en.fileClosureCheck2Customs,
        en.fileClosureCheck3Warehouse,
        en.fileClosureCheck4LandedCost,
        en.fileClosureCheck5Tasks,
        en.fileClosureAuditorNameLabel,
        en.fileClosureAuditorNameValidator,
        en.fileClosureVaultLocationLabel,
        en.fileClosureArchivalNotesLabel,
        en.fileClosureLiveReloadBtn,
        en.fileClosureResetFormBtn,
        en.fileClosureCertifySubmitBtn,
        en.fileClosureChecklistIncompleteWarning,
        en.fileClosureSaveError('Server timeout'),
        en.reopenShipmentDialogTitle('IMP-2026-001'),
        en.reopenShipmentRestoredPhase('Phase 1'),
        en.reopenShipmentNotice,
        en.reopenShipmentReasonLabel,
        en.reopenShipmentReasonHint,
        en.reopenShipmentReasonValidatorEmpty,
        en.reopenShipmentReasonValidatorMin,
        en.reopenShipmentSuccessSnack('IMP-2026-001', 'Phase 1'),
        en.reopenShipmentErrorSnack('DB Error'),
        en.reopenShipmentConfirmBtn,
      ];

      expect(arStrings.length, enStrings.length);
      for (int i = 0; i < arStrings.length; i++) {
        expect(arStrings[i].trim().isNotEmpty, isTrue, reason: 'Arabic string at index $i is empty');
        expect(enStrings[i].trim().isNotEmpty, isTrue, reason: 'English string at index $i is empty');
      }
    });

    test('Verify pure Arabic translations without stacked or Latin characters in static keys', () {
      final List<String> arStaticStrings = [
        ar.fileClosureStageTitle,
        ar.fileClosureTabArchivedRegistry,
        ar.fileClosureTabCloseFile,
        ar.fileClosureRefreshTooltip,
        ar.fileClosureNewCertificateBtn,
        ar.fileClosureEmptyRecords,
        ar.fileClosureClosedBadge,
        ar.fileClosureReopenBtn,
        ar.fileClosureStatusBadgeClosed,
        ar.fileClosureChecklistHeader,
        ar.fileClosureChecklistDocsOriginals,
        ar.fileClosureChecklistCustomsCleared,
        ar.fileClosureChecklistWarehouseGrn,
        ar.fileClosureChecklistLandedCost,
        ar.fileClosureChecklistTasksClosed,
        ar.fileClosureDeleteTitle,
        ar.fileClosureDeleteMessage,
        ar.fileClosureDialogTitle,
        ar.fileClosureSelectImportFile,
        ar.fileClosureSelectImportFileValidator,
        ar.fileClosureMandatoryChecklistHeader,
        ar.fileClosureCheck3Warehouse,
        ar.fileClosureCheck4LandedCost,
        ar.fileClosureCheck5Tasks,
        ar.fileClosureAuditorNameLabel,
        ar.fileClosureAuditorNameValidator,
        ar.fileClosureVaultLocationLabel,
        ar.fileClosureArchivalNotesLabel,
        ar.fileClosureCertifySubmitBtn,
        ar.fileClosureChecklistIncompleteWarning,
        ar.reopenShipmentNotice,
        ar.reopenShipmentReasonLabel,
        ar.reopenShipmentReasonValidatorEmpty,
        ar.reopenShipmentReasonValidatorMin,
        ar.reopenShipmentConfirmBtn,
      ];

      for (final s in arStaticStrings) {
        expect(RegExp(r'[a-zA-Z]').hasMatch(s), isFalse, reason: 'Arabic string contains Latin characters: $s');
      }
    });
  });
}
