import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/core/localization/app_localizations.dart';
import 'package:frontend/core/localization/app_localizations_ar.dart';
import 'package:frontend/core/localization/app_localizations_en.dart';

void main() {
  group('Screen 29: Landed Cost Settlement Localization Tests', () {
    const AppLocalizations ar = AppLocalizationsAr();
    const AppLocalizations en = AppLocalizationsEn();

    test('All Screen 29 getters should have non-empty Arabic and English translations', () {
      final List<String> arStrings = [
        ar.financialSettlementStageTitle,
        ar.financialSettlementTabRegistry,
        ar.financialSettlementTabNewEntry,
        ar.financialSettlementRefreshTooltip,
        ar.financialSettlementNewSettlementBtn,
        ar.financialSettlementSearchHint,
        ar.financialSettlementFetchError,
        ar.financialSettlementEmptyRecords,
        ar.financialSettlementAccountantLabel('Kamal'),
        ar.financialSettlementStatusDraft,
        ar.financialSettlementStatusCalculated,
        ar.financialSettlementStatusApproved,
        ar.financialSettlementMetricFobTotal,
        ar.financialSettlementMetricExpensesTotal,
        ar.financialSettlementMetricLandedCostTotal,
        ar.financialSettlementMetricMarkupFactor,
        ar.financialSettlementExpensesSectionHeader,
        ar.financialSettlementColInvoiceNo,
        ar.financialSettlementColCategory,
        ar.financialSettlementColProvider,
        ar.financialSettlementColAmountFx,
        ar.financialSettlementColExchangeRate,
        ar.financialSettlementColAmountEgp,
        ar.financialSettlementColAllocationRule,
        ar.financialSettlementCategoryFreight,
        ar.financialSettlementCategoryCustomsDuty,
        ar.financialSettlementCategoryBrokerage,
        ar.financialSettlementCategoryLocalTransport,
        ar.financialSettlementCategoryStorage,
        ar.financialSettlementRuleVolumeBased,
        ar.financialSettlementRuleValueBased,
        ar.financialSettlementRuleWeightBased,
        ar.financialSettlementRuleEqual,
        ar.financialSettlementItemsSectionHeader,
        ar.financialSettlementColItemCode,
        ar.financialSettlementColItemName,
        ar.financialSettlementColQty,
        ar.financialSettlementColFobUnit,
        ar.financialSettlementColAllocatedFreight,
        ar.financialSettlementColAllocatedCustoms,
        ar.financialSettlementColAllocatedClearance,
        ar.financialSettlementColAllocatedTransport,
        ar.financialSettlementColUnitLandedCost,
        ar.financialSettlementColMarkupFactor,
        ar.financialSettlementExportOdooBtn,
        ar.financialSettlementRecalculateBtn,
        ar.financialSettlementRecalculateSuccessSnack('LCS-2026-001'),
        ar.financialSettlementPrintSnack('LCS-2026-001', '150,000.00'),
        ar.financialSettlementViewTooltip,
        ar.financialSettlementEditTooltip,
        ar.financialSettlementPrintTooltip,
        ar.financialSettlementDeleteTooltip,
        ar.financialSettlementDeleteTitle,
        ar.financialSettlementDeleteMessage,
        ar.financialSettlementDialogTitle,
        ar.financialSettlementImportFileLabel,
        ar.financialSettlementImportFileSearchHint,
        ar.financialSettlementImportFileValidator,
        ar.financialSettlementExpenseSectionHeader,
        ar.financialSettlementInvoiceNoLabel,
        ar.financialSettlementCategoryLabel,
        ar.financialSettlementCategorySearchHint,
        ar.financialSettlementProviderNameLabel,
        ar.financialSettlementAmountFxLabel,
        ar.financialSettlementExchangeRateLabel,
        ar.financialSettlementAllocationRuleLabel,
        ar.financialSettlementAllocationRuleSearchHint,
        ar.financialSettlementItemSectionHeader,
        ar.financialSettlementItemCodeLabel,
        ar.financialSettlementItemNameLabel,
        ar.financialSettlementQtyReceivedLabel,
        ar.financialSettlementFobUnitPriceLabel,
        ar.financialSettlementLiveReloadBtn,
        ar.financialSettlementResetFormBtn,
        ar.financialSettlementSaveAndAllocateBtn,
        ar.financialSettlementSaveError('Timeout'),
        ar.odooJournalLoading,
        ar.odooJournalFetchError('Connection refused'),
        ar.odooJournalTitle('LCS-2026-001'),
        ar.odooJournalSubtitle('IMP-2026-001', 'REF-001'),
        ar.odooJournalBalanced,
        ar.odooJournalUnbalanced('500.00'),
        ar.odooJournalMetaImporter,
        ar.odooJournalMetaSupplier,
        ar.odooJournalMetaProject,
        ar.odooJournalMetaDate,
        ar.odooJournalMetaTotalDebitCredit,
        ar.odooJournalLinesSectionHeader,
        ar.odooJournalColAccountCode,
        ar.odooJournalColAccountName,
        ar.odooJournalColPartner,
        ar.odooJournalColLabel,
        ar.odooJournalColDebit,
        ar.odooJournalColCredit,
        ar.odooJournalColForeignCurrency,
        ar.odooJournalColCostCategory,
        ar.odooJournalExportCsvBtn,
        ar.odooJournalExportExcelBtn,
        ar.odooJournalExportingSnack('odoo.csv', 'http://127.0.0.1:28080/export'),
      ];

      final List<String> enStrings = [
        en.financialSettlementStageTitle,
        en.financialSettlementTabRegistry,
        en.financialSettlementTabNewEntry,
        en.financialSettlementRefreshTooltip,
        en.financialSettlementNewSettlementBtn,
        en.financialSettlementSearchHint,
        en.financialSettlementFetchError,
        en.financialSettlementEmptyRecords,
        en.financialSettlementAccountantLabel('Kamal'),
        en.financialSettlementStatusDraft,
        en.financialSettlementStatusCalculated,
        en.financialSettlementStatusApproved,
        en.financialSettlementMetricFobTotal,
        en.financialSettlementMetricExpensesTotal,
        en.financialSettlementMetricLandedCostTotal,
        en.financialSettlementMetricMarkupFactor,
        en.financialSettlementExpensesSectionHeader,
        en.financialSettlementColInvoiceNo,
        en.financialSettlementColCategory,
        en.financialSettlementColProvider,
        en.financialSettlementColAmountFx,
        en.financialSettlementColExchangeRate,
        en.financialSettlementColAmountEgp,
        en.financialSettlementColAllocationRule,
        en.financialSettlementCategoryFreight,
        en.financialSettlementCategoryCustomsDuty,
        en.financialSettlementCategoryBrokerage,
        en.financialSettlementCategoryLocalTransport,
        en.financialSettlementCategoryStorage,
        en.financialSettlementRuleVolumeBased,
        en.financialSettlementRuleValueBased,
        en.financialSettlementRuleWeightBased,
        en.financialSettlementRuleEqual,
        en.financialSettlementItemsSectionHeader,
        en.financialSettlementColItemCode,
        en.financialSettlementColItemName,
        en.financialSettlementColQty,
        en.financialSettlementColFobUnit,
        en.financialSettlementColAllocatedFreight,
        en.financialSettlementColAllocatedCustoms,
        en.financialSettlementColAllocatedClearance,
        en.financialSettlementColAllocatedTransport,
        en.financialSettlementColUnitLandedCost,
        en.financialSettlementColMarkupFactor,
        en.financialSettlementExportOdooBtn,
        en.financialSettlementRecalculateBtn,
        en.financialSettlementRecalculateSuccessSnack('LCS-2026-001'),
        en.financialSettlementPrintSnack('LCS-2026-001', '150,000.00'),
        en.financialSettlementViewTooltip,
        en.financialSettlementEditTooltip,
        en.financialSettlementPrintTooltip,
        en.financialSettlementDeleteTooltip,
        en.financialSettlementDeleteTitle,
        en.financialSettlementDeleteMessage,
        en.financialSettlementDialogTitle,
        en.financialSettlementImportFileLabel,
        en.financialSettlementImportFileSearchHint,
        en.financialSettlementImportFileValidator,
        en.financialSettlementExpenseSectionHeader,
        en.financialSettlementInvoiceNoLabel,
        en.financialSettlementCategoryLabel,
        en.financialSettlementCategorySearchHint,
        en.financialSettlementProviderNameLabel,
        en.financialSettlementAmountFxLabel,
        en.financialSettlementExchangeRateLabel,
        en.financialSettlementAllocationRuleLabel,
        en.financialSettlementAllocationRuleSearchHint,
        en.financialSettlementItemSectionHeader,
        en.financialSettlementItemCodeLabel,
        en.financialSettlementItemNameLabel,
        en.financialSettlementQtyReceivedLabel,
        en.financialSettlementFobUnitPriceLabel,
        en.financialSettlementLiveReloadBtn,
        en.financialSettlementResetFormBtn,
        en.financialSettlementSaveAndAllocateBtn,
        en.financialSettlementSaveError('Timeout'),
        en.odooJournalLoading,
        en.odooJournalFetchError('Connection refused'),
        en.odooJournalTitle('LCS-2026-001'),
        en.odooJournalSubtitle('IMP-2026-001', 'REF-001'),
        en.odooJournalBalanced,
        en.odooJournalUnbalanced('500.00'),
        en.odooJournalMetaImporter,
        en.odooJournalMetaSupplier,
        en.odooJournalMetaProject,
        en.odooJournalMetaDate,
        en.odooJournalMetaTotalDebitCredit,
        en.odooJournalLinesSectionHeader,
        en.odooJournalColAccountCode,
        en.odooJournalColAccountName,
        en.odooJournalColPartner,
        en.odooJournalColLabel,
        en.odooJournalColDebit,
        en.odooJournalColCredit,
        en.odooJournalColForeignCurrency,
        en.odooJournalColCostCategory,
        en.odooJournalExportCsvBtn,
        en.odooJournalExportExcelBtn,
        en.odooJournalExportingSnack('odoo.csv', 'http://127.0.0.1:28080/export'),
      ];

      expect(arStrings.length, enStrings.length);
      for (int i = 0; i < arStrings.length; i++) {
        expect(arStrings[i].trim().isNotEmpty, isTrue, reason: 'Arabic string at index $i is empty');
        expect(enStrings[i].trim().isNotEmpty, isTrue, reason: 'English string at index $i is empty');
      }
    });

    test('Verify pure Arabic translations without unwanted English text', () {
      final List<String> arStrings = [
        ar.financialSettlementStageTitle,
        ar.financialSettlementTabRegistry,
        ar.financialSettlementTabNewEntry,
        ar.financialSettlementNewSettlementBtn,
        ar.financialSettlementStatusDraft,
        ar.financialSettlementStatusCalculated,
        ar.financialSettlementStatusApproved,
        ar.financialSettlementMetricExpensesTotal,
        ar.financialSettlementMetricLandedCostTotal,
        ar.financialSettlementCategoryFreight,
        ar.financialSettlementCategoryCustomsDuty,
        ar.financialSettlementCategoryBrokerage,
        ar.financialSettlementCategoryLocalTransport,
        ar.financialSettlementCategoryStorage,
        ar.financialSettlementRuleVolumeBased,
        ar.financialSettlementRuleValueBased,
        ar.financialSettlementRuleWeightBased,
        ar.financialSettlementRuleEqual,
        ar.financialSettlementColItemCode,
        ar.financialSettlementColItemName,
        ar.financialSettlementColQty,
        ar.financialSettlementColUnitLandedCost,
        ar.financialSettlementColMarkupFactor,
        ar.financialSettlementSaveAndAllocateBtn,
        ar.odooJournalBalanced,
        ar.odooJournalMetaImporter,
        ar.odooJournalMetaSupplier,
        ar.odooJournalMetaDate,
        ar.odooJournalColAccountCode,
        ar.odooJournalColAccountName,
        ar.odooJournalColPartner,
        ar.odooJournalColLabel,
        ar.odooJournalColDebit,
        ar.odooJournalColCredit,
      ];

      for (final s in arStrings) {
        expect(RegExp(r'[a-zA-Z]').hasMatch(s), isFalse, reason: 'Arabic string contains Latin characters: $s');
      }
    });
  });
}
