import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/core/localization/app_localizations.dart';
import 'package:frontend/core/localization/app_localizations_ar.dart';
import 'package:frontend/core/localization/app_localizations_en.dart';

void main() {
  group('Screen 25: Freight Booking & Carrier Allocation Localization Tests', () {
    const AppLocalizations ar = AppLocalizationsAr();
    const AppLocalizations en = AppLocalizationsEn();

    test('All Screen 25 getters should have non-empty Arabic and English translations', () {
      final List<String> arStrings = [
        ar.freightBookingStageTitle,
        ar.freightBookingTabRegistry,
        ar.freightBookingTabNewRequest,
        ar.freightBookingCreateButton,
        ar.freightBookingSearchHint,
        ar.freightBookingFilterStatusLabel,
        ar.freightBookingFilterStatusHint,
        ar.freightBookingStatusAll,
        ar.freightBookingStatusDraft,
        ar.freightBookingStatusRequested,
        ar.freightBookingStatusConfirmed,
        ar.freightBookingStatusSailed,
        ar.freightBookingEmptyRecords,
        ar.freightBookingColActions,
        ar.freightBookingColBookingCode,
        ar.freightBookingColImportFile,
        ar.freightBookingColConfirmationNo,
        ar.freightBookingColCarrierForwarder,
        ar.freightBookingColRoute,
        ar.freightBookingColVesselVoyage,
        ar.freightBookingColDeparture,
        ar.freightBookingColArrival,
        ar.freightBookingColContainers,
        ar.freightBookingColTotalFreight,
        ar.freightBookingColStatus,
        ar.freightBookingApprovedQuoteLabel('Maersk'),
        ar.freightBookingWhArrivalLabel('2026-09-01'),
        ar.freightBookingPendingDate,
        ar.freightBookingViewTooltip,
        ar.freightBookingEditTooltip,
        ar.freightBookingPrintTooltip,
        ar.freightBookingDeleteTooltip,
        ar.freightBookingDeleteConfirmTitle,
        ar.freightBookingDeleteConfirmMessage('BK-001'),
        ar.freightBookingNewDialogTitle,
        ar.freightBookingEditDialogTitle('BK-001'),
        ar.freightBookingCloseTooltip,
        ar.freightBookingTabBookingDetails,
        ar.freightBookingTabCostBreakdown,
        ar.freightBookingImportFileLabel,
        ar.freightBookingImportFileHint,
        ar.freightBookingConfirmNoInputLabel,
        ar.freightBookingConfirmNoValidator,
        ar.freightBookingEvaluatedQuotesHeader,
        ar.freightBookingAvailableQuotesBadge(3),
        ar.freightBookingNoEvaluatedQuotes,
        ar.freightBookingApplyQuoteInstruction,
        ar.freightBookingBestQuoteBadge,
        ar.freightBookingQuoteVesselDetails('CMA CGM', 'V-102', 'Shanghai', 'Alexandria'),
        ar.freightBookingQuoteScheduleDetails('2026-08-20', '2026-09-10', 14),
        ar.freightBookingQuoteStudyRef('SES-001', '2026-08-15'),
        ar.freightBookingSelectedQuoteBtn,
        ar.freightBookingApplyQuoteBtn,
        ar.freightBookingQuoteAppliedSuccess('Maersk', 'Vessel 1'),
        ar.freightBookingShippingLineLabel,
        ar.freightBookingShippingLineHint,
        ar.freightBookingForwarderLabel,
        ar.freightBookingForwarderHint,
        ar.freightBookingPolLabel,
        ar.freightBookingPolHint,
        ar.freightBookingPodLabel,
        ar.freightBookingPodHint,
        ar.freightBookingEtdLabel,
        ar.freightBookingEtaLabel,
        ar.freightBookingAtdLabel,
        ar.freightBookingDelayBannerDelayed(5),
        ar.freightBookingDelayBannerOnTime,
        ar.freightBookingExpectedWhArrival('2026-09-15'),
        ar.freightBookingFreeDaysInput,
        ar.freightBookingWarehouseDaysInput,
        ar.freightBookingStatusInputLabel,
        ar.freightBookingVesselNameInput,
        ar.freightBookingVoyageNoInput,
        ar.freightBookingReleaseOrderInput,
        ar.freightBookingContainerTypeInput,
        ar.freightBookingContainersQtyInput,
        ar.freightBookingEquipmentNote,
        ar.freightBookingCostBreakdownTitle,
        ar.freightBookingBaseCurrencyLabel('USD'),
        ar.freightBookingItemRateLabel,
        ar.freightBookingCurrencyLabel,
        ar.freightBookingQuantityLabel,
        ar.freightBookingCbmVolumeLabel,
        ar.freightBookingItemActive,
        ar.freightBookingItemInactive,
        ar.freightBookingItem40ft,
        ar.freightBookingItem20ft,
        ar.freightBookingItemLcl,
        ar.freightBookingItemCourier,
        ar.freightBookingItemEur1,
        ar.freightBookingItemVgm,
        ar.freightBookingItemVgmNotif,
        ar.freightBookingItemTelex,
        ar.freightBookingItemInsurance,
        ar.freightBookingItemCancellation,
        ar.freightBookingItemIcs2,
        ar.freightBookingItemOther,
        ar.freightBookingItemDocFees,
        ar.freightBookingItemWaiver,
        ar.freightBookingItemDthc,
        ar.freightBookingItemStorageWeek,
        ar.freightBookingItemStorageExtra,
        ar.freightBookingMismatchTitle,
        ar.freightBookingMismatchWarning('40HC x1', '20GP x1'),
        ar.freightBookingMismatchPrompt,
        ar.freightBookingMismatchNote,
        ar.freightBookingMismatchBtnNo,
        ar.freightBookingMismatchBtnYes,
        ar.freightBookingMismatchReasonTitle,
        ar.freightBookingMismatchReasonHint,
        ar.freightBookingMismatchReasonValidator,
        ar.freightBookingMismatchReasonConfirm,
        ar.freightBookingDuplicateTitle,
        ar.freightBookingDuplicateMessage,
        ar.freightBookingDuplicateRowFile,
        ar.freightBookingDuplicateRowCode,
        ar.freightBookingDuplicateRowConfirmNo,
        ar.freightBookingDuplicateRowLine,
        ar.freightBookingDuplicateRowStatus,
        ar.freightBookingDuplicateNotice,
        ar.freightBookingDuplicateBtnCancel,
        ar.freightBookingDuplicateBtnSwitch,
        ar.freightBookingBtnCloseDiscard,
        ar.freightBookingBtnLiveReload,
        ar.freightBookingBtnClearNew,
        ar.freightBookingBtnSaveDraft,
        ar.freightBookingBtnSaveConfirm,
        ar.freightBookingBtnUpdate,
        ar.freightBookingSaveSuccess,
        ar.freightBookingViewTitle('BK-001'),
        ar.freightBookingViewShippingLine,
        ar.freightBookingViewConfirmNo,
        ar.freightBookingViewRouteSection,
        ar.freightBookingViewPol,
        ar.freightBookingViewPod,
        ar.freightBookingViewVesselVoyage('Vessel A', '101'),
        ar.freightBookingViewTransitTime(25),
        ar.freightBookingViewEtd('2026-08-20'),
        ar.freightBookingViewEta('2026-09-15'),
        ar.freightBookingViewAtd('2026-08-22', '+2d'),
        ar.freightBookingViewExpectedWh('2026-09-20'),
        ar.freightBookingViewContainersSection,
        ar.freightBookingViewChargesSection,
        ar.freightBookingViewTotalFreight,
        ar.freightBookingPrintTitle('BK-001'),
        ar.freightBookingPrintManifestHeader('BK-001'),
        ar.freightBookingPrintDate('2026-08-24 10:00'),
        ar.freightBookingPrintContainersHeader,
        ar.freightBookingPrintChargesHeader,
        ar.freightBookingPrintGrandTotal('3500.00'),
        ar.freightBookingPrintNowBtn,
        ar.freightBookingPrintSuccess,
      ];

      final List<String> enStrings = [
        en.freightBookingStageTitle,
        en.freightBookingTabRegistry,
        en.freightBookingTabNewRequest,
        en.freightBookingCreateButton,
        en.freightBookingSearchHint,
        en.freightBookingFilterStatusLabel,
        en.freightBookingFilterStatusHint,
        en.freightBookingStatusAll,
        en.freightBookingStatusDraft,
        en.freightBookingStatusRequested,
        en.freightBookingStatusConfirmed,
        en.freightBookingStatusSailed,
        en.freightBookingEmptyRecords,
        en.freightBookingColActions,
        en.freightBookingColBookingCode,
        en.freightBookingColImportFile,
        en.freightBookingColConfirmationNo,
        en.freightBookingColCarrierForwarder,
        en.freightBookingColRoute,
        en.freightBookingColVesselVoyage,
        en.freightBookingColDeparture,
        en.freightBookingColArrival,
        en.freightBookingColContainers,
        en.freightBookingColTotalFreight,
        en.freightBookingColStatus,
        en.freightBookingApprovedQuoteLabel('Maersk'),
        en.freightBookingWhArrivalLabel('2026-09-01'),
        en.freightBookingPendingDate,
        en.freightBookingViewTooltip,
        en.freightBookingEditTooltip,
        en.freightBookingPrintTooltip,
        en.freightBookingDeleteTooltip,
        en.freightBookingDeleteConfirmTitle,
        en.freightBookingDeleteConfirmMessage('BK-001'),
        en.freightBookingNewDialogTitle,
        en.freightBookingEditDialogTitle('BK-001'),
        en.freightBookingCloseTooltip,
        en.freightBookingTabBookingDetails,
        en.freightBookingTabCostBreakdown,
        en.freightBookingImportFileLabel,
        en.freightBookingImportFileHint,
        en.freightBookingConfirmNoInputLabel,
        en.freightBookingConfirmNoValidator,
        en.freightBookingEvaluatedQuotesHeader,
        en.freightBookingAvailableQuotesBadge(3),
        en.freightBookingNoEvaluatedQuotes,
        en.freightBookingApplyQuoteInstruction,
        en.freightBookingBestQuoteBadge,
        en.freightBookingQuoteVesselDetails('CMA CGM', 'V-102', 'Shanghai', 'Alexandria'),
        en.freightBookingQuoteScheduleDetails('2026-08-20', '2026-09-10', 14),
        en.freightBookingQuoteStudyRef('SES-001', '2026-08-15'),
        en.freightBookingSelectedQuoteBtn,
        en.freightBookingApplyQuoteBtn,
        en.freightBookingQuoteAppliedSuccess('Maersk', 'Vessel 1'),
        en.freightBookingShippingLineLabel,
        en.freightBookingShippingLineHint,
        en.freightBookingForwarderLabel,
        en.freightBookingForwarderHint,
        en.freightBookingPolLabel,
        en.freightBookingPolHint,
        en.freightBookingPodLabel,
        en.freightBookingPodHint,
        en.freightBookingEtdLabel,
        en.freightBookingEtaLabel,
        en.freightBookingAtdLabel,
        en.freightBookingDelayBannerDelayed(5),
        en.freightBookingDelayBannerOnTime,
        en.freightBookingExpectedWhArrival('2026-09-15'),
        en.freightBookingFreeDaysInput,
        en.freightBookingWarehouseDaysInput,
        en.freightBookingStatusInputLabel,
        en.freightBookingVesselNameInput,
        en.freightBookingVoyageNoInput,
        en.freightBookingReleaseOrderInput,
        en.freightBookingContainerTypeInput,
        en.freightBookingContainersQtyInput,
        en.freightBookingEquipmentNote,
        en.freightBookingCostBreakdownTitle,
        en.freightBookingBaseCurrencyLabel('USD'),
        en.freightBookingItemRateLabel,
        en.freightBookingCurrencyLabel,
        en.freightBookingQuantityLabel,
        en.freightBookingCbmVolumeLabel,
        en.freightBookingItemActive,
        en.freightBookingItemInactive,
        en.freightBookingItem40ft,
        en.freightBookingItem20ft,
        en.freightBookingItemLcl,
        en.freightBookingItemCourier,
        en.freightBookingItemEur1,
        en.freightBookingItemVgm,
        en.freightBookingItemVgmNotif,
        en.freightBookingItemTelex,
        en.freightBookingItemInsurance,
        en.freightBookingItemCancellation,
        en.freightBookingItemIcs2,
        en.freightBookingItemOther,
        en.freightBookingItemDocFees,
        en.freightBookingItemWaiver,
        en.freightBookingItemDthc,
        en.freightBookingItemStorageWeek,
        en.freightBookingItemStorageExtra,
        en.freightBookingMismatchTitle,
        en.freightBookingMismatchWarning('40HC x1', '20GP x1'),
        en.freightBookingMismatchPrompt,
        en.freightBookingMismatchNote,
        en.freightBookingMismatchBtnNo,
        en.freightBookingMismatchBtnYes,
        en.freightBookingMismatchReasonTitle,
        en.freightBookingMismatchReasonHint,
        en.freightBookingMismatchReasonValidator,
        en.freightBookingMismatchReasonConfirm,
        en.freightBookingDuplicateTitle,
        en.freightBookingDuplicateMessage,
        en.freightBookingDuplicateRowFile,
        en.freightBookingDuplicateRowCode,
        en.freightBookingDuplicateRowConfirmNo,
        en.freightBookingDuplicateRowLine,
        en.freightBookingDuplicateRowStatus,
        en.freightBookingDuplicateNotice,
        en.freightBookingDuplicateBtnCancel,
        en.freightBookingDuplicateBtnSwitch,
        en.freightBookingBtnCloseDiscard,
        en.freightBookingBtnLiveReload,
        en.freightBookingBtnClearNew,
        en.freightBookingBtnSaveDraft,
        en.freightBookingBtnSaveConfirm,
        en.freightBookingBtnUpdate,
        en.freightBookingSaveSuccess,
        en.freightBookingViewTitle('BK-001'),
        en.freightBookingViewShippingLine,
        en.freightBookingViewConfirmNo,
        en.freightBookingViewRouteSection,
        en.freightBookingViewPol,
        en.freightBookingViewPod,
        en.freightBookingViewVesselVoyage('Vessel A', '101'),
        en.freightBookingViewTransitTime(25),
        en.freightBookingViewEtd('2026-08-20'),
        en.freightBookingViewEta('2026-09-15'),
        en.freightBookingViewAtd('2026-08-22', '+2d'),
        en.freightBookingViewExpectedWh('2026-09-20'),
        en.freightBookingViewContainersSection,
        en.freightBookingViewChargesSection,
        en.freightBookingViewTotalFreight,
        en.freightBookingPrintTitle('BK-001'),
        en.freightBookingPrintManifestHeader('BK-001'),
        en.freightBookingPrintDate('2026-08-24 10:00'),
        en.freightBookingPrintContainersHeader,
        en.freightBookingPrintChargesHeader,
        en.freightBookingPrintGrandTotal('3500.00'),
        en.freightBookingPrintNowBtn,
        en.freightBookingPrintSuccess,
      ];

      for (final s in arStrings) {
        expect(s.trim().isNotEmpty, isTrue, reason: 'Arabic translation string must not be empty');
      }

      for (final s in enStrings) {
        expect(s.trim().isNotEmpty, isTrue, reason: 'English translation string must not be empty');
      }
    });

    test('Translations should NOT contain stacked bilingual text patterns', () {
      final List<String> allAr = [
        ar.freightBookingStageTitle,
        ar.freightBookingTabRegistry,
        ar.freightBookingTabNewRequest,
        ar.freightBookingColActions,
        ar.freightBookingColBookingCode,
        ar.freightBookingColImportFile,
        ar.freightBookingColConfirmationNo,
        ar.freightBookingColCarrierForwarder,
        ar.freightBookingColRoute,
        ar.freightBookingColVesselVoyage,
        ar.freightBookingColDeparture,
        ar.freightBookingColArrival,
        ar.freightBookingColContainers,
        ar.freightBookingColTotalFreight,
        ar.freightBookingColStatus,
        ar.freightBookingNewDialogTitle,
        ar.freightBookingTabBookingDetails,
        ar.freightBookingTabCostBreakdown,
        ar.freightBookingImportFileLabel,
        ar.freightBookingConfirmNoInputLabel,
        ar.freightBookingShippingLineLabel,
        ar.freightBookingForwarderLabel,
        ar.freightBookingPolLabel,
        ar.freightBookingPodLabel,
        ar.freightBookingEtdLabel,
        ar.freightBookingEtaLabel,
        ar.freightBookingAtdLabel,
        ar.freightBookingFreeDaysInput,
        ar.freightBookingWarehouseDaysInput,
        ar.freightBookingStatusInputLabel,
        ar.freightBookingVesselNameInput,
        ar.freightBookingVoyageNoInput,
        ar.freightBookingReleaseOrderInput,
        ar.freightBookingContainerTypeInput,
        ar.freightBookingContainersQtyInput,
        ar.freightBookingCostBreakdownTitle,
        ar.freightBookingItem40ft,
        ar.freightBookingItem20ft,
        ar.freightBookingItemLcl,
        ar.freightBookingItemCourier,
        ar.freightBookingItemEur1,
        ar.freightBookingItemVgm,
        ar.freightBookingItemVgmNotif,
        ar.freightBookingItemTelex,
        ar.freightBookingItemInsurance,
        ar.freightBookingItemCancellation,
        ar.freightBookingItemIcs2,
        ar.freightBookingItemOther,
        ar.freightBookingItemDocFees,
        ar.freightBookingItemWaiver,
        ar.freightBookingItemDthc,
        ar.freightBookingItemStorageWeek,
        ar.freightBookingItemStorageExtra,
      ];

      final List<String> allEn = [
        en.freightBookingStageTitle,
        en.freightBookingTabRegistry,
        en.freightBookingTabNewRequest,
        en.freightBookingColActions,
        en.freightBookingColBookingCode,
        en.freightBookingColImportFile,
        en.freightBookingColConfirmationNo,
        en.freightBookingColCarrierForwarder,
        en.freightBookingColRoute,
        en.freightBookingColVesselVoyage,
        en.freightBookingColDeparture,
        en.freightBookingColArrival,
        en.freightBookingColContainers,
        en.freightBookingColTotalFreight,
        en.freightBookingColStatus,
        en.freightBookingNewDialogTitle,
        en.freightBookingTabBookingDetails,
        en.freightBookingTabCostBreakdown,
        en.freightBookingImportFileLabel,
        en.freightBookingConfirmNoInputLabel,
        en.freightBookingShippingLineLabel,
        en.freightBookingForwarderLabel,
        en.freightBookingPolLabel,
        en.freightBookingPodLabel,
        en.freightBookingEtdLabel,
        en.freightBookingEtaLabel,
        en.freightBookingAtdLabel,
        en.freightBookingFreeDaysInput,
        en.freightBookingWarehouseDaysInput,
        en.freightBookingStatusInputLabel,
        en.freightBookingVesselNameInput,
        en.freightBookingVoyageNoInput,
        en.freightBookingReleaseOrderInput,
        en.freightBookingContainerTypeInput,
        en.freightBookingContainersQtyInput,
        en.freightBookingCostBreakdownTitle,
        en.freightBookingItem40ft,
        en.freightBookingItem20ft,
        en.freightBookingItemLcl,
        en.freightBookingItemCourier,
        en.freightBookingItemEur1,
        en.freightBookingItemVgm,
        en.freightBookingItemVgmNotif,
        en.freightBookingItemTelex,
        en.freightBookingItemInsurance,
        en.freightBookingItemCancellation,
        en.freightBookingItemIcs2,
        en.freightBookingItemOther,
        en.freightBookingItemDocFees,
        en.freightBookingItemWaiver,
        en.freightBookingItemDthc,
        en.freightBookingItemStorageWeek,
        en.freightBookingItemStorageExtra,
      ];

      for (final s in allAr) {
        expect(s.contains('Booking Details'), isFalse);
        expect(s.contains('Carrier Allocation'), isFalse);
        expect(s.contains('Cost Breakdown'), isFalse);
        expect(s.contains('Shipping Line'), isFalse);
        expect(s.contains('Freight Forwarder'), isFalse);
        expect(s.contains('Release Order No'), isFalse);
      }

      for (final s in allEn) {
        expect(s.contains('حجز الشحن'), isFalse);
        expect(s.contains('الخط الملاحي'), isFalse);
        expect(s.contains('وكيل الشحن'), isFalse);
        expect(s.contains('ميناء التحميل'), isFalse);
        expect(s.contains('ميناء الوصول'), isFalse);
      }
    });

    test('Parameterized methods produce correct dynamic output', () {
      expect(ar.freightBookingDeleteConfirmMessage('BK-100'), contains('BK-100'));
      expect(en.freightBookingDeleteConfirmMessage('BK-100'), contains('BK-100'));
      expect(ar.freightBookingEditDialogTitle('BK-100'), contains('BK-100'));
      expect(en.freightBookingEditDialogTitle('BK-100'), contains('BK-100'));
      expect(ar.freightBookingAvailableQuotesBadge(5), contains('5'));
      expect(en.freightBookingAvailableQuotesBadge(5), contains('5'));
      expect(ar.freightBookingQuoteVesselDetails('Maersk', 'V10', 'CN', 'EG'), contains('Maersk'));
      expect(en.freightBookingQuoteVesselDetails('Maersk', 'V10', 'CN', 'EG'), contains('Maersk'));
      expect(ar.freightBookingViewTitle('BK-88'), contains('BK-88'));
      expect(en.freightBookingViewTitle('BK-88'), contains('BK-88'));
      expect(ar.freightBookingPrintTitle('BK-88'), contains('BK-88'));
      expect(en.freightBookingPrintTitle('BK-88'), contains('BK-88'));
    });
  });
}
