import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/core/localization/app_localizations.dart';
import 'package:frontend/core/localization/app_localizations_ar.dart';
import 'package:frontend/core/localization/app_localizations_en.dart';

void main() {
  group('Screen 45: HS Code Explorer & Duty Sandbox Localization Tests', () {
    const AppLocalizations ar = AppLocalizationsAr();
    const AppLocalizations en = AppLocalizationsEn();

    test('All Screen 45 getters should have non-empty Arabic and English translations', () {
      final List<String> arStrings = [
        ar.hsExplorerTitle,
        ar.hsExplorerSubtitle,
        ar.hsSearchPlaceholder,
        ar.hsQuickSearchExamples,
        ar.hsQuickQueryAc,
        ar.hsQuickQueryPlastics,
        ar.hsQuickQueryMeat,
        ar.hsQuickQueryWheat,
        ar.hsMatchingResultsHeader,
        ar.hsItemsCount(5),
        ar.hsNoMatchingItemFound('8415'),
        ar.hsDutyRateTag(10.0),
        ar.hsSelectFromListPrompt,
        ar.hsCategoryPrefix('Machinery'),
        ar.hsEffectiveFromPrefix('2026-01-01'),
        ar.hsEffectiveToPrefix('2026-12-31'),
        ar.hsEffectiveActiveRecord,
        ar.hsDiffHistoryAction,
        ar.hsTabTaxRates,
        ar.hsTabAgreements,
        ar.hsTabRegulatory,
        ar.hsTabHistory,
        ar.hsTabQuickCalculator,
        ar.hsTaxRatesSectionHeader,
        ar.hsTaxImportDutyTitle,
        ar.hsTaxImportDutySub,
        ar.hsTaxVatTitle,
        ar.hsTaxVatSub,
        ar.hsTaxScheduleTitle,
        ar.hsTaxScheduleSub,
        ar.hsTaxDevFeeTitle,
        ar.hsTaxDevFeeSub,
        ar.hsTaxImportFeeTitle,
        ar.hsTaxImportFeeSub,
        ar.hsTaxServiceFeeTitle,
        ar.hsTaxServiceFeeSub,
        ar.hsEgyptianCalculationRule,
        ar.hsNoAgreementsFound,
        ar.hsDefaultAgreementName,
        ar.hsRequiredDocPrefix('EUR.1'),
        ar.hsConditionsPrefix('Direct transport'),
        ar.hsFullExemptionBadge,
        ar.hsReducedRateBadge(5.0),
        ar.hsRegulatorySectionHeader,
        ar.hsReqAcidSystem,
        ar.hsReqCertificateOfOrigin,
        ar.hsReqQualityInspection,
        ar.hsRegulatoryAuthorityPrefix('GOEIC'),
        ar.hsDecreesAndNotesHeader,
        ar.hsHistorySummaryTitle('8415.82'),
        ar.hsHistoryMultipleVersionsDesc(3),
        ar.hsHistorySingleVersionDesc,
        ar.hsVersionsCountTag(2),
        ar.hsTimelineSectionTitle,
        ar.hsNoHistoricalVersions,
        ar.hsActiveLiveVersionBadge,
        ar.hsArchivedSnapshotBadge,
        ar.hsRegistrationDatePrefix('2026-01-01'),
        ar.hsValidityPeriodPrefix('2026-01-01', '2026-12-31'),
        ar.hsApprovedDescPrefix('Air Conditioners'),
        ar.hsLinkedAgreementsTag(2),
        ar.hsVersionDiffsSummaryHeader,
        ar.hsDiffTitle('2025-01-01', '2026-01-01'),
        ar.hsDiffDutyChanged(5.0, 10.0),
        ar.hsDiffVatChanged(10.0, 14.0),
        ar.hsDiffScheduleChanged(0.0, 5.0),
        ar.hsDiffAgreementsChanged(1, 2),
        ar.hsDiffMetadataChanged,
        ar.hsAuditTrailSectionTitle,
        ar.hsNoAuditLogsFound,
        ar.hsAuditPerformedBy('Ahmed', '2026-01-01'),
        ar.hsCalculatorSectionHeader,
        ar.hsCifValueLabel,
        ar.hsFreightValueLabel,
        ar.hsOriginCountryLabel,
        ar.hsOriginItalyEur1,
        ar.hsOriginGermanyEur1,
        ar.hsOriginChinaGeneral,
        ar.hsOriginTurkeyFta,
        ar.hsOriginBrazilMercosur,
        ar.hsOriginSerbiaFta,
        ar.hsOriginUkPartnership,
        ar.hsCalculateDutyBtn,
        ar.hsTotalTaxesAndFeesDue('15000'),
        ar.hsNotePrefix('Preferential rate applies'),
        ar.hsImportDutyBreakdown(10.0, '10000'),
        ar.hsVatBreakdown(14.0, '14000'),
        ar.hsScheduleBreakdown('5000'),
        ar.hsServiceFeeBreakdown('1200'),
        ar.hsDatePresentOngoing,
        ar.hsDateToday,
        ar.hsDateInitial,
        ar.hsActionExecuted,
        ar.hsExplorerExportTsvBtn,
        ar.hsExplorerExportTsvSuccess,
        ar.hsExplorerExportExcelBtn,
        ar.hsExplorerExportPdfBtn,
        ar.hsExplorerCopyHsCodeTooltip,
        ar.hsExplorerCopySummaryBtn,
        ar.hsExplorerCopySummarySuccess,
        ar.hsExplorerCopyDutyBreakdownBtn,
        ar.hsExplorerCopyDutyBreakdownSuccess,
        ar.hsExplorerCopyCardRateTooltip,
        ar.hsExplorerTsvHeaderHsCode,
        ar.hsExplorerTsvHeaderDescription,
        ar.hsExplorerTsvHeaderCategory,
        ar.hsExplorerTsvHeaderDutyRate,
        ar.hsExplorerTsvHeaderVatRate,
        ar.hsExplorerTsvHeaderScheduleRate,
        ar.hsExplorerTsvHeaderDevFeeRate,
        ar.hsExplorerTsvHeaderImportFeeRate,
        ar.hsExplorerTsvHeaderServiceFeeRate,
        ar.hsExplorerTsvHeaderRegulatoryAuthority,
        ar.hsExplorerTsvHeaderAcidRequired,
        ar.hsExplorerTsvHeaderCooRequired,
        ar.hsExplorerTsvHeaderInspectionRequired,
        ar.hsExplorerTsvHeaderStatus,
      ];

      final List<String> enStrings = [
        en.hsExplorerTitle,
        en.hsExplorerSubtitle,
        en.hsSearchPlaceholder,
        en.hsQuickSearchExamples,
        en.hsQuickQueryAc,
        en.hsQuickQueryPlastics,
        en.hsQuickQueryMeat,
        en.hsQuickQueryWheat,
        en.hsMatchingResultsHeader,
        en.hsItemsCount(5),
        en.hsNoMatchingItemFound('8415'),
        en.hsDutyRateTag(10.0),
        en.hsSelectFromListPrompt,
        en.hsCategoryPrefix('Machinery'),
        en.hsEffectiveFromPrefix('2026-01-01'),
        en.hsEffectiveToPrefix('2026-12-31'),
        en.hsEffectiveActiveRecord,
        en.hsDiffHistoryAction,
        en.hsTabTaxRates,
        en.hsTabAgreements,
        en.hsTabRegulatory,
        en.hsTabHistory,
        en.hsTabQuickCalculator,
        en.hsTaxRatesSectionHeader,
        en.hsTaxImportDutyTitle,
        en.hsTaxImportDutySub,
        en.hsTaxVatTitle,
        en.hsTaxVatSub,
        en.hsTaxScheduleTitle,
        en.hsTaxScheduleSub,
        en.hsTaxDevFeeTitle,
        en.hsTaxDevFeeSub,
        en.hsTaxImportFeeTitle,
        en.hsTaxImportFeeSub,
        en.hsTaxServiceFeeTitle,
        en.hsTaxServiceFeeSub,
        en.hsEgyptianCalculationRule,
        en.hsNoAgreementsFound,
        en.hsDefaultAgreementName,
        en.hsRequiredDocPrefix('EUR.1'),
        en.hsConditionsPrefix('Direct transport'),
        en.hsFullExemptionBadge,
        en.hsReducedRateBadge(5.0),
        en.hsRegulatorySectionHeader,
        en.hsReqAcidSystem,
        en.hsReqCertificateOfOrigin,
        en.hsReqQualityInspection,
        en.hsRegulatoryAuthorityPrefix('GOEIC'),
        en.hsDecreesAndNotesHeader,
        en.hsHistorySummaryTitle('8415.82'),
        en.hsHistoryMultipleVersionsDesc(3),
        en.hsHistorySingleVersionDesc,
        en.hsVersionsCountTag(2),
        en.hsTimelineSectionTitle,
        en.hsNoHistoricalVersions,
        en.hsActiveLiveVersionBadge,
        en.hsArchivedSnapshotBadge,
        en.hsRegistrationDatePrefix('2026-01-01'),
        en.hsValidityPeriodPrefix('2026-01-01', '2026-12-31'),
        en.hsApprovedDescPrefix('Air Conditioners'),
        en.hsLinkedAgreementsTag(2),
        en.hsVersionDiffsSummaryHeader,
        en.hsDiffTitle('2025-01-01', '2026-01-01'),
        en.hsDiffDutyChanged(5.0, 10.0),
        en.hsDiffVatChanged(10.0, 14.0),
        en.hsDiffScheduleChanged(0.0, 5.0),
        en.hsDiffAgreementsChanged(1, 2),
        en.hsDiffMetadataChanged,
        en.hsAuditTrailSectionTitle,
        en.hsNoAuditLogsFound,
        en.hsAuditPerformedBy('Ahmed', '2026-01-01'),
        en.hsCalculatorSectionHeader,
        en.hsCifValueLabel,
        en.hsFreightValueLabel,
        en.hsOriginCountryLabel,
        en.hsOriginItalyEur1,
        en.hsOriginGermanyEur1,
        en.hsOriginChinaGeneral,
        en.hsOriginTurkeyFta,
        en.hsOriginBrazilMercosur,
        en.hsOriginSerbiaFta,
        en.hsOriginUkPartnership,
        en.hsCalculateDutyBtn,
        en.hsTotalTaxesAndFeesDue('15000'),
        en.hsNotePrefix('Preferential rate applies'),
        en.hsImportDutyBreakdown(10.0, '10000'),
        en.hsVatBreakdown(14.0, '14000'),
        en.hsScheduleBreakdown('5000'),
        en.hsServiceFeeBreakdown('1200'),
        en.hsDatePresentOngoing,
        en.hsDateToday,
        en.hsDateInitial,
        en.hsActionExecuted,
        en.hsExplorerExportTsvBtn,
        en.hsExplorerExportTsvSuccess,
        en.hsExplorerExportExcelBtn,
        en.hsExplorerExportPdfBtn,
        en.hsExplorerCopyHsCodeTooltip,
        en.hsExplorerCopySummaryBtn,
        en.hsExplorerCopySummarySuccess,
        en.hsExplorerCopyDutyBreakdownBtn,
        en.hsExplorerCopyDutyBreakdownSuccess,
        en.hsExplorerCopyCardRateTooltip,
        en.hsExplorerTsvHeaderHsCode,
        en.hsExplorerTsvHeaderDescription,
        en.hsExplorerTsvHeaderCategory,
        en.hsExplorerTsvHeaderDutyRate,
        en.hsExplorerTsvHeaderVatRate,
        en.hsExplorerTsvHeaderScheduleRate,
        en.hsExplorerTsvHeaderDevFeeRate,
        en.hsExplorerTsvHeaderImportFeeRate,
        en.hsExplorerTsvHeaderServiceFeeRate,
        en.hsExplorerTsvHeaderRegulatoryAuthority,
        en.hsExplorerTsvHeaderAcidRequired,
        en.hsExplorerTsvHeaderCooRequired,
        en.hsExplorerTsvHeaderInspectionRequired,
        en.hsExplorerTsvHeaderStatus,
      ];

      expect(arStrings.length, enStrings.length);
      for (int i = 0; i < arStrings.length; i++) {
        expect(arStrings[i].trim().isNotEmpty, isTrue, reason: 'Arabic string at index $i is empty');
        expect(enStrings[i].trim().isNotEmpty, isTrue, reason: 'English string at index $i is empty');
      }
    });

    test('Screen 45 Arabic static translations contain 0 Latin characters', () {
      final List<String> arStaticStrings = [
        ar.hsExplorerTitle,
        ar.hsExplorerSubtitle,
        ar.hsSearchPlaceholder,
        ar.hsQuickSearchExamples,
        ar.hsQuickQueryAc,
        ar.hsQuickQueryPlastics,
        ar.hsQuickQueryMeat,
        ar.hsQuickQueryWheat,
        ar.hsMatchingResultsHeader,
        ar.hsSelectFromListPrompt,
        ar.hsEffectiveActiveRecord,
        ar.hsDiffHistoryAction,
        ar.hsTabTaxRates,
        ar.hsTabAgreements,
        ar.hsTabRegulatory,
        ar.hsTabHistory,
        ar.hsTabQuickCalculator,
        ar.hsTaxRatesSectionHeader,
        ar.hsTaxImportDutyTitle,
        ar.hsTaxImportDutySub,
        ar.hsTaxVatTitle,
        ar.hsTaxVatSub,
        ar.hsTaxScheduleTitle,
        ar.hsTaxScheduleSub,
        ar.hsTaxDevFeeTitle,
        ar.hsTaxDevFeeSub,
        ar.hsTaxImportFeeTitle,
        ar.hsTaxImportFeeSub,
        ar.hsTaxServiceFeeTitle,
        ar.hsTaxServiceFeeSub,
        ar.hsEgyptianCalculationRule,
        ar.hsNoAgreementsFound,
        ar.hsDefaultAgreementName,
        ar.hsFullExemptionBadge,
        ar.hsRegulatorySectionHeader,
        ar.hsReqAcidSystem,
        ar.hsReqCertificateOfOrigin,
        ar.hsReqQualityInspection,
        ar.hsDecreesAndNotesHeader,
        ar.hsCalculatorSectionHeader,
        ar.hsCifValueLabel,
        ar.hsFreightValueLabel,
        ar.hsOriginCountryLabel,
        ar.hsOriginItalyEur1,
        ar.hsOriginGermanyEur1,
        ar.hsOriginChinaGeneral,
        ar.hsOriginTurkeyFta,
        ar.hsOriginBrazilMercosur,
        ar.hsOriginSerbiaFta,
        ar.hsOriginUkPartnership,
        ar.hsCalculateDutyBtn,
        ar.hsHistorySingleVersionDesc,
        ar.hsTimelineSectionTitle,
        ar.hsNoHistoricalVersions,
        ar.hsActiveLiveVersionBadge,
        ar.hsArchivedSnapshotBadge,
        ar.hsVersionDiffsSummaryHeader,
        ar.hsDiffMetadataChanged,
        ar.hsAuditTrailSectionTitle,
        ar.hsNoAuditLogsFound,
        ar.hsDatePresentOngoing,
        ar.hsDateToday,
        ar.hsDateInitial,
        ar.hsActionExecuted,
        ar.hsExplorerExportTsvBtn,
        ar.hsExplorerExportTsvSuccess,
        ar.hsExplorerExportExcelBtn,
        ar.hsExplorerExportPdfBtn,
        ar.hsExplorerCopyHsCodeTooltip,
        ar.hsExplorerCopySummaryBtn,
        ar.hsExplorerCopySummarySuccess,
        ar.hsExplorerCopyDutyBreakdownBtn,
        ar.hsExplorerCopyDutyBreakdownSuccess,
        ar.hsExplorerCopyCardRateTooltip,
        ar.hsExplorerTsvHeaderHsCode,
        ar.hsExplorerTsvHeaderDescription,
        ar.hsExplorerTsvHeaderCategory,
        ar.hsExplorerTsvHeaderDutyRate,
        ar.hsExplorerTsvHeaderVatRate,
        ar.hsExplorerTsvHeaderScheduleRate,
        ar.hsExplorerTsvHeaderDevFeeRate,
        ar.hsExplorerTsvHeaderImportFeeRate,
        ar.hsExplorerTsvHeaderServiceFeeRate,
        ar.hsExplorerTsvHeaderRegulatoryAuthority,
        ar.hsExplorerTsvHeaderAcidRequired,
        ar.hsExplorerTsvHeaderCooRequired,
        ar.hsExplorerTsvHeaderInspectionRequired,
        ar.hsExplorerTsvHeaderStatus,
      ];

      for (final s in arStaticStrings) {
        expect(RegExp(r'[a-zA-Z]').hasMatch(s), isFalse, reason: 'Arabic string contains Latin characters: "$s"');
      }
    });

    test('TSV export headers contains exactly 14 columns', () {
      final headers = [
        ar.hsExplorerTsvHeaderHsCode,
        ar.hsExplorerTsvHeaderDescription,
        ar.hsExplorerTsvHeaderCategory,
        ar.hsExplorerTsvHeaderDutyRate,
        ar.hsExplorerTsvHeaderVatRate,
        ar.hsExplorerTsvHeaderScheduleRate,
        ar.hsExplorerTsvHeaderDevFeeRate,
        ar.hsExplorerTsvHeaderImportFeeRate,
        ar.hsExplorerTsvHeaderServiceFeeRate,
        ar.hsExplorerTsvHeaderRegulatoryAuthority,
        ar.hsExplorerTsvHeaderAcidRequired,
        ar.hsExplorerTsvHeaderCooRequired,
        ar.hsExplorerTsvHeaderInspectionRequired,
        ar.hsExplorerTsvHeaderStatus,
      ];

      expect(headers.length, 14);
      expect(headers.toSet().length, 14, reason: 'All 14 TSV headers must be distinct');
    });
  });
}
