import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/core/localization/app_localizations.dart';
import 'package:frontend/core/localization/app_localizations_ar.dart';
import 'package:frontend/core/localization/app_localizations_en.dart';

void main() {
  group('Screen 32: Egyptian Import Companies Localization Tests', () {
    const AppLocalizations ar = AppLocalizationsAr();
    const AppLocalizations en = AppLocalizationsEn();

    test('All Screen 32 getters should have non-empty Arabic and English translations', () {
      final List<String> arStrings = [
        ar.importCompaniesScreenTitle,
        ar.importCompaniesScreenSubtitle,
        ar.includeDeactivatedLabel,
        ar.addImporterCompanyBtn,
        ar.searchImporterHint,
        ar.importersFetchError('Connection timeout'),
        ar.retryConnectionBtn,
        ar.noImportCompaniesFound,
        ar.statusActive,
        ar.statusInactive,
        ar.importerRowMeta('528153439', '528153439', '100200000070828'),
        ar.badgeImportId,
        ar.badgeVatExpiry,
        ar.badgeComReg,
        ar.expiryExpired,
        ar.expiryDaysLeft(15),
        ar.expiryValidDays(120),
        ar.confirmDeactivateCompany('Pharaohs LLC'),
        ar.confirmActivateCompany('Pharaohs LLC'),
        ar.deactivateCompanyTooltip,
        ar.activateCompanyTooltip,
        ar.editImporterCompanyTitle,
        ar.addImporterCompanyTitle,
        ar.closeDialogTooltip,
        ar.companyNameLabel,
        ar.companyNameHint,
        ar.addressLabel,
        ar.addressHint,
        ar.countryLabel,
        ar.importerCardIdLabel,
        ar.importerCardIdHint,
        ar.importerCardExpiryLabel,
        ar.vatRegIdLabel,
        ar.vatRegIdHint,
        ar.vatRegExpiryLabel,
        ar.commercialRegNumLabel,
        ar.commercialRegNumHint,
        ar.commercialRegExpiryLabel,
        ar.phoneNumberLabel,
        ar.phoneNumberHint,
        ar.cancelAndCloseBtn,
        ar.updateCompanyBtn,
        ar.saveCompanyBtn,
        ar.diffCompanyName,
        ar.diffImporterCardId,
        ar.diffImporterCardExpiry,
        ar.diffVatId,
        ar.diffCommercialReg,
        ar.diffAddress,
        ar.diffPhone,
        ar.diffConfirmCompanyTitle,
        ar.importerProfileSubtitle,
        ar.officialRegistrationsHeader,
        ar.importerCardIdRowLabel,
        ar.vatTaxIdRowLabel,
        ar.commercialRegRowLabel,
        ar.expiryEndingSoon(20),
        ar.expiryValidDaysRemaining(90),
        ar.expiryDateLabel('2026-12-31'),
        ar.copiedToClipboard('528153439'),
        ar.locationAndContactHeader,
        ar.countryRowLabel,
        ar.egyptCountryFallback,
        ar.addressRowLabel,
        ar.phoneRowLabel,
        ar.emailRowLabel,
        ar.administrativeNotesHeader,
        ar.printSavePdfBtn,
        ar.downloadExcelBtn,
        ar.excelSavedSuccess('C:/reports/importer.xlsx'),
        ar.whatsappShareBtn,
        ar.emailShareBtn,
        ar.whatsappPreviewTitle,
        ar.copyWhatsappTextBtn,
        ar.whatsappCopiedSuccess,
        ar.emailPreviewTitle,
        ar.emailSubjectPrefix('Company Details'),
        ar.copyEmailTextBtn,
        ar.emailCopiedSuccess,
      ];

      final List<String> enStrings = [
        en.importCompaniesScreenTitle,
        en.importCompaniesScreenSubtitle,
        en.includeDeactivatedLabel,
        en.addImporterCompanyBtn,
        en.searchImporterHint,
        en.importersFetchError('Connection timeout'),
        en.retryConnectionBtn,
        en.noImportCompaniesFound,
        en.statusActive,
        en.statusInactive,
        en.importerRowMeta('528153439', '528153439', '100200000070828'),
        en.badgeImportId,
        en.badgeVatExpiry,
        en.badgeComReg,
        en.expiryExpired,
        en.expiryDaysLeft(15),
        en.expiryValidDays(120),
        en.confirmDeactivateCompany('Pharaohs LLC'),
        en.confirmActivateCompany('Pharaohs LLC'),
        en.deactivateCompanyTooltip,
        en.activateCompanyTooltip,
        en.editImporterCompanyTitle,
        en.addImporterCompanyTitle,
        en.closeDialogTooltip,
        en.companyNameLabel,
        en.companyNameHint,
        en.addressLabel,
        en.addressHint,
        en.countryLabel,
        en.importerCardIdLabel,
        en.importerCardIdHint,
        en.importerCardExpiryLabel,
        en.vatRegIdLabel,
        en.vatRegIdHint,
        en.vatRegExpiryLabel,
        en.commercialRegNumLabel,
        en.commercialRegNumHint,
        en.commercialRegExpiryLabel,
        en.phoneNumberLabel,
        en.phoneNumberHint,
        en.cancelAndCloseBtn,
        en.updateCompanyBtn,
        en.saveCompanyBtn,
        en.diffCompanyName,
        en.diffImporterCardId,
        en.diffImporterCardExpiry,
        en.diffVatId,
        en.diffCommercialReg,
        en.diffAddress,
        en.diffPhone,
        en.diffConfirmCompanyTitle,
        en.importerProfileSubtitle,
        en.officialRegistrationsHeader,
        en.importerCardIdRowLabel,
        en.vatTaxIdRowLabel,
        en.commercialRegRowLabel,
        en.expiryEndingSoon(20),
        en.expiryValidDaysRemaining(90),
        en.expiryDateLabel('2026-12-31'),
        en.copiedToClipboard('528153439'),
        en.locationAndContactHeader,
        en.countryRowLabel,
        en.egyptCountryFallback,
        en.addressRowLabel,
        en.phoneRowLabel,
        en.emailRowLabel,
        en.administrativeNotesHeader,
        en.printSavePdfBtn,
        en.downloadExcelBtn,
        en.excelSavedSuccess('C:/reports/importer.xlsx'),
        en.whatsappShareBtn,
        en.emailShareBtn,
        en.whatsappPreviewTitle,
        en.copyWhatsappTextBtn,
        en.whatsappCopiedSuccess,
        en.emailPreviewTitle,
        en.emailSubjectPrefix('Company Details'),
        en.copyEmailTextBtn,
        en.emailCopiedSuccess,
      ];

      expect(arStrings.length, enStrings.length);
      for (int i = 0; i < arStrings.length; i++) {
        expect(arStrings[i].trim().isNotEmpty, isTrue, reason: 'Arabic string at index $i is empty');
        expect(enStrings[i].trim().isNotEmpty, isTrue, reason: 'English string at index $i is empty');
      }
    });

    test('Verify pure Arabic translations without stacked or Latin characters in static keys', () {
      final List<String> arStaticStrings = [
        ar.importCompaniesScreenTitle,
        ar.importCompaniesScreenSubtitle,
        ar.includeDeactivatedLabel,
        ar.addImporterCompanyBtn,
        ar.searchImporterHint,
        ar.retryConnectionBtn,
        ar.noImportCompaniesFound,
        ar.statusActive,
        ar.statusInactive,
        ar.badgeImportId,
        ar.badgeVatExpiry,
        ar.badgeComReg,
        ar.expiryExpired,
        ar.deactivateCompanyTooltip,
        ar.activateCompanyTooltip,
        ar.editImporterCompanyTitle,
        ar.addImporterCompanyTitle,
        ar.closeDialogTooltip,
        ar.companyNameLabel,
        ar.addressLabel,
        ar.countryLabel,
        ar.importerCardExpiryLabel,
        ar.vatRegExpiryLabel,
        ar.commercialRegExpiryLabel,
        ar.phoneNumberLabel,
        ar.updateCompanyBtn,
        ar.saveCompanyBtn,
        ar.diffCompanyName,
        ar.diffImporterCardId,
        ar.diffImporterCardExpiry,
        ar.diffVatId,
        ar.diffCommercialReg,
        ar.diffAddress,
        ar.diffPhone,
        ar.diffConfirmCompanyTitle,
        ar.importerProfileSubtitle,
        ar.officialRegistrationsHeader,
        ar.importerCardIdRowLabel,
        ar.vatTaxIdRowLabel,
        ar.commercialRegRowLabel,
        ar.locationAndContactHeader,
        ar.countryRowLabel,
        ar.egyptCountryFallback,
        ar.addressRowLabel,
        ar.phoneRowLabel,
        ar.emailRowLabel,
        ar.administrativeNotesHeader,
        ar.whatsappPreviewTitle,
        ar.whatsappCopiedSuccess,
        ar.emailPreviewTitle,
        ar.emailCopiedSuccess,
      ];

      for (final s in arStaticStrings) {
        expect(RegExp(r'[a-zA-Z]').hasMatch(s), isFalse, reason: 'Arabic string contains Latin characters: $s');
      }
    });
  });
}
