import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/core/localization/app_localizations.dart';
import 'package:frontend/core/localization/app_localizations_ar.dart';
import 'package:frontend/core/localization/app_localizations_en.dart';

void main() {
  group('Screen 35: Incoterms Rules Localization Tests', () {
    const AppLocalizations ar = AppLocalizationsAr();
    const AppLocalizations en = AppLocalizationsEn();

    test('All Screen 35 getters should have non-empty Arabic and English translations', () {
      final List<String> arStrings = [
        ar.incotermsScreenTitle,
        ar.incotermsScreenSubtitle,
        ar.incotermsTabRules,
        ar.incotermsTabCostItems,
        ar.incotermsTabMatrix,
        ar.searchIncotermsHint,
        ar.showInactiveIncotermsLabel,
        ar.addIncotermBtn,
        ar.noIncotermsFound,
        ar.incotermCodeCol,
        ar.incotermNameCol,
        ar.incotermVersionCol,
        ar.incotermStatusCol,
        ar.incotermActionsCol,
        ar.printIncotermSnack('FOB', 'Free on Board'),
        ar.confirmDeactivateIncoterm('FOB'),
        ar.confirmActivateIncoterm('FOB'),
        ar.deactivateIncotermTooltip,
        ar.activateIncotermTooltip,
        ar.editIncotermDialogTitle,
        ar.addIncotermDialogTitle,
        ar.incotermCodeLabel,
        ar.incotermFullNameLabel,
        ar.incotermVersionLabel,
        ar.incotermDescriptionLabel,
        ar.addCostItemBtn,
        ar.showInactiveCostItemsLabel,
        ar.noCostItemsFound,
        ar.costItemCodeCol,
        ar.costItemNameCol,
        ar.costItemCategoryCol,
        ar.costItemStatusCol,
        ar.costItemActionsCol,
        ar.costCategoryFreight,
        ar.costCategoryCustoms,
        ar.costCategoryPort,
        ar.costCategoryBank,
        ar.costCategoryOther,
        ar.printCostItemSnack('THC', 'Terminal Handling Charge'),
        ar.confirmDeactivateCostItem('THC'),
        ar.confirmActivateCostItem('THC'),
        ar.deactivateCostItemTooltip,
        ar.activateCostItemTooltip,
        ar.editCostItemDialogTitle,
        ar.addCostItemDialogTitle,
        ar.costItemCodeLabel,
        ar.costItemNameLabel,
        ar.costCategoryLabel,
        ar.costItemDescriptionLabel,
        ar.filterByIncotermLabel,
        ar.allIncotermsOption,
        ar.showingAllMatrixResponsibilities,
        ar.filteringResponsibilitiesForSelectedTerm,
        ar.noMatrixDataFound,
        ar.matrixIncotermCol,
        ar.matrixCostItemCol,
        ar.matrixCategoryCol,
        ar.matrixResponsibleCol,
        ar.matrixIncludedCol,
        ar.matrixNotesCol,
        ar.matrixActionsCol,
        ar.partyBuyerImporter,
        ar.partySellerExporter,
        ar.partyShared,
        ar.editResponsibilityTooltip,
        ar.editResponsibilityDialogTitle('FOB'),
        ar.incotermPrefix('FOB'),
        ar.costItemPrefix('Ocean Freight', 'Freight'),
        ar.matrixResponsiblePartyFieldLabel,
        ar.includedInSellerPriceTitle,
        ar.includedInSellerPriceSubtitle,
        ar.commentNotesLabel,
        ar.commentNotesHint,
        ar.updatedSuccessfully,
      ];

      final List<String> enStrings = [
        en.incotermsScreenTitle,
        en.incotermsScreenSubtitle,
        en.incotermsTabRules,
        en.incotermsTabCostItems,
        en.incotermsTabMatrix,
        en.searchIncotermsHint,
        en.showInactiveIncotermsLabel,
        en.addIncotermBtn,
        en.noIncotermsFound,
        en.incotermCodeCol,
        en.incotermNameCol,
        en.incotermVersionCol,
        en.incotermStatusCol,
        en.incotermActionsCol,
        en.printIncotermSnack('FOB', 'Free on Board'),
        en.confirmDeactivateIncoterm('FOB'),
        en.confirmActivateIncoterm('FOB'),
        en.deactivateIncotermTooltip,
        en.activateIncotermTooltip,
        en.editIncotermDialogTitle,
        en.addIncotermDialogTitle,
        en.incotermCodeLabel,
        en.incotermFullNameLabel,
        en.incotermVersionLabel,
        en.incotermDescriptionLabel,
        en.addCostItemBtn,
        en.showInactiveCostItemsLabel,
        en.noCostItemsFound,
        en.costItemCodeCol,
        en.costItemNameCol,
        en.costItemCategoryCol,
        en.costItemStatusCol,
        en.costItemActionsCol,
        en.costCategoryFreight,
        en.costCategoryCustoms,
        en.costCategoryPort,
        en.costCategoryBank,
        en.costCategoryOther,
        en.printCostItemSnack('THC', 'Terminal Handling Charge'),
        en.confirmDeactivateCostItem('THC'),
        en.confirmActivateCostItem('THC'),
        en.deactivateCostItemTooltip,
        en.activateCostItemTooltip,
        en.editCostItemDialogTitle,
        en.addCostItemDialogTitle,
        en.costItemCodeLabel,
        en.costItemNameLabel,
        en.costCategoryLabel,
        en.costItemDescriptionLabel,
        en.filterByIncotermLabel,
        en.allIncotermsOption,
        en.showingAllMatrixResponsibilities,
        en.filteringResponsibilitiesForSelectedTerm,
        en.noMatrixDataFound,
        en.matrixIncotermCol,
        en.matrixCostItemCol,
        en.matrixCategoryCol,
        en.matrixResponsibleCol,
        en.matrixIncludedCol,
        en.matrixNotesCol,
        en.matrixActionsCol,
        en.partyBuyerImporter,
        en.partySellerExporter,
        en.partyShared,
        en.editResponsibilityTooltip,
        en.editResponsibilityDialogTitle('FOB'),
        en.incotermPrefix('FOB'),
        en.costItemPrefix('Ocean Freight', 'Freight'),
        en.matrixResponsiblePartyFieldLabel,
        en.includedInSellerPriceTitle,
        en.includedInSellerPriceSubtitle,
        en.commentNotesLabel,
        en.commentNotesHint,
        en.updatedSuccessfully,
      ];

      expect(arStrings.length, enStrings.length);
      for (int i = 0; i < arStrings.length; i++) {
        expect(arStrings[i].trim().isNotEmpty, isTrue, reason: 'Arabic string at index $i is empty');
        expect(enStrings[i].trim().isNotEmpty, isTrue, reason: 'English string at index $i is empty');
      }
    });

    test('Verify pure Arabic translations without stacked or Latin characters in static keys', () {
      final List<String> arStaticStrings = [
        ar.incotermsScreenTitle,
        ar.incotermsScreenSubtitle,
        ar.incotermsTabRules,
        ar.incotermsTabCostItems,
        ar.incotermsTabMatrix,
        ar.searchIncotermsHint,
        ar.showInactiveIncotermsLabel,
        ar.addIncotermBtn,
        ar.noIncotermsFound,
        ar.incotermCodeCol,
        ar.incotermNameCol,
        ar.incotermVersionCol,
        ar.incotermStatusCol,
        ar.incotermActionsCol,
        ar.deactivateIncotermTooltip,
        ar.activateIncotermTooltip,
        ar.editIncotermDialogTitle,
        ar.addIncotermDialogTitle,
        ar.incotermCodeLabel,
        ar.incotermFullNameLabel,
        ar.incotermVersionLabel,
        ar.incotermDescriptionLabel,
        ar.addCostItemBtn,
        ar.showInactiveCostItemsLabel,
        ar.noCostItemsFound,
        ar.costItemCodeCol,
        ar.costItemNameCol,
        ar.costItemCategoryCol,
        ar.costItemStatusCol,
        ar.costItemActionsCol,
        ar.costCategoryFreight,
        ar.costCategoryCustoms,
        ar.costCategoryPort,
        ar.costCategoryBank,
        ar.costCategoryOther,
        ar.deactivateCostItemTooltip,
        ar.activateCostItemTooltip,
        ar.editCostItemDialogTitle,
        ar.addCostItemDialogTitle,
        ar.costItemCodeLabel,
        ar.costItemNameLabel,
        ar.costCategoryLabel,
        ar.costItemDescriptionLabel,
        ar.filterByIncotermLabel,
        ar.allIncotermsOption,
        ar.showingAllMatrixResponsibilities,
        ar.filteringResponsibilitiesForSelectedTerm,
        ar.noMatrixDataFound,
        ar.matrixIncotermCol,
        ar.matrixCostItemCol,
        ar.matrixCategoryCol,
        ar.matrixResponsibleCol,
        ar.matrixIncludedCol,
        ar.matrixNotesCol,
        ar.matrixActionsCol,
        ar.partyBuyerImporter,
        ar.partySellerExporter,
        ar.partyShared,
        ar.editResponsibilityTooltip,
        ar.matrixResponsiblePartyFieldLabel,
        ar.includedInSellerPriceTitle,
        ar.includedInSellerPriceSubtitle,
        ar.commentNotesLabel,
        ar.commentNotesHint,
        ar.updatedSuccessfully,
      ];

      for (final s in arStaticStrings) {
        expect(RegExp(r'[a-zA-Z]').hasMatch(s), isFalse, reason: 'Arabic string contains Latin characters: $s');
      }
    });
  });
}
