import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/core/localization/app_localizations.dart';
import 'package:frontend/core/localization/app_localizations_ar.dart';
import 'package:frontend/core/localization/app_localizations_en.dart';

void main() {
  group('Screen 21: PO & Packing Reconciliation Localization Tests', () {
    const AppLocalizations ar = AppLocalizationsAr();
    const AppLocalizations en = AppLocalizationsEn();

    test('All Screen 21 getters should have non-empty Arabic and English translations', () {
      final List<String> arStrings = [
        ar.poRecSampleLoadedSuccess,
        ar.poRecFileSelected('test.pdf', '256'),
        ar.poRecFilePickFailed('File error'),
        ar.poRecExtractedDigitalFileNotice('sample.xlsx'),
        ar.poRecInputValidationTitle,
        ar.poRecInputValidationDesc,
        ar.poRecInputValidationRecHeader,
        ar.poRecInputValidationGotIt,
        ar.poRecIssueNoFileSelected,
        ar.poRecRecSelectFileFromList,
        ar.poRecIssueEmptyInputs,
        ar.poRecRecProvideInputs,
        ar.poRecServerSuccessNotice,
        ar.poRecFallbackSuccessNotice,
        ar.poRecApplyExtractedSuccess,
        ar.poRecSaveSessionSelectFileWarning,
        ar.poRecExistingSessionWarningTitle,
        ar.poRecExistingSessionWarningContent('REC-2026-001'),
        ar.poRecUpdateExistingSessionButton,
        ar.poRecSaveSessionError('Timeout'),
        ar.poRecVarianceAlertTitle,
        ar.poRecVarianceAlertContent,
        ar.poRecCancelAndReview,
        ar.poRecConfirmCertifyButton,
        ar.poRecCertificationSuccess,
        ar.poRecCertificationError('Validation failed'),
        ar.poRecSessionLoadedInEditor('REC-2026-001'),
        ar.poRecEditSessionTitle('REC-2026-001'),
        ar.poRecNewSessionTitle,
        ar.poRecOpenSessionBadge('REC-2026-001'),
        ar.poRecHeaderDescription,
        ar.poRecSearchFileHint,
        ar.poRecImportFileLabel,
        ar.poRecSelectFileRequired,
        ar.poRecFinalInvoiceNoLabel,
        ar.poRecFinalInvoiceNoHint,
        ar.poRecFinalPackingListNoLabel,
        ar.poRecFinalPackingListNoHint,
        ar.poRecRequired,
        ar.poRecKpiTotalInvoice,
        ar.poRecKpiTotalPackages,
        ar.poRecKpiTotalGrossWeight,
        ar.poRecKpiTotalNetWeight,
        ar.poRecKpiTotalCbm,
        ar.poRecPackagesUnit,
        ar.poRecKgUnit,
        ar.poRecCbmUnit,
        ar.poRecInvoiceSectionTitle,
        ar.poRecResetToOriginalValuesButton,
        ar.poRecUpdateSessionButton,
        ar.poRecSaveSessionButton,
        ar.poRecCertifyFinalDataButton,
        ar.poRecSelectFileToViewPoItems,
        ar.poRecColItemCode,
        ar.poRecColDescription,
        ar.poRecColPoQty,
        ar.poRecColFinalQty,
        ar.poRecColQtyVariance,
        ar.poRecColPoUnitPrice,
        ar.poRecColFinalUnitPrice,
        ar.poRecColPriceVariance,
        ar.poRecColFinalTotal,
        ar.poRecColHsCode,
        ar.poRecPackingSectionTitle,
        ar.poRecSelectFileToViewPackingItems,
        ar.poRecColPackageType,
        ar.poRecColFinalPackagesCount,
        ar.poRecColGrossWeight,
        ar.poRecColNetWeight,
        ar.poRecColCbm,
        ar.poRecExtractorTitle,
        ar.poRecExtractorSubtitle,
        ar.poRecLoadSampleDemoButton,
        ar.poRecHideTool,
        ar.poRecShowTool,
        ar.poRecExtractorTabInvoice,
        ar.poRecExtractorTabPacking,
        ar.poRecChangeFile,
        ar.poRecUploadFile,
        ar.poRecPasteInvoiceHint,
        ar.poRecPastePackingHint,
        ar.poRecExtractingProgress,
        ar.poRecExecuteSmartExtractionButton,
        ar.poRecStatusFullyMatchedTitle,
        ar.poRecStatusWarningsTitle(3),
        ar.poRecStatusCriticalTitle(1),
        ar.poRecApplyExtractedToTablesButton,
        ar.poRecHeaderComplianceChecksTitle,
        ar.poRecColCheckItem,
        ar.poRecColSystemValue,
        ar.poRecColExtractedValue,
        ar.poRecColMatchStatus,
        ar.poRecColDetails,
        ar.poRecMatchStatusMatched,
        ar.poRecMatchStatusWarning,
        ar.poRecMatchStatusCritical,
        ar.poRecExtractedDocMetadataTitle,
        ar.poRecExtractedInvNo,
        ar.poRecExtractedInvAmount,
        ar.poRecExtractedAcid,
        ar.poRecExtractedPackagesWeight,
        ar.poRecHistorySectionTitle,
        ar.poRecHistorySectionSubtitle,
        ar.poRecHistoryTotalSessionsBadge(5),
        ar.poRecHistoryKpiTotalSessions,
        ar.poRecHistoryKpiFullMatch,
        ar.poRecHistoryKpiWithVariances,
        ar.poRecHistoryKpiTotalCertifiedValue,
        ar.poRecHistoryNewSessionButton,
        ar.poRecHistorySearchHint,
        ar.poRecHistoryFilterAll(10),
        ar.poRecHistoryFilterMatched,
        ar.poRecHistoryFilterWarnings,
        ar.poRecHistoryFilterCritical,
        ar.poRecHistoryRefreshTooltip,
        ar.poRecHistoryEmptyTitle,
        ar.poRecHistoryNoMatchFilter,
        ar.poRecHistoryCreateFirstSessionButton,
        ar.poRecHistoryColIndex,
        ar.poRecHistoryColSessionCode,
        ar.poRecHistoryColImportFileImporter,
        ar.poRecHistoryColInvoicePacking,
        ar.poRecHistoryColTotalValue,
        ar.poRecHistoryColPackagesWeight,
        ar.poRecHistoryColCbm,
        ar.poRecHistoryColStatus,
        ar.poRecHistoryColSavedDate,
        ar.poRecHistoryColActions,
        ar.poRecHistoryCopyCodeTooltip,
        ar.poRecHistoryCodeCopiedNotice,
        ar.poRecHistoryViewDetailsTooltip,
        ar.poRecHistoryLoadIntoEditorTooltip,
        ar.poRecHistoryPrintTooltip,
        ar.poRecHistoryDeleteTooltip,
        ar.poRecHistoryDeleteConfirmTitle,
        ar.poRecHistoryDeleteConfirmContent('REC-001', 'IMP-101'),
        ar.poRecHistoryDeletePermanent,
        ar.poRecHistoryDeletedSuccess('REC-001'),
        ar.poRecHistoryPrintCopiedSuccess,
        ar.poRecHistorySavedDialogTitle('REC-001'),
        ar.poRecHistorySavedUniqueNotice,
        ar.poRecHistoryCopyReportButton,
        ar.poRecHistoryDetailsModalTitle('REC-001'),
        ar.poRecHistoryDetailsCertifiedItemsTitle,
        ar.poRecHistoryLoadInEditorButton,
        ar.poRecDiff,
        ar.poRecMissingInPacking,
        ar.poRecMissingInInvoice,
        ar.poRecQtyDiff,
        ar.poRecOk,
        ar.poRecUnassignedHsCode,
        ar.poRecInvoicePrefix,
        ar.poRecPackingPrefix,
        ar.poRecGrossPrefix,
        ar.poRecCheckFieldInvoiceNumber,
        ar.poRecCheckFieldAcidNumber,
        ar.poRecCheckFieldTotalAmount,
        ar.poRecCheckMsgInvoiceMatched,
        ar.poRecCheckMsgAcidMatched,
        ar.poRecCheckMsgTotalAmountMatched,
        ar.poRecCheckNotSpecified,
        ar.poRecReportTitle,
        ar.poRecReportSessionCode,
        ar.poRecReportImportFile,
        ar.poRecReportImporter,
        ar.poRecReportShipper,
        ar.poRecReportAcid,
        ar.poRecReportInvoiceNo,
        ar.poRecReportPackingNo,
        ar.poRecReportTotalValue,
        ar.poRecReportPackages,
        ar.poRecReportGrossWeight,
        ar.poRecReportNetWeight,
        ar.poRecReportTotalCbm,
        ar.poRecReportOverallStatus,
        ar.poRecReportCertifiedBy,
        ar.poRecReportCsvHeader,
        ar.poRecReportPreviewTitle,
      ];

      final List<String> enStrings = [
        en.poRecSampleLoadedSuccess,
        en.poRecFileSelected('test.pdf', '256'),
        en.poRecFilePickFailed('File error'),
        en.poRecExtractedDigitalFileNotice('sample.xlsx'),
        en.poRecInputValidationTitle,
        en.poRecInputValidationDesc,
        en.poRecInputValidationRecHeader,
        en.poRecInputValidationGotIt,
        en.poRecIssueNoFileSelected,
        en.poRecRecSelectFileFromList,
        en.poRecIssueEmptyInputs,
        en.poRecRecProvideInputs,
        en.poRecServerSuccessNotice,
        en.poRecFallbackSuccessNotice,
        en.poRecApplyExtractedSuccess,
        en.poRecSaveSessionSelectFileWarning,
        en.poRecExistingSessionWarningTitle,
        en.poRecExistingSessionWarningContent('REC-2026-001'),
        en.poRecUpdateExistingSessionButton,
        en.poRecSaveSessionError('Timeout'),
        en.poRecVarianceAlertTitle,
        en.poRecVarianceAlertContent,
        en.poRecCancelAndReview,
        en.poRecConfirmCertifyButton,
        en.poRecCertificationSuccess,
        en.poRecCertificationError('Validation failed'),
        en.poRecSessionLoadedInEditor('REC-2026-001'),
        en.poRecEditSessionTitle('REC-2026-001'),
        en.poRecNewSessionTitle,
        en.poRecOpenSessionBadge('REC-2026-001'),
        en.poRecHeaderDescription,
        en.poRecSearchFileHint,
        en.poRecImportFileLabel,
        en.poRecSelectFileRequired,
        en.poRecFinalInvoiceNoLabel,
        en.poRecFinalInvoiceNoHint,
        en.poRecFinalPackingListNoLabel,
        en.poRecFinalPackingListNoHint,
        en.poRecRequired,
        en.poRecKpiTotalInvoice,
        en.poRecKpiTotalPackages,
        en.poRecKpiTotalGrossWeight,
        en.poRecKpiTotalNetWeight,
        en.poRecKpiTotalCbm,
        en.poRecPackagesUnit,
        en.poRecKgUnit,
        en.poRecCbmUnit,
        en.poRecInvoiceSectionTitle,
        en.poRecResetToOriginalValuesButton,
        en.poRecUpdateSessionButton,
        en.poRecSaveSessionButton,
        en.poRecCertifyFinalDataButton,
        en.poRecSelectFileToViewPoItems,
        en.poRecColItemCode,
        en.poRecColDescription,
        en.poRecColPoQty,
        en.poRecColFinalQty,
        en.poRecColQtyVariance,
        en.poRecColPoUnitPrice,
        en.poRecColFinalUnitPrice,
        en.poRecColPriceVariance,
        en.poRecColFinalTotal,
        en.poRecColHsCode,
        en.poRecPackingSectionTitle,
        en.poRecSelectFileToViewPackingItems,
        en.poRecColPackageType,
        en.poRecColFinalPackagesCount,
        en.poRecColGrossWeight,
        en.poRecColNetWeight,
        en.poRecColCbm,
        en.poRecExtractorTitle,
        en.poRecExtractorSubtitle,
        en.poRecLoadSampleDemoButton,
        en.poRecHideTool,
        en.poRecShowTool,
        en.poRecExtractorTabInvoice,
        en.poRecExtractorTabPacking,
        en.poRecChangeFile,
        en.poRecUploadFile,
        en.poRecPasteInvoiceHint,
        en.poRecPastePackingHint,
        en.poRecExtractingProgress,
        en.poRecExecuteSmartExtractionButton,
        en.poRecStatusFullyMatchedTitle,
        en.poRecStatusWarningsTitle(3),
        en.poRecStatusCriticalTitle(1),
        en.poRecApplyExtractedToTablesButton,
        en.poRecHeaderComplianceChecksTitle,
        en.poRecColCheckItem,
        en.poRecColSystemValue,
        en.poRecColExtractedValue,
        en.poRecColMatchStatus,
        en.poRecColDetails,
        en.poRecMatchStatusMatched,
        en.poRecMatchStatusWarning,
        en.poRecMatchStatusCritical,
        en.poRecExtractedDocMetadataTitle,
        en.poRecExtractedInvNo,
        en.poRecExtractedInvAmount,
        en.poRecExtractedAcid,
        en.poRecExtractedPackagesWeight,
        en.poRecHistorySectionTitle,
        en.poRecHistorySectionSubtitle,
        en.poRecHistoryTotalSessionsBadge(5),
        en.poRecHistoryKpiTotalSessions,
        en.poRecHistoryKpiFullMatch,
        en.poRecHistoryKpiWithVariances,
        en.poRecHistoryKpiTotalCertifiedValue,
        en.poRecHistoryNewSessionButton,
        en.poRecHistorySearchHint,
        en.poRecHistoryFilterAll(10),
        en.poRecHistoryFilterMatched,
        en.poRecHistoryFilterWarnings,
        en.poRecHistoryFilterCritical,
        en.poRecHistoryRefreshTooltip,
        en.poRecHistoryEmptyTitle,
        en.poRecHistoryNoMatchFilter,
        en.poRecHistoryCreateFirstSessionButton,
        en.poRecHistoryColIndex,
        en.poRecHistoryColSessionCode,
        en.poRecHistoryColImportFileImporter,
        en.poRecHistoryColInvoicePacking,
        en.poRecHistoryColTotalValue,
        en.poRecHistoryColPackagesWeight,
        en.poRecHistoryColCbm,
        en.poRecHistoryColStatus,
        en.poRecHistoryColSavedDate,
        en.poRecHistoryColActions,
        en.poRecHistoryCopyCodeTooltip,
        en.poRecHistoryCodeCopiedNotice,
        en.poRecHistoryViewDetailsTooltip,
        en.poRecHistoryLoadIntoEditorTooltip,
        en.poRecHistoryPrintTooltip,
        en.poRecHistoryDeleteTooltip,
        en.poRecHistoryDeleteConfirmTitle,
        en.poRecHistoryDeleteConfirmContent('REC-001', 'IMP-101'),
        en.poRecHistoryDeletePermanent,
        en.poRecHistoryDeletedSuccess('REC-001'),
        en.poRecHistoryPrintCopiedSuccess,
        en.poRecHistorySavedDialogTitle('REC-001'),
        en.poRecHistorySavedUniqueNotice,
        en.poRecHistoryCopyReportButton,
        en.poRecHistoryDetailsModalTitle('REC-001'),
        en.poRecHistoryDetailsCertifiedItemsTitle,
        en.poRecHistoryLoadInEditorButton,
        en.poRecDiff,
        en.poRecMissingInPacking,
        en.poRecMissingInInvoice,
        en.poRecQtyDiff,
        en.poRecOk,
        en.poRecUnassignedHsCode,
        en.poRecInvoicePrefix,
        en.poRecPackingPrefix,
        en.poRecGrossPrefix,
        en.poRecCheckFieldInvoiceNumber,
        en.poRecCheckFieldAcidNumber,
        en.poRecCheckFieldTotalAmount,
        en.poRecCheckMsgInvoiceMatched,
        en.poRecCheckMsgAcidMatched,
        en.poRecCheckMsgTotalAmountMatched,
        en.poRecCheckNotSpecified,
        en.poRecReportTitle,
        en.poRecReportSessionCode,
        en.poRecReportImportFile,
        en.poRecReportImporter,
        en.poRecReportShipper,
        en.poRecReportAcid,
        en.poRecReportInvoiceNo,
        en.poRecReportPackingNo,
        en.poRecReportTotalValue,
        en.poRecReportPackages,
        en.poRecReportGrossWeight,
        en.poRecReportNetWeight,
        en.poRecReportTotalCbm,
        en.poRecReportOverallStatus,
        en.poRecReportCertifiedBy,
        en.poRecReportCsvHeader,
        en.poRecReportPreviewTitle,
      ];

      expect(arStrings.length, enStrings.length);

      for (final s in arStrings) {
        expect(s.trim().isNotEmpty, isTrue, reason: 'Arabic translation string must not be empty');
      }

      for (final s in enStrings) {
        expect(s.trim().isNotEmpty, isTrue, reason: 'English translation string must not be empty');
      }
    });

    test('Translations should not have stacked bilingual text or slash dual language formatting', () {
      final List<String> labels = [
        ar.poRecInvoiceSectionTitle,
        en.poRecInvoiceSectionTitle,
        ar.poRecPackingSectionTitle,
        en.poRecPackingSectionTitle,
        ar.poRecExtractorTitle,
        en.poRecExtractorTitle,
        ar.poRecHistorySectionTitle,
        en.poRecHistorySectionTitle,
        ar.poRecRecProvideInputs,
        ar.poRecFinalInvoiceNoHint,
        ar.poRecFinalPackingListNoHint,
        ar.poRecKpiTotalCbm,
        ar.poRecColHsCode,
        ar.poRecUploadFile,
        ar.poRecHistoryColImportFileImporter,
        ar.poRecHistoryColCbm,
        ar.poRecReportTitle,
        ar.poRecReportPreviewTitle,
      ];

      for (final label in labels) {
        expect(label.contains(' / '), isFalse, reason: 'Labels should not contain dual stacked format " / ": $label');
      }
    });

    test('Clean single-locale integrity: Arabic strings must not contain raw English acronyms or slashes', () {
      expect(ar.poRecKpiTotalCbm.contains('(CBM)'), isFalse);
      expect(ar.poRecColHsCode.contains('(HS)'), isFalse);
      expect(ar.poRecUploadFile.contains('(PDF/Word/Excel)'), isFalse);
      expect(ar.poRecHistoryColImportFileImporter.contains('/'), isFalse);
      expect(ar.poRecHistoryColCbm.contains('(CBM)'), isFalse);
    });

    test('Task C Linked Output Report strings should be complete, valid, and localized', () {
      expect(ar.poRecReportTitle, contains('نظام سرور للخدمات اللوجستية'));
      expect(en.poRecReportTitle, contains('Sorour Logistics ERP'));
      expect(ar.poRecReportCsvHeader, contains('كود الصنف'));
      expect(en.poRecReportCsvHeader, contains('Item Code'));
      expect(ar.poRecInvoicePrefix, isNotEmpty);
      expect(en.poRecInvoicePrefix, isNotEmpty);
      expect(ar.poRecPackingPrefix, isNotEmpty);
      expect(en.poRecPackingPrefix, isNotEmpty);
      expect(ar.poRecGrossPrefix, isNotEmpty);
      expect(en.poRecGrossPrefix, isNotEmpty);
    });
  });
}

