import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/core/localization/app_localizations.dart';
import 'package:frontend/core/localization/app_localizations_ar.dart';
import 'package:frontend/core/localization/app_localizations_en.dart';

void main() {
  group('Screen 31: Projects & Cost Centers Localization Tests', () {
    const AppLocalizations ar = AppLocalizationsAr();
    const AppLocalizations en = AppLocalizationsEn();

    test('All Screen 31 getters should have non-empty Arabic and English translations', () {
      final List<String> arStrings = [
        ar.projectsScreenTitle,
        ar.projectsScreenSubtitle,
        ar.createNewProjectBtn,
        ar.projectsSearchHint,
        ar.projectsFetchError('Connection timed out'),
        ar.noProjectsFound,
        ar.projectCodeCol,
        ar.projectNameAndOwnerCol,
        ar.companyAndSupplierCol,
        ar.typeAndCategoryCol,
        ar.budgetUsdCol,
        ar.capabilitiesCol,
        ar.projectOwnerLabel('Eng. Mahmoud'),
        ar.projectCompanyFallback(1),
        ar.projectSupplierFallback(2),
        ar.projectSupplierLabel('Supplier X'),
        ar.capMultiShipment,
        ar.capMultiCompany,
        ar.projectPrintSnack('Project A', 'PRJ-001'),
        ar.confirmActionTitle,
        ar.confirmDeactivateProject('Project A'),
        ar.confirmActivateProject('Project A'),
        ar.deactivateBtn,
        ar.activateBtn,
        ar.deactivateProjectTooltip,
        ar.activateProjectTooltip,
        ar.createProjectDialogTitle,
        ar.editProjectDialogTitle('PRJ-001'),
        ar.projectPrerequisitesMissing,
        ar.projectNameLabel,
        ar.projectNameHint,
        ar.projectOwnerLabelField,
        ar.projectOwnerHint,
        ar.importingCompaniesFieldLabel,
        ar.primarySupplierLabel,
        ar.defaultIncotermLabel,
        ar.importTypeLabel,
        ar.priorityLabel,
        ar.projectStatusLabel,
        ar.allowedShipmentCategoriesLabel,
        ar.estTotalBudgetUsdLabel,
        ar.estTotalBudgetUsdHint,
        ar.allowMultiShipmentTitle,
        ar.allowMultiShipmentSubtitle,
        ar.allowMultiCompanyTitle,
        ar.allowMultiCompanySubtitle,
        ar.projectNotesLabel,
        ar.selectAtLeastOneCompanyError,
        ar.selectAtLeastOneCategoryError,
        ar.createProjectSubmitBtn,
        ar.saveChangesSubmitBtn,
        ar.statusOnHold,
        ar.priorityUrgent,
        ar.importTypeDirectCommercial,
        ar.importTypeFreeZone,
        ar.importTypeTemporaryRelease,
        ar.importTypeDrawback,
        ar.importTypeProjectEquipment,
        ar.categoryFclContainer,
        ar.categoryLclBreakbulk,
        ar.categoryAirFreight,
        ar.categoryBulkCargo,
        ar.categoryMultimodal,
      ];

      final List<String> enStrings = [
        en.projectsScreenTitle,
        en.projectsScreenSubtitle,
        en.createNewProjectBtn,
        en.projectsSearchHint,
        en.projectsFetchError('Connection timed out'),
        en.noProjectsFound,
        en.projectCodeCol,
        en.projectNameAndOwnerCol,
        en.companyAndSupplierCol,
        en.typeAndCategoryCol,
        en.budgetUsdCol,
        en.capabilitiesCol,
        en.projectOwnerLabel('Eng. Mahmoud'),
        en.projectCompanyFallback(1),
        en.projectSupplierFallback(2),
        en.projectSupplierLabel('Supplier X'),
        en.capMultiShipment,
        en.capMultiCompany,
        en.projectPrintSnack('Project A', 'PRJ-001'),
        en.confirmActionTitle,
        en.confirmDeactivateProject('Project A'),
        en.confirmActivateProject('Project A'),
        en.deactivateBtn,
        en.activateBtn,
        en.deactivateProjectTooltip,
        en.activateProjectTooltip,
        en.createProjectDialogTitle,
        en.editProjectDialogTitle('PRJ-001'),
        en.projectPrerequisitesMissing,
        en.projectNameLabel,
        en.projectNameHint,
        en.projectOwnerLabelField,
        en.projectOwnerHint,
        en.importingCompaniesFieldLabel,
        en.primarySupplierLabel,
        en.defaultIncotermLabel,
        en.importTypeLabel,
        en.priorityLabel,
        en.projectStatusLabel,
        en.allowedShipmentCategoriesLabel,
        en.estTotalBudgetUsdLabel,
        en.estTotalBudgetUsdHint,
        en.allowMultiShipmentTitle,
        en.allowMultiShipmentSubtitle,
        en.allowMultiCompanyTitle,
        en.allowMultiCompanySubtitle,
        en.projectNotesLabel,
        en.selectAtLeastOneCompanyError,
        en.selectAtLeastOneCategoryError,
        en.createProjectSubmitBtn,
        en.saveChangesSubmitBtn,
        en.statusOnHold,
        en.priorityUrgent,
        en.importTypeDirectCommercial,
        en.importTypeFreeZone,
        en.importTypeTemporaryRelease,
        en.importTypeDrawback,
        en.importTypeProjectEquipment,
        en.categoryFclContainer,
        en.categoryLclBreakbulk,
        en.categoryAirFreight,
        en.categoryBulkCargo,
        en.categoryMultimodal,
      ];

      expect(arStrings.length, enStrings.length);
      for (int i = 0; i < arStrings.length; i++) {
        expect(arStrings[i].trim().isNotEmpty, isTrue, reason: 'Arabic string at index $i is empty');
        expect(enStrings[i].trim().isNotEmpty, isTrue, reason: 'English string at index $i is empty');
      }
    });

    test('Verify pure Arabic translations without stacked or Latin characters in static keys', () {
      final List<String> arStaticStrings = [
        ar.projectsScreenTitle,
        ar.projectsScreenSubtitle,
        ar.createNewProjectBtn,
        ar.projectsSearchHint,
        ar.noProjectsFound,
        ar.projectCodeCol,
        ar.projectNameAndOwnerCol,
        ar.companyAndSupplierCol,
        ar.typeAndCategoryCol,
        ar.capabilitiesCol,
        ar.capMultiShipment,
        ar.capMultiCompany,
        ar.confirmActionTitle,
        ar.deactivateBtn,
        ar.activateBtn,
        ar.deactivateProjectTooltip,
        ar.activateProjectTooltip,
        ar.createProjectDialogTitle,
        ar.projectPrerequisitesMissing,
        ar.projectNameLabel,
        ar.projectOwnerLabelField,
        ar.importingCompaniesFieldLabel,
        ar.primarySupplierLabel,
        ar.importTypeLabel,
        ar.priorityLabel,
        ar.projectStatusLabel,
        ar.allowedShipmentCategoriesLabel,
        ar.allowMultiShipmentSubtitle,
        ar.allowMultiCompanySubtitle,
        ar.projectNotesLabel,
        ar.selectAtLeastOneCompanyError,
        ar.selectAtLeastOneCategoryError,
        ar.createProjectSubmitBtn,
        ar.saveChangesSubmitBtn,
        ar.statusOnHold,
        ar.priorityUrgent,
        ar.importTypeDirectCommercial,
        ar.importTypeFreeZone,
        ar.importTypeTemporaryRelease,
        ar.importTypeDrawback,
        ar.importTypeProjectEquipment,
        ar.categoryAirFreight,
      ];

      for (final s in arStaticStrings) {
        expect(RegExp(r'[a-zA-Z]').hasMatch(s), isFalse, reason: 'Arabic string contains Latin characters: $s');
      }
    });
  });
}
