import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/core/localization/app_localizations.dart';
import 'package:frontend/core/localization/app_localizations_ar.dart';
import 'package:frontend/core/localization/app_localizations_en.dart';

void main() {
  group('Screen 33: Foreign Suppliers Localization Tests', () {
    const AppLocalizations ar = AppLocalizationsAr();
    const AppLocalizations en = AppLocalizationsEn();

    test('All Screen 33 getters should have non-empty Arabic and English translations', () {
      final List<String> arStrings = [
        ar.suppliersScreenTitle,
        ar.suppliersScreenSubtitle,
        ar.aiExtractorAndCodingBtn,
        ar.addForeignSupplierBtn,
        ar.searchSuppliersHint,
        ar.showInactiveSuppliersLabel,
        ar.suppliersFetchError('Connection timeout'),
        ar.noSuppliersFound,
        ar.supplierRowMeta('EXP-CN-123', 'CX-456', 'Via Roma 1', 'BrandX'),
        ar.supplierTypeAndReg('Manufacturer', 'Factory Registration'),
        ar.confirmDeactivateSupplier('Acme Corp'),
        ar.confirmActivateSupplier('Acme Corp'),
        ar.deactivateSupplierTooltip,
        ar.activateSupplierTooltip,
        ar.editSupplierDialogTitle,
        ar.addSupplierDialogTitle,
        ar.supplierCompanyNameLabel,
        ar.supplierCompanyNameHint,
        ar.supplierTypeLabel,
        ar.supplierTypeManufacturer,
        ar.supplierTypeTrader,
        ar.supplierTypeAgent,
        ar.supplierTypeExporter,
        ar.supplierRegTypeLabel,
        ar.regTypeFactory,
        ar.regTypeNafezaExporter,
        ar.regTypeCompanyReg,
        ar.regTypeVat,
        ar.regTypeTax,
        ar.regTypeCommercial,
        ar.supplierForeignExporterIdLabel,
        ar.foreignExporterIdHint,
        ar.cargoxIdLabel,
        ar.cargoxIdHint,
        ar.supplierCountryLabel,
        ar.supplierCountryHint,
        ar.supplierCountryCodeLabel,
        ar.supplierCountryCodeHint,
        ar.supplierAddressLabel,
        ar.supplierAddressHint,
        ar.supplierEmailLabel,
        ar.supplierEmailHint,
        ar.supplierSecondaryEmailLabel,
        ar.supplierSecondaryEmailHint,
        ar.supplierPhoneLabel,
        ar.supplierPhoneHint,
        ar.supplierMobileLabel,
        ar.supplierMobileHint,
        ar.supplierFaxLabel,
        ar.supplierFaxHint,
        ar.supplierWebsiteLabel,
        ar.supplierWebsiteHint,
        ar.beneficiaryBankDetailsHeader,
        ar.beneficiaryBankNameLabel,
        ar.beneficiaryBankNameHint,
        ar.beneficiarySwiftCodeLabel,
        ar.beneficiarySwiftCodeHint,
        ar.beneficiaryAccountNumberLabel,
        ar.beneficiaryAccountNumberHint,
        ar.beneficiaryIbanLabel,
        ar.beneficiaryIbanHint,
        ar.complianceAndCertsHeader,
        ar.isoCertifiedCheck,
        ar.decree43Check,
        ar.whiteListCheck,
        ar.brandsProductLinesLabel,
        ar.brandsProductLinesHint,
        ar.supplierNotesLabel,
        ar.supplierNotesHint,
        ar.updateSupplierBtn,
        ar.saveSupplierBtn,
        ar.diffSupplierCompanyName,
        ar.diffSupplierType,
        ar.diffSupplierRegType,
        ar.diffForeignExporterId,
        ar.diffCargoXId,
        ar.diffSupplierCountry,
        ar.diffSupplierEmail,
        ar.diffSupplierPhone,
        ar.diffConfirmSupplierTitle,
        ar.supplierProfileSubtitle,
        ar.nafezaCargoXComplianceHeader,
        ar.foreignExporterIdFieldLabel,
        ar.cargoxPlatformIdFieldLabel,
        ar.notRegisteredCargoX,
        ar.supplierTypeFieldLabel,
        ar.supplierOriginCountryFieldLabel,
        ar.complianceCertificatesLabel,
        ar.isoCertifiedTag,
        ar.decree43Tag,
        ar.whiteListTag,
        ar.bankingSwiftSectionHeader,
        ar.beneficiaryBankFieldLabel,
        ar.swiftCodeFieldLabel,
        ar.accountNumberFieldLabel,
        ar.ibanFieldLabel,
        ar.contactAddressBrandsHeader,
        ar.fullAddressFieldLabel,
        ar.phoneFieldLabel,
        ar.emailFieldLabel,
        ar.websiteFieldLabel,
        ar.brandsFieldLabel,
        ar.additionalNotesHeader,
      ];

      final List<String> enStrings = [
        en.suppliersScreenTitle,
        en.suppliersScreenSubtitle,
        en.aiExtractorAndCodingBtn,
        en.addForeignSupplierBtn,
        en.searchSuppliersHint,
        en.showInactiveSuppliersLabel,
        en.suppliersFetchError('Connection timeout'),
        en.noSuppliersFound,
        en.supplierRowMeta('EXP-CN-123', 'CX-456', 'Via Roma 1', 'BrandX'),
        en.supplierTypeAndReg('Manufacturer', 'Factory Registration'),
        en.confirmDeactivateSupplier('Acme Corp'),
        en.confirmActivateSupplier('Acme Corp'),
        en.deactivateSupplierTooltip,
        en.activateSupplierTooltip,
        en.editSupplierDialogTitle,
        en.addSupplierDialogTitle,
        en.supplierCompanyNameLabel,
        en.supplierCompanyNameHint,
        en.supplierTypeLabel,
        en.supplierTypeManufacturer,
        en.supplierTypeTrader,
        en.supplierTypeAgent,
        en.supplierTypeExporter,
        en.supplierRegTypeLabel,
        en.regTypeFactory,
        en.regTypeNafezaExporter,
        en.regTypeCompanyReg,
        en.regTypeVat,
        en.regTypeTax,
        en.regTypeCommercial,
        en.supplierForeignExporterIdLabel,
        en.foreignExporterIdHint,
        en.cargoxIdLabel,
        en.cargoxIdHint,
        en.supplierCountryLabel,
        en.supplierCountryHint,
        en.supplierCountryCodeLabel,
        en.supplierCountryCodeHint,
        en.supplierAddressLabel,
        en.supplierAddressHint,
        en.supplierEmailLabel,
        en.supplierEmailHint,
        en.supplierSecondaryEmailLabel,
        en.supplierSecondaryEmailHint,
        en.supplierPhoneLabel,
        en.supplierPhoneHint,
        en.supplierMobileLabel,
        en.supplierMobileHint,
        en.supplierFaxLabel,
        en.supplierFaxHint,
        en.supplierWebsiteLabel,
        en.supplierWebsiteHint,
        en.beneficiaryBankDetailsHeader,
        en.beneficiaryBankNameLabel,
        en.beneficiaryBankNameHint,
        en.beneficiarySwiftCodeLabel,
        en.beneficiarySwiftCodeHint,
        en.beneficiaryAccountNumberLabel,
        en.beneficiaryAccountNumberHint,
        en.beneficiaryIbanLabel,
        en.beneficiaryIbanHint,
        en.complianceAndCertsHeader,
        en.isoCertifiedCheck,
        en.decree43Check,
        en.whiteListCheck,
        en.brandsProductLinesLabel,
        en.brandsProductLinesHint,
        en.supplierNotesLabel,
        en.supplierNotesHint,
        en.updateSupplierBtn,
        en.saveSupplierBtn,
        en.diffSupplierCompanyName,
        en.diffSupplierType,
        en.diffSupplierRegType,
        en.diffForeignExporterId,
        en.diffCargoXId,
        en.diffSupplierCountry,
        en.diffSupplierEmail,
        en.diffSupplierPhone,
        en.diffConfirmSupplierTitle,
        en.supplierProfileSubtitle,
        en.nafezaCargoXComplianceHeader,
        en.foreignExporterIdFieldLabel,
        en.cargoxPlatformIdFieldLabel,
        en.notRegisteredCargoX,
        en.supplierTypeFieldLabel,
        en.supplierOriginCountryFieldLabel,
        en.complianceCertificatesLabel,
        en.isoCertifiedTag,
        en.decree43Tag,
        en.whiteListTag,
        en.bankingSwiftSectionHeader,
        en.beneficiaryBankFieldLabel,
        en.swiftCodeFieldLabel,
        en.accountNumberFieldLabel,
        en.ibanFieldLabel,
        en.contactAddressBrandsHeader,
        en.fullAddressFieldLabel,
        en.phoneFieldLabel,
        en.emailFieldLabel,
        en.websiteFieldLabel,
        en.brandsFieldLabel,
        en.additionalNotesHeader,
      ];

      expect(arStrings.length, enStrings.length);
      for (int i = 0; i < arStrings.length; i++) {
        expect(arStrings[i].trim().isNotEmpty, isTrue, reason: 'Arabic string at index $i is empty');
        expect(enStrings[i].trim().isNotEmpty, isTrue, reason: 'English string at index $i is empty');
      }
    });

    test('Verify pure Arabic translations without stacked or Latin characters in static keys', () {
      final List<String> arStaticStrings = [
        ar.suppliersScreenTitle,
        ar.suppliersScreenSubtitle,
        ar.addForeignSupplierBtn,
        ar.searchSuppliersHint,
        ar.showInactiveSuppliersLabel,
        ar.noSuppliersFound,
        ar.deactivateSupplierTooltip,
        ar.activateSupplierTooltip,
        ar.editSupplierDialogTitle,
        ar.addSupplierDialogTitle,
        ar.supplierCompanyNameLabel,
        ar.supplierTypeLabel,
        ar.supplierRegTypeLabel,
        ar.supplierCountryLabel,
        ar.supplierAddressLabel,
        ar.supplierEmailLabel,
        ar.supplierSecondaryEmailLabel,
        ar.supplierPhoneLabel,
        ar.supplierMobileLabel,
        ar.supplierFaxLabel,
        ar.supplierWebsiteLabel,
        ar.beneficiaryBankDetailsHeader,
        ar.beneficiaryBankNameLabel,
        ar.beneficiaryAccountNumberLabel,
        ar.complianceAndCertsHeader,
        ar.brandsProductLinesLabel,
        ar.supplierNotesLabel,
        ar.updateSupplierBtn,
        ar.saveSupplierBtn,
        ar.diffSupplierCompanyName,
        ar.diffSupplierType,
        ar.diffSupplierRegType,
        ar.diffSupplierCountry,
        ar.diffSupplierEmail,
        ar.diffSupplierPhone,
        ar.diffConfirmSupplierTitle,
        ar.supplierProfileSubtitle,
        ar.nafezaCargoXComplianceHeader,
        ar.notRegisteredCargoX,
        ar.supplierTypeFieldLabel,
        ar.supplierOriginCountryFieldLabel,
        ar.complianceCertificatesLabel,
        ar.isoCertifiedTag,
        ar.decree43Tag,
        ar.whiteListTag,
        ar.bankingSwiftSectionHeader,
        ar.beneficiaryBankFieldLabel,
        ar.swiftCodeFieldLabel,
        ar.accountNumberFieldLabel,
        ar.contactAddressBrandsHeader,
        ar.fullAddressFieldLabel,
        ar.phoneFieldLabel,
        ar.emailFieldLabel,
        ar.websiteFieldLabel,
        ar.brandsFieldLabel,
        ar.additionalNotesHeader,
      ];

      for (final s in arStaticStrings) {
        expect(RegExp(r'[a-zA-Z]').hasMatch(s), isFalse, reason: 'Arabic string contains Latin characters: $s');
      }
    });
  });
}
