import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/core/localization/app_localizations.dart';
import 'package:frontend/core/localization/app_localizations_ar.dart';
import 'package:frontend/core/localization/app_localizations_en.dart';

void main() {
  group('Screen 28: Warehouse Receiving & Inspection (GRN) Localization Tests', () {
    const AppLocalizations ar = AppLocalizationsAr();
    const AppLocalizations en = AppLocalizationsEn();

    test('All Screen 28 getters should have non-empty Arabic and English translations', () {
      final List<String> arStrings = [
        ar.warehouseReceivingStageTitle,
        ar.warehouseReceivingTabRegistry,
        ar.warehouseReceivingTabNewEntry,
        ar.warehouseReceivingRefreshTooltip,
        ar.warehouseReceivingNewGrnBtn,
        ar.warehouseReceivingSearchHint,
        ar.warehouseReceivingStatusAll,
        ar.warehouseReceivingStatusDraft,
        ar.warehouseReceivingStatusGoodsReceived,
        ar.warehouseReceivingStatusDiscrepancy,
        ar.warehouseReceivingEmptyRecords,
        ar.warehouseReceivingTruckAndDriver,
        ar.warehouseReceivingArrivalDatetime,
        ar.warehouseReceivingInspector,
        ar.warehouseReceivingDiscrepancyStatus,
        ar.warehouseReceivingMetricInvoiced,
        ar.warehouseReceivingMetricAccepted,
        ar.warehouseReceivingMetricShortage,
        ar.warehouseReceivingMetricDamaged,
        ar.warehouseReceivingConfirmFinalReceiptBtn,
        ar.warehouseReceivingRecordDiscrepancyBtn,
        ar.warehouseReceivingPrintGrnSnack('GRN-2026-001', 'Main WH'),
        ar.warehouseReceivingDeleteTitle,
        ar.warehouseReceivingDeleteConfirmMessage,
        ar.warehouseReceivingViewTooltip,
        ar.warehouseReceivingEditTooltip,
        ar.warehouseReceivingPrintTooltip,
        ar.warehouseReceivingDeleteTooltip,
        ar.warehouseReceivingSealIntact,
        ar.warehouseReceivingSealBroken,
        ar.warehouseReceivingConfirmReceiptTitle,
        ar.warehouseReceivingConfirmReceiptMessage('GRN-2026-001'),
        ar.warehouseReceivingConfirmReceiptBtn,
        ar.warehouseReceivingConfirmReceiptSuccess('GRN-2026-001'),
        ar.warehouseReceivingConfirmReceiptError('Connection timeout'),
        ar.warehouseReceivingNewDialogTitle,
        ar.warehouseReceivingEditDialogTitle,
        ar.warehouseReceivingDispatchAlertTitle,
        ar.warehouseReceivingDispatchAlertDesc,
        ar.warehouseReceivingDispatchSentBtn,
        ar.warehouseReceivingDispatchSendBtn,
        ar.warehouseReceivingDispatchSuccessSnack,
        ar.warehouseReceivingImportFileLabel,
        ar.warehouseReceivingSelectFileValidator,
        ar.warehouseReceivingWarehouseNameLabel,
        ar.warehouseReceivingWarehouseNameValidator,
        ar.warehouseReceivingTruckPlateLabel,
        ar.warehouseReceivingDriverNameLabel,
        ar.warehouseReceivingSealNumberLabel,
        ar.warehouseReceivingSealIntactSwitch,
        ar.warehouseReceivingMultiPoHeader,
        ar.warehouseReceivingAddItemBtn,
        ar.warehouseReceivingPoLabel('PO-2026-001'),
        ar.warehouseReceivingItemNameLabel,
        ar.warehouseReceivingInvoicedQtyLabel,
        ar.warehouseReceivingAcceptedQtyLabel,
        ar.warehouseReceivingShortageQtyLabel,
        ar.warehouseReceivingDamagedQtyLabel,
        ar.warehouseReceivingSamplesQtyLabel,
        ar.warehouseReceivingSaveDraftBtn,
        ar.warehouseReceivingSaveFinalBtn,
        ar.warehouseReceivingDraftSuccessSnack,
        ar.warehouseReceivingFinalSuccessSnack,
        ar.warehouseReceivingDiscrepancyDialogTitle('GRN-2026-001'),
        ar.warehouseReceivingDiscrepancyTypeLabel,
        ar.warehouseReceivingDiscrepancyTypeShortageAndDamage,
        ar.warehouseReceivingDiscrepancyTypeShortageOnly,
        ar.warehouseReceivingDiscrepancyTypeDamageOnly,
        ar.warehouseReceivingDiscrepancyTypeBrokenSeal,
        ar.warehouseReceivingDiscrepancyNotesLabel,
        ar.warehouseReceivingDiscrepancyNotesValidator,
        ar.warehouseReceivingQuarantineSwitch,
        ar.warehouseReceivingInsuranceClaimSwitch,
        ar.warehouseReceivingClaimRefLabel,
        ar.warehouseReceivingCertifyDiscrepancyBtn,
        ar.warehouseReceivingDiscrepancySuccessSnack,
      ];

      final List<String> enStrings = [
        en.warehouseReceivingStageTitle,
        en.warehouseReceivingTabRegistry,
        en.warehouseReceivingTabNewEntry,
        en.warehouseReceivingRefreshTooltip,
        en.warehouseReceivingNewGrnBtn,
        en.warehouseReceivingSearchHint,
        en.warehouseReceivingStatusAll,
        en.warehouseReceivingStatusDraft,
        en.warehouseReceivingStatusGoodsReceived,
        en.warehouseReceivingStatusDiscrepancy,
        en.warehouseReceivingEmptyRecords,
        en.warehouseReceivingTruckAndDriver,
        en.warehouseReceivingArrivalDatetime,
        en.warehouseReceivingInspector,
        en.warehouseReceivingDiscrepancyStatus,
        en.warehouseReceivingMetricInvoiced,
        en.warehouseReceivingMetricAccepted,
        en.warehouseReceivingMetricShortage,
        en.warehouseReceivingMetricDamaged,
        en.warehouseReceivingConfirmFinalReceiptBtn,
        en.warehouseReceivingRecordDiscrepancyBtn,
        en.warehouseReceivingPrintGrnSnack('GRN-2026-001', 'Main WH'),
        en.warehouseReceivingDeleteTitle,
        en.warehouseReceivingDeleteConfirmMessage,
        en.warehouseReceivingViewTooltip,
        en.warehouseReceivingEditTooltip,
        en.warehouseReceivingPrintTooltip,
        en.warehouseReceivingDeleteTooltip,
        en.warehouseReceivingSealIntact,
        en.warehouseReceivingSealBroken,
        en.warehouseReceivingConfirmReceiptTitle,
        en.warehouseReceivingConfirmReceiptMessage('GRN-2026-001'),
        en.warehouseReceivingConfirmReceiptBtn,
        en.warehouseReceivingConfirmReceiptSuccess('GRN-2026-001'),
        en.warehouseReceivingConfirmReceiptError('Connection timeout'),
        en.warehouseReceivingNewDialogTitle,
        en.warehouseReceivingEditDialogTitle,
        en.warehouseReceivingDispatchAlertTitle,
        en.warehouseReceivingDispatchAlertDesc,
        en.warehouseReceivingDispatchSentBtn,
        en.warehouseReceivingDispatchSendBtn,
        en.warehouseReceivingDispatchSuccessSnack,
        en.warehouseReceivingImportFileLabel,
        en.warehouseReceivingSelectFileValidator,
        en.warehouseReceivingWarehouseNameLabel,
        en.warehouseReceivingWarehouseNameValidator,
        en.warehouseReceivingTruckPlateLabel,
        en.warehouseReceivingDriverNameLabel,
        en.warehouseReceivingSealNumberLabel,
        en.warehouseReceivingSealIntactSwitch,
        en.warehouseReceivingMultiPoHeader,
        en.warehouseReceivingAddItemBtn,
        en.warehouseReceivingPoLabel('PO-2026-001'),
        en.warehouseReceivingItemNameLabel,
        en.warehouseReceivingInvoicedQtyLabel,
        en.warehouseReceivingAcceptedQtyLabel,
        en.warehouseReceivingShortageQtyLabel,
        en.warehouseReceivingDamagedQtyLabel,
        en.warehouseReceivingSamplesQtyLabel,
        en.warehouseReceivingSaveDraftBtn,
        en.warehouseReceivingSaveFinalBtn,
        en.warehouseReceivingDraftSuccessSnack,
        en.warehouseReceivingFinalSuccessSnack,
        en.warehouseReceivingDiscrepancyDialogTitle('GRN-2026-001'),
        en.warehouseReceivingDiscrepancyTypeLabel,
        en.warehouseReceivingDiscrepancyTypeShortageAndDamage,
        en.warehouseReceivingDiscrepancyTypeShortageOnly,
        en.warehouseReceivingDiscrepancyTypeDamageOnly,
        en.warehouseReceivingDiscrepancyTypeBrokenSeal,
        en.warehouseReceivingDiscrepancyNotesLabel,
        en.warehouseReceivingDiscrepancyNotesValidator,
        en.warehouseReceivingQuarantineSwitch,
        en.warehouseReceivingInsuranceClaimSwitch,
        en.warehouseReceivingClaimRefLabel,
        en.warehouseReceivingCertifyDiscrepancyBtn,
        en.warehouseReceivingDiscrepancySuccessSnack,
      ];

      expect(arStrings.length, enStrings.length);
      for (int i = 0; i < arStrings.length; i++) {
        expect(arStrings[i].trim().isNotEmpty, isTrue, reason: 'Arabic string at index $i is empty');
        expect(enStrings[i].trim().isNotEmpty, isTrue, reason: 'English string at index $i is empty');
      }
    });

    test('Verify pure localized texts without stacked bilingual patterns', () {
      final List<String> arStrings = [
        ar.warehouseReceivingStageTitle,
        ar.warehouseReceivingTabRegistry,
        ar.warehouseReceivingTabNewEntry,
        ar.warehouseReceivingNewGrnBtn,
        ar.warehouseReceivingStatusDraft,
        ar.warehouseReceivingStatusGoodsReceived,
        ar.warehouseReceivingStatusDiscrepancy,
        ar.warehouseReceivingSealIntact,
        ar.warehouseReceivingSealBroken,
        ar.warehouseReceivingDispatchAlertTitle,
        ar.warehouseReceivingMultiPoHeader,
        ar.warehouseReceivingDiscrepancyTypeShortageAndDamage,
        ar.warehouseReceivingDiscrepancyTypeShortageOnly,
        ar.warehouseReceivingDiscrepancyTypeDamageOnly,
        ar.warehouseReceivingDiscrepancyTypeBrokenSeal,
        ar.warehouseReceivingQuarantineSwitch,
        ar.warehouseReceivingInsuranceClaimSwitch,
      ];

      for (final s in arStrings) {
        expect(RegExp(r'[a-zA-Z]').hasMatch(s), isFalse, reason: 'Arabic string contains English Latin text: $s');
      }
    });
  });
}
