"""sync_all_module_models

Revision ID: 4e8d5e046be7
Revises: 627c866a1010
Create Date: 2026-08-18 20:49:36.537613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8d5e046be7'
down_revision: Union[str, Sequence[str], None] = '627c866a1010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acid_registration_sessions', schema=None) as batch_op:
        batch_op.alter_column('has_discrepancies',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('ix_acid_registration_sessions_acid_number'))
        batch_op.create_index(batch_op.f('ix_acid_registration_sessions_acid_number'), ['acid_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_acid_registration_sessions_customs_broker_id'), ['customs_broker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_acid_registration_sessions_import_file_id'), ['import_file_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_acid_registration_sessions_customs_broker_id_external_service_providers'), 'external_service_providers', ['customs_broker_id'], ['provider_id'])

    with op.batch_alter_table('banking_document_sessions', schema=None) as batch_op:
        batch_op.alter_column('request_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('execution_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_index(batch_op.f('ix_banking_document_sessions_import_file_id'), ['import_file_id'], unique=False)

    with op.batch_alter_table('cargo_shipping_records', schema=None) as batch_op:
        batch_op.alter_column('shipment_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'FCL'"))

    with op.batch_alter_table('cbm_calculations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cbm_calculations_import_file_id'), ['import_file_id'], unique=False)

    with op.batch_alter_table('customs_consultation_sessions', schema=None) as batch_op:
        batch_op.alter_column('total_broker_fees_egp',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.create_index(batch_op.f('ix_customs_consultation_sessions_import_file_id'), ['import_file_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_customs_consultation_sessions_broker_price_list_id_broker_price_lists'), 'broker_price_lists', ['broker_price_list_id'], ['price_list_id'])

    with op.batch_alter_table('customs_declaration_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customs_declaration_drafts_import_file_id'), ['import_file_id'], unique=False)

    with op.batch_alter_table('external_service_providers', schema=None) as batch_op:
        batch_op.alter_column('partner_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('freight_rfq_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_freight_rfq_requests_import_file_id'), ['import_file_id'], unique=False)

    with op.batch_alter_table('import_budget_approvals', schema=None) as batch_op:
        batch_op.alter_column('invoice_amount_foreign',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('invoice_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('freight_cost_foreign',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('freight_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('exchange_rate',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(50.0)'))
        batch_op.create_index(batch_op.f('ix_import_budget_approvals_import_file_id'), ['import_file_id'], unique=False)

    with op.batch_alter_table('import_companies', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_import_companies_importer_id'), ['importer_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_import_companies_registration_number'), ['registration_number'])
        batch_op.create_unique_constraint(batch_op.f('uq_import_companies_vat_id'), ['vat_id'])

    with op.batch_alter_table('import_files', schema=None) as batch_op:
        batch_op.alter_column('is_customs_released',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('estimated_cost_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.drop_index(batch_op.f('ix_import_files_company_id'))
        batch_op.drop_index(batch_op.f('ix_import_files_current_stage'))
        batch_op.drop_index(batch_op.f('ix_import_files_is_active'))
        batch_op.drop_index(batch_op.f('ix_import_files_status'))
        batch_op.drop_index(batch_op.f('ix_import_files_supplier_id'))
        batch_op.create_index(batch_op.f('ix_import_files_custom_file_number'), ['custom_file_number'], unique=True)
        batch_op.create_foreign_key(batch_op.f('fk_import_files_broker_id_external_service_providers'), 'external_service_providers', ['broker_id'], ['provider_id'])

    with op.batch_alter_table('import_requirement_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hs_code_items', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('sailing_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sailing_date', sa.String(length=50), nullable=True))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('shipment_value',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('white_list_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('coa_required',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('coa_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Not Required'"))
        batch_op.alter_column('confirmation_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Pending Confirmation'"))
        batch_op.alter_column('is_post_acid_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_unique_constraint(batch_op.f('uq_import_requirement_assessments_assessment_code'), ['assessment_code'])
        batch_op.create_foreign_key(batch_op.f('fk_import_requirement_assessments_supplier_id_suppliers'), 'suppliers', ['supplier_id'], ['supplier_id'])
        batch_op.create_foreign_key(batch_op.f('fk_import_requirement_assessments_consultation_id_customs_consultation_sessions'), 'customs_consultation_sessions', ['consultation_id'], ['consultation_id'])

    with op.batch_alter_table('payment_request_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_request_sessions_import_file_id'), ['import_file_id'], unique=False)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_import_file_id'), ['import_file_id'], unique=False)

    with op.batch_alter_table('shipment_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_bookings_scenario_item_id'), ['scenario_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_bookings_scenario_session_id'), ['scenario_session_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_shipment_bookings_scenario_item_id_shipping_scenario_items'), 'shipping_scenario_items', ['scenario_item_id'], ['item_id'])
        batch_op.create_foreign_key(batch_op.f('fk_shipment_bookings_scenario_session_id_shipping_evaluation_sessions'), 'shipping_evaluation_sessions', ['scenario_session_id'], ['session_id'])

    with op.batch_alter_table('shipment_document_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_document_items_import_file_id'), ['import_file_id'], unique=False)

    with op.batch_alter_table('shipment_stage_activity', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('import_file_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('step_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'In-Progress'"))
        batch_op.alter_column('started_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('completed_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('assigned_user',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_shipment_stage_activity_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_stage_activity_import_file_code'), ['import_file_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_stage_activity_step_code'), ['step_code'], unique=False)

    with op.batch_alter_table('shipping_evaluation_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipping_evaluation_sessions_import_file_id'), ['import_file_id'], unique=False)

    with op.batch_alter_table('shipping_scenario_items', schema=None) as batch_op:
        batch_op.alter_column('free_time_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(14)'))
        batch_op.alter_column('quotation_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('total_quotation_amount',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('container_40ft_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('container_40ft_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('container_40ft_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('container_40ft_qty',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('container_20ft_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('container_20ft_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('container_20ft_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('container_20ft_qty',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('lcl_cbm_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('lcl_cbm_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('lcl_cbm_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('lcl_cbm_qty',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('express_courier_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('express_courier_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('express_courier_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('eur_atr_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('eur_atr_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('eur_atr_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('solas_vgm_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('solas_vgm_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('solas_vgm_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('vgm_notification_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('vgm_notification_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('vgm_notification_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('telex_release_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('telex_release_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('telex_release_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('insurance_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('insurance_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('insurance_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('booking_cancellation_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('booking_cancellation_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('booking_cancellation_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('ics2_filing_fee_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('ics2_filing_fee_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('ics2_filing_fee_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('others_fee_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('others_fee_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('others_fee_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('document_fees_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('document_fees_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('document_fees_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('waiver_letter_fee_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('waiver_letter_fee_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('waiver_letter_fee_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('dthc_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('dthc_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('dthc_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('storage_per_week_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('storage_per_week_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('storage_per_week_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('extra_day_storage_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('extra_day_storage_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('extra_day_storage_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'USD'"))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('has_iso',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('registered_decree_43',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('white_list_registered',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_unique_constraint(batch_op.f('uq_suppliers_foreign_exporter_id'), ['foreign_exporter_id'])

    with op.batch_alter_table('upload_sessions', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_upload_sessions_session_ref'), ['session_ref'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_upload_sessions_session_ref'), type_='unique')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_suppliers_foreign_exporter_id'), type_='unique')
        batch_op.alter_column('white_list_registered',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('registered_decree_43',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('has_iso',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('shipping_scenario_items', schema=None) as batch_op:
        batch_op.alter_column('extra_day_storage_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('extra_day_storage_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('extra_day_storage_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('storage_per_week_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('storage_per_week_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('storage_per_week_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('dthc_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('dthc_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('dthc_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('waiver_letter_fee_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('waiver_letter_fee_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('waiver_letter_fee_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('document_fees_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('document_fees_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('document_fees_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('others_fee_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('others_fee_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('others_fee_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('ics2_filing_fee_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('ics2_filing_fee_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('ics2_filing_fee_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('booking_cancellation_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('booking_cancellation_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('booking_cancellation_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('insurance_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('insurance_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('insurance_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('telex_release_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('telex_release_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('telex_release_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('vgm_notification_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('vgm_notification_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('vgm_notification_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('solas_vgm_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('solas_vgm_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('solas_vgm_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('eur_atr_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('eur_atr_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('eur_atr_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('express_courier_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('express_courier_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('express_courier_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('lcl_cbm_qty',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('lcl_cbm_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('lcl_cbm_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('lcl_cbm_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('container_20ft_qty',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('container_20ft_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('container_20ft_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('container_20ft_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('container_40ft_qty',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('container_40ft_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('container_40ft_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('container_40ft_applicable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_quotation_amount',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('quotation_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('free_time_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(14)'))

    with op.batch_alter_table('shipping_evaluation_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipping_evaluation_sessions_import_file_id'))

    with op.batch_alter_table('shipment_stage_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_stage_activity_step_code'))
        batch_op.drop_index(batch_op.f('ix_shipment_stage_activity_import_file_code'))
        batch_op.drop_index(batch_op.f('ix_shipment_stage_activity_id'))
        batch_op.alter_column('assigned_user',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('completed_at',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('started_at',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'In-Progress'"))
        batch_op.alter_column('step_code',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('import_file_code',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('shipment_document_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_document_items_import_file_id'))

    with op.batch_alter_table('shipment_bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_shipment_bookings_scenario_session_id_shipping_evaluation_sessions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_shipment_bookings_scenario_item_id_shipping_scenario_items'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_shipment_bookings_scenario_session_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_bookings_scenario_item_id'))

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_import_file_id'))

    with op.batch_alter_table('payment_request_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_request_sessions_import_file_id'))

    with op.batch_alter_table('import_requirement_assessments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_import_requirement_assessments_consultation_id_customs_consultation_sessions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_import_requirement_assessments_supplier_id_suppliers'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_import_requirement_assessments_assessment_code'), type_='unique')
        batch_op.alter_column('is_post_acid_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('confirmation_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Pending Confirmation'"))
        batch_op.alter_column('coa_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Not Required'"))
        batch_op.alter_column('coa_required',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('white_list_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('shipment_value',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.drop_column('sailing_date')
        batch_op.drop_column('sailing_status')
        batch_op.drop_column('hs_code_items')

    with op.batch_alter_table('import_files', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_import_files_broker_id_external_service_providers'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_import_files_custom_file_number'))
        batch_op.create_index(batch_op.f('ix_import_files_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_files_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_files_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_files_current_stage'), ['current_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_files_company_id'), ['company_id'], unique=False)
        batch_op.alter_column('estimated_cost_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('is_customs_released',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('import_companies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_import_companies_vat_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_import_companies_registration_number'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_import_companies_importer_id'), type_='unique')

    with op.batch_alter_table('import_budget_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_budget_approvals_import_file_id'))
        batch_op.alter_column('exchange_rate',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(50.0)'))
        batch_op.alter_column('freight_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('freight_cost_foreign',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('invoice_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('invoice_amount_foreign',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('freight_rfq_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_freight_rfq_requests_import_file_id'))

    with op.batch_alter_table('external_service_providers', schema=None) as batch_op:
        batch_op.alter_column('partner_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('customs_declaration_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customs_declaration_drafts_import_file_id'))

    with op.batch_alter_table('customs_consultation_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_customs_consultation_sessions_broker_price_list_id_broker_price_lists'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customs_consultation_sessions_import_file_id'))
        batch_op.alter_column('total_broker_fees_egp',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('cbm_calculations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cbm_calculations_import_file_id'))

    with op.batch_alter_table('cargo_shipping_records', schema=None) as batch_op:
        batch_op.alter_column('shipment_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'FCL'"))

    with op.batch_alter_table('banking_document_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banking_document_sessions_import_file_id'))
        batch_op.alter_column('execution_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('request_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('acid_registration_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_acid_registration_sessions_customs_broker_id_external_service_providers'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_acid_registration_sessions_import_file_id'))
        batch_op.drop_index(batch_op.f('ix_acid_registration_sessions_customs_broker_id'))
        batch_op.drop_index(batch_op.f('ix_acid_registration_sessions_acid_number'))
        batch_op.create_index(batch_op.f('ix_acid_registration_sessions_acid_number'), ['acid_number'], unique=1)
        batch_op.alter_column('has_discrepancies',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
