import os
import sys
from datetime import date
from decimal import Decimal

# Ensure project path is accessible
sys.path.insert(0, os.path.abspath("."))
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

from database.database import SessionLocal, engine, Base
from modules.customs_tariff.model import CustomsTariff, PreferentialAgreement

# Create tables if not exist
Base.metadata.create_all(bind=engine)

def seed_customs_tariffs():
    db = SessionLocal()
    try:
        print("🌱 Starting Comprehensive Egyptian Customs Tariff Seeding...")

        # Master HS Code Tariffs List according to Decree 549/2020 & Egyptian Customs Authority Schedule
        tariffs_data = [
            # ──────────────────────────────────────────────────
            # Sector 1: Electrical & IT Equipment (الأجهزة الكهربائية والشبكات والإلكترونيات)
            # ──────────────────────────────────────────────────
            {
                "hs_code": "8536410000",
                "hs_description": "مرحلات كهربائية لجهد لا يتجاوز 60 فولت (Electrical Relays <= 60V)",
                "customs_category": "مكونات كهربائية وصناعية",
                "customs_duty_rate": Decimal("10.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("10.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "الهيئة العامة للرقابة على الصادرات والواردات (GOEIC)",
                "prior_approval_note": "شهادة فحص وتطابق المواصفات القياسية المصرية ES 60947",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=8536410000",
                "notes": "بند معتمد في الفواتير الصناعية ولوحات التحكم الكهربائية",
            },
            {
                "hs_code": "8537109000",
                "hs_description": "لوحات ولوحات تحكم وتوزيع كهربائية لجهد لا يتجاوز 1000 فولت (Control Boards & Electric Panels)",
                "customs_category": "معدات ومستلزمات شبكات كهربائية",
                "customs_duty_rate": Decimal("10.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("10.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC / وزارة الكهرباء والطاقة المتجددة",
                "prior_approval_note": "يخضع لاختبارات الأمن والسلامة الكهربائية للجهد المنخفض",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=8537109000",
                "notes": "لوحات تحكم برمجية ومفاتيح أوتوماتيكية للمصانع والمشاريع القومية",
            },
            {
                "hs_code": "8471300000",
                "hs_description": "أجهزة حاسب آلي محمولة ومفكرات رقمية وززنها لا يتعدى 10 كجم (Laptops & Notebooks)",
                "customs_category": "أجهزة تكنولوجيا المعلومات والحاسبات",
                "customs_duty_rate": Decimal("0.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": False,
                "requires_acid": True,
                "regulatory_authority": "الجهاز القومي لتنظيم الاتصالات (NTRA)",
                "prior_approval_note": "موافقة الاتصالات في حالة وجود وحدات Wi-Fi أو Bluetooth مدمجة",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=8471300000",
                "notes": "معفى من ضريبة الوارد وفق قرار التعريفة المعمول به لدعم التحول الرقمي",
            },
            {
                "hs_code": "8471410000",
                "hs_description": "أجهزة معالجة بيانات رقمية مدمجة تشتمل على وحدة معالجة وذاكرة (Desktop Servers & PCs)",
                "customs_category": "خوادم ومحطات عمل رقمية",
                "customs_duty_rate": Decimal("0.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": False,
                "requires_acid": True,
                "regulatory_authority": "NTRA / هيئة تنمية صناعة تكنولوجيا المعلومات",
                "prior_approval_note": "موافقة الجهاز القومي لتنظيم الاتصالات لأجهزة الخوادم ذات التشفير العالي",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=8471410000",
                "notes": "معفى من ضريبة الوارد الجمركية",
            },
            {
                "hs_code": "8517130000",
                "hs_description": "هواتف ذكية وأجهزة شبكات خلوية محقولة (Smartphones & Cellular Handsets)",
                "customs_category": "أجهزة الاتصالات الذكية",
                "customs_duty_rate": Decimal("10.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("5.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "الجهاز القومي لتنظيم الاتصالات (NTRA) / الجهاز القومي للضرائب",
                "prior_approval_note": "موافقة نوعية مسبقة من NTRA واعتماد الرقم المسلسل IMEI في منظومة الحوكمة",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=8517130000",
                "notes": "يخضع لرسم تنمية موارد الدولة بنسبة 5% بالإضافة لرسوم الجهاز القومي للاتصالات",
            },
            {
                "hs_code": "8517620000",
                "hs_description": "أجهزة توجيه وتبديل واستقبال البيانات والشبكات (Routers, Switches & Modems)",
                "customs_category": "معدات شبكات الاتصالات والبنية التحتية",
                "customs_duty_rate": Decimal("5.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "NTRA",
                "prior_approval_note": "تصريح استيراد وإفراج جمركي من الجهاز القومي لتنظيم الاتصالات",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=8517620000",
                "notes": "معدات التشفير والمبدلات الذكية تحتاجة موافقة أمنية خاصة",
            },
            {
                "hs_code": "8528520000",
                "hs_description": "شاشات عرض مجهزة للاستخدام المباشر مع أجهزة المعالجة الآلية (Computer Monitors)",
                "customs_category": "شاشات وأجهزة عرض رقمية",
                "customs_duty_rate": Decimal("5.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC",
                "prior_approval_note": "فحص السلامة وكفاءة الطاقة من الرقابة على الصادرات والواردات",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=8528520000",
                "notes": "الشاشات التلفزيونية العادية تخضع لبند آخر برسم 40%",
            },
            {
                "hs_code": "8504409000",
                "hs_description": "متحولات ومستمرّات وشواحن ومحولات طاقة كهربائية إلكترونية (Inverters & Power Supplies)",
                "customs_category": "معدات وأجهزة الطاقة الكهربائية",
                "customs_duty_rate": Decimal("5.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC / هيئة الطاقة الجديدة والمتجددة",
                "prior_approval_note": "انفرترات الطاقة الشمسية تخضع لتخفيضات تفضيلية للمشاريع الخضراء",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=8504409000",
                "notes": "يشمل شواحن البطاريات الصناعية ومحولات انفرتر للطاقة الشمسية",
            },
            {
                "hs_code": "8544429000",
                "hs_description": "كابلات وموصلات كهربائية معزولة مجهزة بأطراف توصيل لجهد لا يتعدى 1000 فولت (Electric Cables & Connectors)",
                "customs_category": "كابلات وأسلاك كهربائية",
                "customs_duty_rate": Decimal("10.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC",
                "prior_approval_note": "شهادة مطابقة الموصلية وحظر أدخنة الهالوجين Zero Halogen",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=8544429000",
                "notes": "كابلات الألياف الضوئية لها بند مستقل بنسبة 5%",
            },

            # ──────────────────────────────────────────────────
            # Sector 2: Industrial Machinery & Equipment (الآلات والمعدات الميكانيكية والخطوط)
            # ──────────────────────────────────────────────────
            {
                "hs_code": "8414800000",
                "hs_description": "ضواغط هواء ومضخات تفريغ هواء صناعية (Air Compressors & Vacuum Pumps)",
                "customs_category": "آلات ومعدات صناعية ميكانيكية",
                "customs_duty_rate": Decimal("5.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC / وزارة الصناعة والتنمية الصناعية",
                "prior_approval_note": "شهادة اختبار أوعية الضغط والسلامة الميكانيكية",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=8414800000",
                "notes": "تستفيد الخطوط الإنتاجية الكاملة من فئة 2% بموجب خطابات هيئة التنمية الصناعية",
            },
            {
                "hs_code": "8413700000",
                "hs_description": "مضخات طرد مركزي مائية وصناعية وسوائل أخرى (Centrifugal Water Pumps)",
                "customs_category": "طلمبات ومضخات مائية وصناعية",
                "customs_duty_rate": Decimal("5.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC / وزارة الري والموارد المائية",
                "prior_approval_note": "مطابقة مواصفات الضغط وكفاءة استهلاك الطاقة الكهربائية",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=8413700000",
                "notes": "طلمبات الأعماق وطلمبات الخرسانة تخضع لبنود فرعية خاصة",
            },
            {
                "hs_code": "8481809000",
                "hs_description": "صمامات ومحابس وبوابات صناعية للتحكم في الأنابيب والخزانات (Industrial Valves & Taps)",
                "customs_category": "صمامات ومحابس ومستلزمات خطوط شبكات",
                "customs_duty_rate": Decimal("5.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC",
                "prior_approval_note": "شهادة فحص ضغط السوائل واختبارات التسريب ISO 5208",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=8481809000",
                "notes": "مكونات خطوط الغاز الطبيعي والبترول تحتاح موافقة هيئة البترول EGPC",
            },
            {
                "hs_code": "8482100000",
                "hs_description": "رولمان بلي ورولمان بلح كروي لحركة المحاور الميكانيكية (Ball Bearings)",
                "customs_category": "مكونات ميكانيكية وقطع غيار مصانع",
                "customs_duty_rate": Decimal("2.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC",
                "prior_approval_note": "شهادة منشأ وفحص الأبعاد والصلابة لقطع الغيار الصناعية",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=8482100000",
                "notes": "فئة تخفيض جمركي تشجيعي للصناعات الوطنية برسم 2%",
            },
            {
                "hs_code": "8428330000",
                "hs_description": "سيور وخطوط نقل آلية متصلة للمصانع والمستودعات (Conveyor Belt Systems)",
                "customs_category": "معدات ومناولة وتجهيز خطوط الإنتاج",
                "customs_duty_rate": Decimal("5.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": False,
                "requires_acid": True,
                "regulatory_authority": "GOEIC / التنمية الصناعية",
                "prior_approval_note": "تخفيض إلى 2% عند الشحن كخط إنتاجي مجمع بموجب قرار 32",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=8428330000",
                "notes": "أنظمة السيور والمناولة الأوتوماتيكية للمخازن الذكية",
            },

            # ──────────────────────────────────────────────────
            # Sector 3: Vehicles, Passenger Cars & Spare Parts (السيارات ووسائل النقل وقطع الغيار)
            # ──────────────────────────────────────────────────
            {
                "hs_code": "8703239000",
                "hs_description": "سيارات ركوب بمحرك بنزين (سعة السلندرات من 1500 حتى 1600 سم3) (Passenger Cars 1.5L-1.6L)",
                "customs_category": "سيارات ركوب واستخدام شخصي وتجاري",
                "customs_duty_rate": Decimal("40.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("1.00"),
                "development_fee_rate": Decimal("3.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC / المرور / وزارة التجارة والصناعة",
                "prior_approval_note": "تطبق قواعد العمر (موديل السنة) والإفراج عن السيارت الأوروبية 0% بموجب الشراكة الأوروبية بشرط شهادة EUR.1",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=8703239000",
                "notes": "تخضع لضريبة جدول 1% ورسم تنمية 3% من القيمة الجمركية CIF + الجمرك",
            },
            {
                "hs_code": "8703800000",
                "hs_description": "سيارات ركوب ذات محرك كهربائي بالكامل لتوليد الحركة (Electric Passenger Cars - EV)",
                "customs_category": "سيارات وركوب صديقة للبيئة (كهربائية)",
                "customs_duty_rate": Decimal("0.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC / وزارة البيئة",
                "prior_approval_note": "معفاة تماماً من ضريبة الوارد الجمركية وفق قرار مجلس الوزراء لدعم المركبات الكهربائية",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=8703800000",
                "notes": "يشترط ألا يتجاوز عمر السيارة 3 سنوات من تاريخ الصنع",
            },
            {
                "hs_code": "8708300000",
                "hs_description": "أنظمة فرامل وأجزاؤها وسلاسل فرامل لسيارات الركوب والمركبات (Automotive Brake Systems & Parts)",
                "customs_category": "قطع غيار وأجزاء سيارات ومركبات",
                "customs_duty_rate": Decimal("12.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "الهيئة العامة للرقابة على الصادرات والواردات (GOEIC)",
                "prior_approval_note": "شهادة فحص إجبارية من المصانع المسجلة وفق القرار الوزاري 43 لسنة 2016",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=8708300000",
                "notes": "تخضع لقائمة الفحص النوعي الإجباري لقطع غيار الأمان والسلامة بالمركبات",
            },
            {
                "hs_code": "8708990000",
                "hs_description": "أجزاء ولوازم أخرى لسيارات الركوب ونقل البضائع (Automotive Miscellaneous Spare Parts)",
                "customs_category": "قطع غيار سيارات ومعدات نقل",
                "customs_duty_rate": Decimal("12.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC",
                "prior_approval_note": "تسجيل الشركات الموردة بالرقابة على الصادرات والواردات mandatory registration",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=8708990000",
                "notes": "أجزاء التعليق والمساعدين وعلب عجلة القيادة",
            },

            # ──────────────────────────────────────────────────
            # Sector 4: Plastics, Chemicals & Rubber (البلاستيك والمواد الكيميائية والمطاط)
            # ──────────────────────────────────────────────────
            {
                "hs_code": "3901100000",
                "hs_description": "بولي إيثيلين بكثافة أقل من 0.94 في أشكاله الأولية حبيبات (Low-Density Polyethylene Raw Granules - LDPE)",
                "customs_category": "خامات بلاستيكية وراتنجات أولية",
                "customs_duty_rate": Decimal("2.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": False,
                "requires_acid": True,
                "regulatory_authority": "وزارة الصناعة / هيئة التنمية الصناعية",
                "prior_approval_note": "خامات أولية مستوردة للمصانع والورش الإنتاجية الوطنية",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=3901100000",
                "notes": "فئة تشجيعية 2% لدعم مصانع البلاستيك والتعبئة والتغليف المحلية",
            },
            {
                "hs_code": "3902100000",
                "hs_description": "بولي بروبيلين في أشكاله الأولية حبيبات وبودرة (Polypropylene Raw Granules - PP)",
                "customs_category": "خامات بلاستيك وبتروكيماويات",
                "customs_duty_rate": Decimal("2.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": False,
                "requires_acid": True,
                "regulatory_authority": "هيئة التنمية الصناعية",
                "prior_approval_note": "خامات مستوردة لأغراض السحب والحقن وتصنيع المواسير والسجاد",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=3902100000",
                "notes": "خام البولي بروبيلين للصناعات الكيماوية والنسيجية",
            },
            {
                "hs_code": "4011100000",
                "hs_description": "إطارات مطاطية جديدة من أصناف مستعملة لسيارات الركوب (New Pneumatic Rubber Passenger Tyres)",
                "customs_category": "منتجات المطاط وإطارات المركبات",
                "customs_duty_rate": Decimal("20.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC",
                "prior_approval_note": "شهادة اختبار الأداء وتحمل درجات الحرارة ومطابقة المواصفات المصرية ES 1481",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=4011100000",
                "notes": "إطارات الشاحنات والحافلات لها بند مستقل برسم 10%",
            },
            {
                "hs_code": "2836200000",
                "hs_description": "كربونات الصوديوم نلمحتوية على صودا آش ناعمة وخشنة (Sodium Carbonate - Soda Ash)",
                "customs_category": "كيماويات صناعية غير عضوية",
                "customs_duty_rate": Decimal("2.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "وزارة البيئة / الهيئة العامة للرقابة على الصادرات والواردات",
                "prior_approval_note": "صحيفة بيانات السلامة الكيميائية MSDS واشتراطات النقل الآمن",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=2836200000",
                "notes": "مادة خام أساسية لصناعة الزجاج والمنظفات والورق",
            },

            # ──────────────────────────────────────────────────
            # Sector 5: Steel, Iron & Base Metals (الحديد والصلب والمعادن ومصنوعاتها)
            # ──────────────────────────────────────────────────
            {
                "hs_code": "7208390000",
                "hs_description": "منتجات مسطحة بالدرفلة على الساخن من حديد أو صلب سمك أقل من 3 مم في لائف (Hot Rolled Steel Coils < 3mm)",
                "customs_category": "حديد وصلب خام وملايع درفلة",
                "customs_duty_rate": Decimal("5.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC / قطاع التجارة الخارجية",
                "prior_approval_note": "شهادة فحص الشحنة واختبارات الشد والتركيب الكيميائي للصلب",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=7208390000",
                "notes": "قد تخضع لتدابير حماية أو رسوم إغراق تدبيرية حسب القرارات الوزارية",
            },
            {
                "hs_code": "7210490000",
                "hs_description": "صاج مجلفن ومغطى بالزنك من صلب مسطح مدرفل (Galvanized Sheet Steel)",
                "customs_category": "حديد صاج مجلفن ومطلي",
                "customs_duty_rate": Decimal("10.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC",
                "prior_approval_note": "قياس سمك طبقة الجلفنة والزنك المطابق للمواصفة القياسية",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=7210490000",
                "notes": "مستلزم لصناعة الثلاجات والغسالات والهياكل المعدنية",
            },
            {
                "hs_code": "7318150000",
                "hs_description": "براغي ومسامير ملولبة وصواميل من حديد أو صلب (Steel Threaded Bolts & Screws)",
                "customs_category": "مصنوعات حديد وصلب ومثبتات",
                "customs_duty_rate": Decimal("10.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC",
                "prior_approval_note": "شهادة فحص الجودة لدرجة صلابة المسامير والتثبيتات",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=7318150000",
                "notes": "مسامير التركيبات الهندسية والمصانع",
            },
            {
                "hs_code": "7604290000",
                "hs_description": "قطاعات وأشكال خاصة من ألومنيوم غير مسبوك (Aluminum Extruded Profiles)",
                "customs_category": "ألومنيوم ومصنوعاته",
                "customs_duty_rate": Decimal("10.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC",
                "prior_approval_note": "اختبارات نقاوة الألومنيوم والمواصفات المعمارية",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=7604290000",
                "notes": "مستلزمات واجهات المباني والواجهات المعمارية والشبابيك",
            },

            # ──────────────────────────────────────────────────
            # Sector 6: Foodstuff & Agricultural Products (الأغذية والمنتجات الزراعية والحيوانية)
            # ──────────────────────────────────────────────────
            {
                "hs_code": "1001990000",
                "hs_description": "قمح وحنطة للاستهلاك البشري (Wheat for Human Consumption)",
                "customs_category": "حبوب وسلع استراتيجية زراعية",
                "customs_duty_rate": Decimal("0.00"),
                "vat_rate": Decimal("0.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "الهيئة القومية لسلامة الغذاء (NFSA) / الحجر الزراعي",
                "prior_approval_note": "شهادة فحص خلو من الإرجوت والفطريات والمبيدات وتحليل الحجر الزراعي",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=1001990000",
                "notes": "سلعة استراتيجية معفاة تماماً من الجمارك وضريبة القيمة المضافة بموجب القانون",
            },
            {
                "hs_code": "1507100000",
                "hs_description": "زيت فول صويا خام غير معدل كيميائياً (Crude Soybean Oil)",
                "customs_category": "زيوت زراعية ونباتية خام",
                "customs_duty_rate": Decimal("0.00"),
                "vat_rate": Decimal("0.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "NFSA / الحجر الزراعي",
                "prior_approval_note": "شهادة صحية وفحص معملي للإفراج عن الزيوت الغذائية الخام",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=1507100000",
                "notes": "معفى من ضريبة الوارد وضريبة القيمة المضافة لدعم منظومة الزيوت التموينية والغذائية",
            },
            {
                "hs_code": "0202300000",
                "hs_description": "لحوم أبقار مجمدة بدون عظام (Frozen Boneless Beef)",
                "customs_category": "لحوم ومنتجات حيوانية مجمدة",
                "customs_duty_rate": Decimal("5.00"),
                "vat_rate": Decimal("0.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "NFSA / الحجر البيطري / الهيئة العامة للخدمات البيطرية",
                "prior_approval_note": "شهادة تذكية إسلامية (Halal Certificate) موثقة وشرفات الفحص البيطري بالميناء",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=0202300000",
                "notes": "معفاة من ضريبة القيمة المضافة طبقاً لقانون القيمة المضافة رقم 67 لسنة 2016 وتعديلاته",
            },
            {
                "hs_code": "0402100000",
                "hs_description": "حليب وبودرة لبن مجفف بنسبة دسم لا تتجاوز 1.5% (Skimmed Milk Powder)",
                "customs_category": "منتجات ألبان ومستلزمات تصنيع غذائي",
                "customs_duty_rate": Decimal("5.00"),
                "vat_rate": Decimal("0.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "NFSA / سلامة الغذاء",
                "prior_approval_note": "تحليل إشعاعي وميكروبيولوجي كامل من الهيئة القومية لسلامة الغذاء",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=0402100000",
                "notes": "مادة أولية لمصانع الألبان والأغذية ومعفاة من القيمة المضافة",
            },

            # ──────────────────────────────────────────────────
            # Sector 7: Pharmaceuticals & Medical Devices (الأدوية والأجهزة والمستلزمات الطبية)
            # ──────────────────────────────────────────────────
            {
                "hs_code": "3004909000",
                "hs_description": "أدوية ومستحضرات صيدلانية ومضادات حيوية مهيأة للبيع بالتجزئة (Finished Human Medicines)",
                "customs_category": "أدوية ومستحضرات طبية بشرية",
                "customs_duty_rate": Decimal("0.00"),
                "vat_rate": Decimal("0.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "هيئة الدواء المصرية (EDA)",
                "prior_approval_note": "إفراج صحي وموافقة تسعير وتسجيل مستحضر صيدلي من هيئة الدواء المصرية",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=3004909000",
                "notes": "معفى كاملاً من الجمارك وضريبة القيمة المضافة بحكم القانون للحفاظ على أسعار الدواء",
            },
            {
                "hs_code": "9018900000",
                "hs_description": "أدوات وأجهزة طبية وجودة جراحية وتشخيصية ذات استخدام طبي (Medical & Surgical Instruments)",
                "customs_category": "أجهزة ومستلزمات جراحية وتأهيلية",
                "customs_duty_rate": Decimal("0.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "هيئة الدواء المصرية (EDA) / الشراء الموحد",
                "prior_approval_note": "تصريح استيراد وترخيص تداول أجهزة طبية من الإدارة المركزية للمستلزمات الطبية",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=9018900000",
                "notes": "معفاة من ضريبة الوارد لدعم المنظومة الصحية والتعليمية",
            },

            # ──────────────────────────────────────────────────
            # Sector 8: Textiles & Apparel (المنسوجات والملابس والجاهزات)
            # ──────────────────────────────────────────────────
            {
                "hs_code": "5201000000",
                "hs_description": "قطن خام غير محلوج ولا ممشط لتغذية المحالج والمصانع (Raw Cotton)",
                "customs_category": "ألياف نسيجية خامات زراعية",
                "customs_duty_rate": Decimal("0.00"),
                "vat_rate": Decimal("0.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "الحجر الزراعي / لجنة تحكيم القطن",
                "prior_approval_note": "شهادة تبخير وفحص حجر زراعي للخلو من الآفات والديدان الحجرية",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=5201000000",
                "notes": "خام زراعي صناعي معفى من كافة الضرائب والرسوم",
            },
            {
                "hs_code": "6109100000",
                "hs_description": "قمصان تي شيرت وسترات حياكة مصنعة من قطن خالص أو مخلوط (Cotton T-Shirts & Vests)",
                "customs_category": "ملابس جاهزة ومنسوجات مسبوكة",
                "customs_duty_rate": Decimal("30.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC",
                "prior_approval_note": "تسجيل مصانع الملابس الجاهزة بالرقابة على الصادرات والواردات طبقاً للقرار 43",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=6109100000",
                "notes": "تخضع للفئة العالية 30% لحماية الصناعة الوطنية للملابس والنسيج",
            },

            # ──────────────────────────────────────────────────
            # Sector 9: Furniture & Building Materials (الأثاث ومواد البناء والورق)
            # ──────────────────────────────────────────────────
            {
                "hs_code": "4407110000",
                "hs_description": "أخشاب صنوبرية منشورة أو مقطوعة طولياً سمك يتجاوز 6 مم (Pine Sawn Timber & Wood)",
                "customs_category": "أخشاب وخامات صناعية",
                "customs_duty_rate": Decimal("2.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "الحجر الزراعي / الرقابة على الصادرات والواردات",
                "prior_approval_note": "شهادة تبخير خشبية معتمدة وفق المعيار الدولي ISPM 15",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=4407110000",
                "notes": "خامات خشبية أولية لمصانع الأثاث ومقاولات البناء برسم 2%",
            },
            {
                "hs_code": "6907210000",
                "hs_description": "بلاط وبلاطات سيراميك وبورسلين ملمعة للأرضيات والجدران (Porcelain & Ceramic Tiles)",
                "customs_category": "مواد بناء وسيراميك وبورسلين",
                "customs_duty_rate": Decimal("40.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC",
                "prior_approval_note": "اختبارات مقاومة البري وامتصاص الماء والمواصفات القياسية ES 3168",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=6907210000",
                "notes": "تخضع للفئة العظمى 40% لدعم صناعة السيراميك المصرية",
            },
            {
                "hs_code": "9403200000",
                "hs_description": "أثاث معدني من أنواع مستعملة في المكاتب والمحلات (Metal Office Furniture)",
                "customs_category": "أثاث ومستلزمات تجهيز المكاتب",
                "customs_duty_rate": Decimal("30.00"),
                "vat_rate": Decimal("14.00"),
                "schedule_tax_rate": Decimal("0.00"),
                "development_fee_rate": Decimal("0.00"),
                "import_fee_rate": Decimal("0.00"),
                "requires_coo": True,
                "requires_inspection": True,
                "requires_acid": True,
                "regulatory_authority": "GOEIC",
                "prior_approval_note": "تسجيل مصانع الأثاث الموردة بالرقابة على الصادرات والواردات",
                "source_url": "https://www.nafeza.gov.eg/ar/tarrif?code=9403200000",
                "notes": "مكاتب ودواليب معدنية وتجهيزات تخزين",
            },
        ]

        # Preferential Agreements List (الاتفاقيات التفضيلية المعتمدة وفق Addendum 3)
        agreements_data = [
            {
                "hs_code": "8536410000",
                "agreement_name": "اتفاقية منطقة التجارة الحرة العربية الكبرى (GAFTA)",
                "reduction_type": "full_duty_exemption",
                "reduction_percentage": Decimal("1.00"),
                "origin_countries": "SA,AE,JO,IQ,LY,SD,KW,QA,BH,OM,LB,SY,YE,MA,TN,DZ",
                "conditions_note": "إعفاء 100% من ضريبة الوارد بشرط تقديم شهادة منشأ عربية معتمدة وقاعدة القيمة المضافة العربية 40%",
            },
            {
                "hs_code": "8537109000",
                "agreement_name": "اتفاقية منطقة التجارة الحرة العربية الكبرى (GAFTA)",
                "reduction_type": "full_duty_exemption",
                "reduction_percentage": Decimal("1.00"),
                "origin_countries": "SA,AE,JO,IQ,LY,SD,KW,QA,BH,OM,LB,SY,YE,MA,TN,DZ",
                "conditions_note": "إعفاء 100% من الجمرك للشهادات العربية المعتمدة",
            },
            {
                "hs_code": "8537109000",
                "agreement_name": "اتفاقية الشراكة المصرية الأوروبية (Egypt-EU Partnership Agreement)",
                "reduction_type": "full_duty_exemption",
                "reduction_percentage": Decimal("1.00"),
                "origin_countries": "DE,IT,FR,ES,NL,BE,PL,CZ,AT,SE,FI,DK,GR,PT,IE,HU,RO,BG",
                "conditions_note": "إعفاء جمركي 100% بشرط شهادة حركة البضائع EUR.1 أو EUR-MED المعتمدة مع الفاتورة",
            },
            {
                "hs_code": "8537109000",
                "agreement_name": "اتفاقية التجارة الحرة بين مصر وتركيا (Egypt-Turkey FTA)",
                "reduction_type": "full_duty_exemption",
                "reduction_percentage": Decimal("1.00"),
                "origin_countries": "TR",
                "conditions_note": "إعفاء كامل 100% من ضريبة الوارد الجمركية للبضائع ذات المنشأ التركي المصحوبة بشهادة EUR.1",
            },
            {
                "hs_code": "8703239000",
                "agreement_name": "اتفاقية الشراكة المصرية الأوروبية (Egypt-EU Partnership)",
                "reduction_type": "full_duty_exemption",
                "reduction_percentage": Decimal("1.00"),
                "origin_countries": "DE,IT,FR,ES,NL,BE,PL,CZ,AT,SE,FI,DK,GR,PT,IE,HU,RO,BG",
                "conditions_note": "إعفاء 100% من ضريبة الوارد (الجمارك) لسيارات الركوب الأوروبية المصحوبة بشهادة EUR.1 مع استمرار تطبيق ضريبة القيمة المضافة وجدول التنمية",
            },
            {
                "hs_code": "8708300000",
                "agreement_name": "اتفاقية الشراكة المصرية الأوروبية (Egypt-EU Partnership)",
                "reduction_type": "full_duty_exemption",
                "reduction_percentage": Decimal("1.00"),
                "origin_countries": "DE,IT,FR,ES,NL,BE,PL,CZ,AT,SE,FI,DK,GR,PT,IE,HU,RO,BG",
                "conditions_note": "إعفاء 100% من ضريبة الوارد لقطع الغيار ذات المنشأ الأوروبي",
            },
            {
                "hs_code": "8708300000",
                "agreement_name": "اتفاقية التجارة الحرة بين مصر وتركيا (Egypt-Turkey FTA)",
                "reduction_type": "full_duty_exemption",
                "reduction_percentage": Decimal("1.00"),
                "origin_countries": "TR",
                "conditions_note": "إعفاء 100% لقطع الغيار التركية الأصل المصحوبة بشهادة EUR.1",
            },
            {
                "hs_code": "4011100000",
                "agreement_name": "اتفاقية الشراكة المصرية الأوروبية (Egypt-EU Partnership)",
                "reduction_type": "full_duty_exemption",
                "reduction_percentage": Decimal("1.00"),
                "origin_countries": "DE,IT,FR,ES,NL,BE,PL,CZ,AT,SE,FI,DK,GR,PT,IE,HU,RO,BG",
                "conditions_note": "إعفاء كامل من جمرك الإطارات الأوروبية الأصل",
            },
            {
                "hs_code": "6109100000",
                "agreement_name": "اتفاقية الأغادير (Agadir Agreement)",
                "reduction_type": "full_duty_exemption",
                "reduction_percentage": Decimal("1.00"),
                "origin_countries": "MA,TN,JO",
                "conditions_note": "إعفاء 100% من الجمرك للمنسوجات المصنعة بدول اتفاقية الأغادير",
            },
            {
                "hs_code": "4407110000",
                "agreement_name": "اتفاقية الشراكة المصرية الأوروبية (Egypt-EU Partnership)",
                "reduction_type": "full_duty_exemption",
                "reduction_percentage": Decimal("1.00"),
                "origin_countries": "DE,IT,FR,ES,NL,BE,PL,CZ,AT,SE,FI,DK,GR,PT,IE,HU,RO,BG,FI",
                "conditions_note": "إعفاء 100% للأخشاب السويدية والفنلندية ذات المنشأ الأوروبي المصحوبة بشهادة EUR.1",
            },
        ]

        # Insert Tariffs
        inserted_tariffs = 0
        updated_tariffs = 0

        for t_dict in tariffs_data:
            existing = db.query(CustomsTariff).filter(
                CustomsTariff.hs_code == t_dict["hs_code"],
                CustomsTariff.effective_from == date.today(),
            ).first()

            if existing:
                for k, v in t_dict.items():
                    setattr(existing, k, v)
                updated_tariffs += 1
            else:
                tariff_obj = CustomsTariff(
                    **t_dict,
                    effective_from=date.today(),
                    verified_by="System Master Seed",
                    confidence="verified_official_gazette",
                )
                db.add(tariff_obj)
                inserted_tariffs += 1

        db.commit()
        print(f"✅ Inserted {inserted_tariffs} new Customs Tariff records, updated {updated_tariffs}.")

        # Insert Preferential Agreements
        inserted_agreements = 0
        for a_dict in agreements_data:
            existing_agr = db.query(PreferentialAgreement).filter(
                PreferentialAgreement.hs_code == a_dict["hs_code"],
                PreferentialAgreement.agreement_name == a_dict["agreement_name"],
            ).first()

            if not existing_agr:
                agr_obj = PreferentialAgreement(
                    **a_dict,
                    effective_from=date.today(),
                )
                db.add(agr_obj)
                inserted_agreements += 1

        db.commit()
        print(f"✅ Inserted {inserted_agreements} Preferential Agreement records.")

        total_tariffs = db.query(CustomsTariff).count()
        total_agreements = db.query(PreferentialAgreement).count()
        print(f"🎉 Total Database CustomsTariff count now: {total_tariffs}")
        print(f"🎉 Total Database PreferentialAgreement count now: {total_agreements}")

    except Exception as e:
        db.rollback()
        print(f"❌ Error seeding tariffs: {e}")
        raise e
    finally:
        db.close()

if __name__ == "__main__":
    seed_customs_tariffs()
