import os
import sys
from datetime import date, datetime, timezone

root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)

from database.database import SessionLocal
from modules.customs_tariff.model import CustomsTariff

NAFEZA_CUSTOMS_TARIFFS = [
    # 1. Agriculture & Food (المنتجات الزراعية والأغذية)
    {
        "hs_code": "1001.99.00",
        "hs_description": "Wheat and meslin (Other than durum wheat)",
        "customs_category": "Agriculture & Food",
        "customs_duty_rate": 0.00,
        "vat_rate": 0.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "Quarantine, GOEIC, Food Safety Authority (NFSA)",
        "notes": "سلعة استراتيجية أساسية — معفاة من الجمارك والضريبة",
    },
    {
        "hs_code": "1006.30.00",
        "hs_description": "Semi-milled or wholly milled rice, whether or not polished or glazed",
        "customs_category": "Agriculture & Food",
        "customs_duty_rate": 0.00,
        "vat_rate": 0.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "National Food Safety Authority (NFSA), GOEIC",
        "notes": "أرز مبيض أو معالج — معفى من الضرائب والرسوم الجمركية",
    },
    {
        "hs_code": "0713.31.00",
        "hs_description": "Beans of the species Vigna mungo (L.) Hepper or Vigna radiata (L.) Wilczek (Dried Fava Beans)",
        "customs_category": "Agriculture & Food",
        "customs_duty_rate": 0.00,
        "vat_rate": 0.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "Agricultural Quarantine, NFSA",
        "notes": "فول مجفف استراتيجي — معفى لدعم الأمن الغذائي",
    },
    {
        "hs_code": "1507.10.00",
        "hs_description": "Crude soybean oil, whether or not degummed",
        "customs_category": "Agriculture & Food",
        "customs_duty_rate": 2.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "National Food Safety Authority (NFSA)",
        "notes": "زيت صويا خام لصناعة الزيوت",
    },
    {
        "hs_code": "1512.11.00",
        "hs_description": "Crude sunflower-seed or safflower oil",
        "customs_category": "Agriculture & Food",
        "customs_duty_rate": 2.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "NFSA",
        "notes": "زيت عباد شمس خام",
    },
    {
        "hs_code": "1701.99.90",
        "hs_description": "Cane or beet sugar in solid form (Refined sugar)",
        "customs_category": "Agriculture & Food",
        "customs_duty_rate": 20.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "National Food Safety Authority (NFSA)",
        "notes": "سكر مكرر — خاضع لضريبة وارد 20%",
    },
    {
        "hs_code": "0402.10.00",
        "hs_description": "Milk and cream in powder, granules, fat content <= 1.5%",
        "customs_category": "Agriculture & Food",
        "customs_duty_rate": 5.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "NFSA & Veterinary Quarantine",
        "notes": "لبن مجفف بودرة لصناعات الأغذية",
    },
    {
        "hs_code": "0202.30.00",
        "hs_description": "Frozen boneless bovine meat (Frozen Beef)",
        "customs_category": "Agriculture & Food",
        "customs_duty_rate": 0.00,
        "vat_rate": 0.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "Veterinary Quarantine & Halal Inspection, NFSA",
        "notes": "لحوم بقرية مجمدة بدون عظم — معفاة بشرط شهادة الذبح الحلال",
    },
    {
        "hs_code": "0303.89.00",
        "hs_description": "Frozen fish excluding salmon, trout, tuna, mackerel",
        "customs_category": "Agriculture & Food",
        "customs_duty_rate": 5.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "NFSA & General Authority for Fisheries Development",
        "notes": "أسماك مجمدة متنوعة",
    },
    {
        "hs_code": "0901.11.00",
        "hs_description": "Coffee, not roasted, not decaffeinated (Raw Green Coffee Beans)",
        "customs_category": "Agriculture & Food",
        "customs_duty_rate": 5.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "NFSA & Agricultural Quarantine",
        "notes": "بن أخضر غير محمص",
    },
    {
        "hs_code": "0902.30.00",
        "hs_description": "Black tea (fermented) in immediate packings <= 3kg",
        "customs_category": "Agriculture & Food",
        "customs_duty_rate": 2.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "NFSA",
        "notes": "شاي أسود معبأ",
    },
    {
        "hs_code": "1806.31.00",
        "hs_description": "Chocolate and other food preparations containing cocoa, filled, in blocks or slabs",
        "customs_category": "Luxury & Consumer Goods",
        "customs_duty_rate": 30.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 5.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "NFSA & GOEIC Decree 43",
        "notes": "شوكولاتة محشوة — يتطلب تسجيل المصانع المؤهلة لتصدير المنتجات لمصر",
    },

    # 2. Pharmaceuticals & Medical Equipment (الأدوية والأجهزة الطبية)
    {
        "hs_code": "3004.90.90",
        "hs_description": "Medicaments consisting of mixed or unmixed products for therapeutic uses",
        "customs_category": "Pharmaceuticals",
        "customs_duty_rate": 0.00,
        "vat_rate": 0.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "EDA (Egyptian Drug Authority)",
        "notes": "مستحضرات صيدلانية وأدوية بشري — معفى تشجيعاً للقطاع الطبي",
    },
    {
        "hs_code": "3002.20.00",
        "hs_description": "Vaccines for human medicine",
        "customs_category": "Pharmaceuticals",
        "customs_duty_rate": 0.00,
        "vat_rate": 0.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "Egyptian Drug Authority (EDA)",
        "notes": "طعوم ولقاحات طبية بشرية — معفاة تماماً",
    },
    {
        "hs_code": "9018.90.00",
        "hs_description": "Instruments and appliances used in medical, surgical or veterinary sciences",
        "customs_category": "Medical Equipment",
        "customs_duty_rate": 0.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "EDA & Ministry of Health",
        "notes": "أجهزة جراحية وطبية — معفاة من ضريبة الوارد",
    },
    {
        "hs_code": "9022.14.00",
        "hs_description": "Apparatus based on the use of X-rays for medical, surgical or dental use",
        "customs_category": "Medical Equipment",
        "customs_duty_rate": 0.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "Egyptian Atomic Energy Authority & EDA",
        "notes": "أجهزة أشعة سينية تشخيصية — موافقة هيئة الطاقة الذرية",
    },
    {
        "hs_code": "3005.90.00",
        "hs_description": "Wadding, gauze, bandages and similar medical articles impregnated or coated",
        "customs_category": "Medical Supplies",
        "customs_duty_rate": 5.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "EDA",
        "notes": "شاش وضماضم ومستلزمات طبية معقمة",
    },

    # 3. Chemicals & Plastics (الكيماويات والبلاستيك)
    {
        "hs_code": "3901.10.00",
        "hs_description": "Polyethylene having a specific gravity of less than 0.94 (Primary forms)",
        "customs_category": "Chemicals & Plastics",
        "customs_duty_rate": 2.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "Egyptian Environmental Affairs Agency (EEAA)",
        "notes": "بوليثيلين منخفض الكثافة خامات أولية للصناعة",
    },
    {
        "hs_code": "3902.10.00",
        "hs_description": "Polypropylene in primary forms",
        "customs_category": "Chemicals & Plastics",
        "customs_duty_rate": 2.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": False,
        "requires_acid": True,
        "regulatory_authority": "EEAA",
        "notes": "بوليمرات بروبيلين أشكال أولية",
    },
    {
        "hs_code": "3904.10.00",
        "hs_description": "Polyvinyl chloride (PVC) not mixed with any other substances in primary forms",
        "customs_category": "Chemicals & Plastics",
        "customs_duty_rate": 2.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": False,
        "requires_acid": True,
        "regulatory_authority": "EEAA",
        "notes": "خامات PVC لصناعة المواسير والكابلات",
    },
    {
        "hs_code": "2815.11.00",
        "hs_description": "Sodium hydroxide (Caustic soda) solid",
        "customs_category": "Chemicals & Plastics",
        "customs_duty_rate": 2.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "Chemical Administration & EEAA",
        "notes": "صودا كاوية صلبة للصناعات الكيماوية والمنظفات",
    },
    {
        "hs_code": "3102.10.00",
        "hs_description": "Urea whether or not in aqueous solution (Fertilizers)",
        "customs_category": "Chemicals & Plastics",
        "customs_duty_rate": 5.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "Ministry of Agriculture",
        "notes": "سماد يوريا زراعي",
    },
    {
        "hs_code": "3208.10.00",
        "hs_description": "Paints and varnishes based on polyesters in non-aqueous medium",
        "customs_category": "Chemicals & Plastics",
        "customs_duty_rate": 10.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC",
        "notes": "دهانات وورنيشات صناعية",
    },

    # 4. Textiles & Apparel (المنسوجات والملابس)
    {
        "hs_code": "5201.00.00",
        "hs_description": "Cotton, not carded or combed (Raw Cotton)",
        "customs_category": "Textiles & Apparel",
        "customs_duty_rate": 0.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "Agricultural Quarantine (Cotton Pest Control)",
        "notes": "قطن خام غير محلوج — معفى لدعم صناعة الغزل والنسيج",
    },
    {
        "hs_code": "5208.11.00",
        "hs_description": "Plain weave woven fabrics of cotton, containing >= 85% cotton",
        "customs_category": "Textiles & Apparel",
        "customs_duty_rate": 15.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC",
        "notes": "أقمشة قطنية منسوجة خام",
    },
    {
        "hs_code": "6203.42.00",
        "hs_description": "Men's or boys' trousers and shorts of cotton",
        "customs_category": "Textiles & Apparel",
        "customs_duty_rate": 30.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC (Factory Registration Decree 43 Required)",
        "notes": "بنطلونات رجال وأولاد — يتطلب فحص GOEIC وتسجيل مصنع",
    },
    {
        "hs_code": "6109.10.00",
        "hs_description": "T-shirts, singlets and other vests of cotton, knitted or crocheted",
        "customs_category": "Textiles & Apparel",
        "customs_duty_rate": 30.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC (Decree 43)",
        "notes": "قمصان تيشيرت قطنية تريكو",
    },
    {
        "hs_code": "6302.21.00",
        "hs_description": "Bed linen of cotton printed",
        "customs_category": "Textiles & Apparel",
        "customs_duty_rate": 30.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC",
        "notes": "ملايات ومفروشات أسرة قطنية مطبوعة",
    },

    # 5. Metals & Industrial Materials (المعادن ومواد البناء)
    {
        "hs_code": "7208.39.00",
        "hs_description": "Flat-rolled products of iron or non-alloy steel, hot-rolled (Thickness < 3mm)",
        "customs_category": "Metals & Industrial",
        "customs_duty_rate": 5.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "Industrial Development Authority (IDA)",
        "notes": "مسطحات صلب ومدلفن على الساخن للصناعة",
    },
    {
        "hs_code": "7214.20.00",
        "hs_description": "Bars and rods of iron or non-alloy steel, containing indentations, ribs (Rebar)",
        "customs_category": "Metals & Industrial",
        "customs_duty_rate": 15.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC & IDA (Protection Fees May Apply)",
        "notes": "حديد تسليح للبناء",
    },
    {
        "hs_code": "7601.10.00",
        "hs_description": "Unwrought aluminium, non-alloyed (Aluminium ingots)",
        "customs_category": "Metals & Industrial",
        "customs_duty_rate": 5.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "IDA",
        "notes": "خام ألومنيوم غير مشغول",
    },
    {
        "hs_code": "2523.29.00",
        "hs_description": "Portland cement, excluding white cement",
        "customs_category": "Building Materials",
        "customs_duty_rate": 5.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC",
        "notes": "أسمنت بورتلاندي عادي",
    },
    {
        "hs_code": "6907.21.00",
        "hs_description": "Ceramic flags and paving, hearth or wall tiles, water absorption <= 0.5%",
        "customs_category": "Building Materials",
        "customs_duty_rate": 60.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC (Decree 43)",
        "notes": "بلاط سيراميك وبورسلين للأرضيات والجدران",
    },
    {
        "hs_code": "7005.29.00",
        "hs_description": "Float glass and surface ground or polished glass sheets",
        "customs_category": "Building Materials",
        "customs_duty_rate": 15.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC",
        "notes": "زجاج مسطح فلوت للمباني والإنشاءات",
    },

    # 6. Machinery & Industrial Equipment (الآلات والمعدات)
    {
        "hs_code": "8409.91.00",
        "hs_description": "Parts suitable for use solely or principally with spark-ignition engines",
        "customs_category": "Machinery & Industrial Parts",
        "customs_duty_rate": 5.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC",
        "notes": "أجزاء وقطع غيار محركات الاحتراق الداخلي",
    },
    {
        "hs_code": "8413.70.00",
        "hs_description": "Centrifugal water pumps, power driven",
        "customs_category": "Machinery & Industrial Parts",
        "customs_duty_rate": 5.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC & IDA",
        "notes": "طلمبات ومضخات مياه طاردة مركزية",
    },
    {
        "hs_code": "8428.10.00",
        "hs_description": "Lifts and skip hoists (Passenger Elevators)",
        "customs_category": "Machinery & Industrial Parts",
        "customs_duty_rate": 5.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "Civil Protection & GOEIC",
        "notes": "مصاعد ركاب كهربائية للمباني",
    },
    {
        "hs_code": "8482.10.00",
        "hs_description": "Ball bearings",
        "customs_category": "Machinery & Industrial Parts",
        "customs_duty_rate": 5.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC",
        "notes": "رولمان بلي كروي للآلات والسيارات",
    },
    {
        "hs_code": "8501.52.00",
        "hs_description": "AC motors, multi-phase, of an output > 750 W but <= 75 kW",
        "customs_category": "Machinery & Industrial Parts",
        "customs_duty_rate": 5.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC",
        "notes": "محركات كهربائية تيار متناوب للمصانع",
    },

    # 7. Electronics & IT Equipment (الأجهزة الإلكترونية وتكنولوجيا المعلومات)
    {
        "hs_code": "8471.30.00",
        "hs_description": "Portable automatic data processing machines (Laptops & Notebooks)",
        "customs_category": "Electronics",
        "customs_duty_rate": 5.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 5.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "NTRA (National Telecom Regulatory Authority)",
        "notes": "حواسب شخصية محمولة — موافقة جهاز تنظيم الاتصالات NTRA",
    },
    {
        "hs_code": "8471.41.00",
        "hs_description": "Desktop computers comprising CPU, keyboard and display in same housing",
        "customs_category": "Electronics",
        "customs_duty_rate": 5.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 5.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "NTRA",
        "notes": "حواسب مكتبية متكاملة",
    },
    {
        "hs_code": "8517.13.00",
        "hs_description": "Smartphones for cellular networks or for other wireless networks",
        "customs_category": "Electronics",
        "customs_duty_rate": 10.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 10.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "NTRA",
        "notes": "أجهزة هواتف ذكية محمولة — رسم تنمية 10% واعتماد NTRA",
    },
    {
        "hs_code": "8517.62.00",
        "hs_description": "Machines for reception, conversion and transmission or regeneration of voice/data (Routers & Switches)",
        "customs_category": "Electronics",
        "customs_duty_rate": 5.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 5.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "NTRA",
        "notes": "راوترات ومحولات شبكات اتصالات وترديد بيانات",
    },
    {
        "hs_code": "8528.52.00",
        "hs_description": "Monitors capable of directly connecting to and designed for use with processing machines",
        "customs_category": "Electronics",
        "customs_duty_rate": 10.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 5.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "NTRA & GOEIC",
        "notes": "شاشات حواسب كمبيوتر",
    },

    # 8. Home Appliances (الأجهزة المنزلية)
    {
        "hs_code": "8418.10.00",
        "hs_description": "Combined refrigerator-freezers, fitted with separate external doors",
        "customs_category": "Home Appliances",
        "customs_duty_rate": 60.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 5.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "EOS (Egyptian Organization for Standardization), GOEIC",
        "notes": "ثلاجات منزلية مع فريزر — خاضعة لفحص الجودة وبطاقة كفاءة الطاقة",
    },
    {
        "hs_code": "8415.10.00",
        "hs_description": "Window or wall air conditioning machines, self-contained or split-system",
        "customs_category": "Home Appliances",
        "customs_duty_rate": 60.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 5.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "EOS & GOEIC",
        "notes": "أجهزة تكييف هواء منزلية سبليت وشباك",
    },
    {
        "hs_code": "8450.11.00",
        "hs_description": "Fully-automatic household washing machines, dry linen capacity <= 10 kg",
        "customs_category": "Home Appliances",
        "customs_duty_rate": 60.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 5.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "EOS & GOEIC",
        "notes": "غسالات ملابس أوتوماتيك منزلية",
    },
    {
        "hs_code": "8528.72.00",
        "hs_description": "Reception apparatus for television, color, with flat panel screen",
        "customs_category": "Home Appliances",
        "customs_duty_rate": 60.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 5.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "EOS, NTRA & GOEIC",
        "notes": "شاشات تلفزيون ملونة شاشة مسطحة (Smart TV)",
    },

    # 9. Vehicles & Automotive (السيارات ووسائل النقل)
    {
        "hs_code": "8703.21.00",
        "hs_description": "Passenger motor cars, cylinder capacity <= 1000 cc",
        "customs_category": "Automotive",
        "customs_duty_rate": 40.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 1.00,
        "development_fee_rate": 3.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC & Ministry of Industry",
        "notes": "سيارات ركوب سعة محرك حتى 1000 سي سي",
    },
    {
        "hs_code": "8703.22.00",
        "hs_description": "Passenger motor cars, cylinder capacity > 1000 cc but <= 1600 cc",
        "customs_category": "Automotive",
        "customs_duty_rate": 40.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 1.00,
        "development_fee_rate": 3.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC",
        "notes": "سيارات ركوب سعة محرك من 1000 حتى 1600 سي سي",
    },
    {
        "hs_code": "8703.23.00",
        "hs_description": "Passenger motor cars, cylinder capacity > 1600 cc but <= 2000 cc",
        "customs_category": "Automotive",
        "customs_duty_rate": 135.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 15.00,
        "development_fee_rate": 5.50,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC",
        "notes": "سيارات ركوب سعة من 1600 حتى 2000 سي سي — ضريبة جدول 15% ورسم وارد مرتفع",
    },
    {
        "hs_code": "8703.80.00",
        "hs_description": "Electric motor vehicles for passenger transport (EVs)",
        "customs_category": "Automotive",
        "customs_duty_rate": 0.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC & Ministry of Industry",
        "notes": "سيارات تعمل بمحرك كهربائي بالكامل (EV) — معفاة من الجمارك تشجيعاً للبيئة",
    },
    {
        "hs_code": "8704.21.00",
        "hs_description": "Motor vehicles for transport of goods, diesel, gvw <= 5 tonnes (Light Trucks)",
        "customs_category": "Automotive",
        "customs_duty_rate": 20.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC",
        "notes": "سيارات نقل بضائع خفيفة ديزل (نصف نقل)",
    },

    # 10. Luxury Goods & Special Schedule Taxes (البضائع الترفيهية وضريبة الجدول)
    {
        "hs_code": "2208.30.00",
        "hs_description": "Whiskies",
        "customs_category": "Luxury Goods",
        "customs_duty_rate": 300.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 150.00,
        "development_fee_rate": 10.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "Ministry of Finance & Tax Authority",
        "notes": "مشروبات روحية — خاضعة لأعلى الشرائح الضريبية وضريبة الجدول 150%",
    },
    {
        "hs_code": "2402.20.00",
        "hs_description": "Cigarettes containing tobacco",
        "customs_category": "Luxury Goods",
        "customs_duty_rate": 50.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 100.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "Eastern Company & Tax Authority",
        "notes": "سجائر تبغ — خاضعة لضريبة الجدول 100%",
    },
    {
        "hs_code": "3303.00.00",
        "hs_description": "Perfumes and toilet waters",
        "customs_category": "Luxury Goods",
        "customs_duty_rate": 60.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 10.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "EDA & GOEIC Decree 43",
        "notes": "عطور ومياه تجميل — رسم تنمية 10%",
    },
    {
        "hs_code": "7113.19.00",
        "hs_description": "Articles of jewelry and parts of precious metal other than silver",
        "customs_category": "Luxury Goods",
        "customs_duty_rate": 30.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 10.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "Stamp and Weights Authority (مصلحة دمغ المصوغات والموازين)",
        "notes": "مجوهرات وحلي ذهب وبلاتين — يتطلب فحص مصلحة الدمغ",
    },

    # 11. Paper, Packaging & Wood (الورق والتعبئة والخشبيات)
    {
        "hs_code": "4802.55.00",
        "hs_description": "Uncoated paper and paperboard, used for writing, printing, weight 40g/m² to 150g/m²",
        "customs_category": "Paper & Packaging",
        "customs_duty_rate": 5.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC",
        "notes": "ورق طباعة وكتابة أبيض غير مطلي",
    },
    {
        "hs_code": "4819.10.00",
        "hs_description": "Cartons, boxes and cases, of corrugated paper or paperboard",
        "customs_category": "Paper & Packaging",
        "customs_duty_rate": 15.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "GOEIC",
        "notes": "كرتون وصناديق تعبئة مضلعة",
    },
    {
        "hs_code": "4407.11.00",
        "hs_description": "Coniferous wood sawn or chipped lengthwise, thickness > 6mm (Pine & Spruce)",
        "customs_category": "Wood & Timber",
        "customs_duty_rate": 2.00,
        "vat_rate": 14.00,
        "schedule_tax_rate": 0.00,
        "development_fee_rate": 0.00,
        "import_fee_rate": 0.00,
        "requires_coo": True,
        "requires_inspection": True,
        "requires_acid": True,
        "regulatory_authority": "Agricultural Quarantine (Plant Protection)",
        "notes": "أخشاب صنوبرية موسكي وسويد مشرح للبناء والأثاث",
    },
]


def seed_nafeza_tariffs():
    db = SessionLocal()
    try:
        inserted = 0
        updated = 0
        for item in NAFEZA_CUSTOMS_TARIFFS:
            existing = db.query(CustomsTariff).filter(CustomsTariff.hs_code == item["hs_code"]).first()
            if existing:
                for k, v in item.items():
                    setattr(existing, k, v)
                existing.updated_at = datetime.now(timezone.utc)
                updated += 1
            else:
                tariff = CustomsTariff(
                    **item,
                    effective_from=date(2024, 1, 1),
                    is_active=True,
                )
                db.add(tariff)
                inserted += 1
        db.commit()
        print(f"Successfully seeded Nafeza Tariffs! Created: {inserted}, Updated: {updated}")
    except Exception as e:
        db.rollback()
        print(f"Error seeding Nafeza Tariffs: {e}")
    finally:
        db.close()


if __name__ == "__main__":
    seed_nafeza_tariffs()
