"""
Expense Catalog Seed Data (AI-EXPENSE-CATALOG-002)
Canonical 53 seed items extracted from Alexandria Customs Clearance (ACC) golden rate card.
"""

from typing import Any, Dict, List

EXPENSE_CATALOG_SEED_DATA: List[Dict[str, Any]] = [
    # ── Clearance Fees (9 items) ──
    {
        "code": "CLR-LCL-INV",
        "canonical_name_ar": "اتعاب تخليص LCL (فاتورة)",
        "canonical_name_en": "LCL Clearance Fee (Per Invoice)",
        "category": "Clearance Fees",
        "unit_type": "per_invoice",
        "allow_composite": False,
        "recognition_patterns": ["اتعاب تخليص ( فاتوره)", "اتعاب تخليص (فاتورة)", "أتعاب تخليص LCL (فاتورة)", "أتعاب تخليص LCL", "LCL Clearance Fee"],
    },
    {
        "code": "CLR-LCL-TON",
        "canonical_name_ar": "مصاريف تخليص LCL — أول طن",
        "canonical_name_en": "LCL Clearance Fee - First Ton",
        "category": "Clearance Fees",
        "unit_type": "per_ton",
        "allow_composite": False,
        "recognition_patterns": ["مصاريف تخليص واحد طن", "واحد طن LCL مصاريف تخليص", "مصاريف تخليص اول طن", "LCL 1 Ton Clearance"],
    },
    {
        "code": "CLR-LCL-TON-EXTRA",
        "canonical_name_ar": "مصاريف تخليص LCL — كل طن زيادة",
        "canonical_name_en": "LCL Clearance Fee - Additional Ton",
        "category": "Clearance Fees",
        "unit_type": "per_ton",
        "allow_composite": False,
        "recognition_patterns": ["مصاريف تخليص كل طن زيادة", "كل طن زيادة", "كل طن زبادة", "طن زبادة", "لكل طن زيادة LCL", "لكل طن اضافي LCL"],
    },
    {
        "code": "CLR-FCL20-INV",
        "canonical_name_ar": "اتعاب تخليص حاوية 20 قدم (فاتورة)",
        "canonical_name_en": "20ft FCL Clearance Fee (Per Invoice)",
        "category": "Clearance Fees",
        "unit_type": "per_invoice",
        "allow_composite": False,
        "recognition_patterns": ["اتعاب تخليص ( فاتوره)", "أتعاب تخليص حاوية 20 قدم (فاتورة)", "أتعاب تخليص 20 قدم", "اتعاب تخليص حاوية 20"],
    },
    {
        "code": "CLR-FCL20-CONT",
        "canonical_name_ar": "تخليص حاوية 20 قدم (1 حاوية)",
        "canonical_name_en": "20ft FCL Clearance (1 Container)",
        "category": "Clearance Fees",
        "unit_type": "per_container",
        "allow_composite": False,
        "recognition_patterns": ["مصاريف تخليص ١ حاوية", "مصاريف تخليص 1 حاوية", "مصاريف تخليص أول حاوية 20 قدم", "تخليص حاوية 20 قدم (1 حاوية)"],
    },
    {
        "code": "CLR-FCL20-CONT-EXTRA",
        "canonical_name_ar": "تخليص حاوية 20 قدم — كل حاوية زيادة",
        "canonical_name_en": "20ft FCL Clearance - Additional Container",
        "category": "Clearance Fees",
        "unit_type": "per_container",
        "allow_composite": False,
        "recognition_patterns": ["كل حاوية زيادة", "مصاريف تخليص كل حاوية 20 قدم زيادة", "كل حاوية 20 زيادة", "تخليص حاوية 20 زيادة"],
    },
    {
        "code": "CLR-FCL40-INV",
        "canonical_name_ar": "اتعاب تخليص حاوية 40 قدم (فاتورة)",
        "canonical_name_en": "40ft FCL Clearance Fee (Per Invoice)",
        "category": "Clearance Fees",
        "unit_type": "per_invoice",
        "allow_composite": False,
        "recognition_patterns": ["اتعاب تخليص ( فاتوره)", "أتعاب تخليص حاوية 40 قدم (فاتورة)", "أتعاب تخليص 40 قدم", "اتعاب تخليص حاوية 40"],
    },
    {
        "code": "CLR-FCL40-CONT",
        "canonical_name_ar": "تخليص حاوية 40 قدم (1 حاوية)",
        "canonical_name_en": "40ft FCL Clearance (1 Container)",
        "category": "Clearance Fees",
        "unit_type": "per_container",
        "allow_composite": False,
        "recognition_patterns": ["مصاريف تخليص ١ حاوية", "مصاريف تخليص 1 حاوية", "مصاريف تخليص أول حاوية 40 قدم", "تخليص حاوية 40 قدم (1 حاوية)"],
    },
    {
        "code": "CLR-FCL40-CONT-EXTRA",
        "canonical_name_ar": "تخليص حاوية 40 قدم — كل حاوية زيادة",
        "canonical_name_en": "40ft FCL Clearance - Additional Container",
        "category": "Clearance Fees",
        "unit_type": "per_container",
        "allow_composite": False,
        "recognition_patterns": ["كل حاوية زيادة", "مصاريف تخليص كل حاوية 40 قدم زيادة", "كل حاوية 40 زيادة", "تخليص حاوية 40 زيادة"],
    },

    # ── Procedures & Approvals (29 items) ──
    {
        "code": "PROC-POSTAGE",
        "canonical_name_ar": "بريد",
        "canonical_name_en": "Postage",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["بريد", "بريد ومراسلات", "مصاريف بريد", "بريد - دمغات"],
    },
    {
        "code": "PROC-STAMPS",
        "canonical_name_ar": "دمغات",
        "canonical_name_en": "Stamps",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["دمغات", "دمغة جمركية", "بريد - دمغات", "دمغات ومطبوعات"],
    },
    {
        "code": "PROC-IMPORTS-REVIEW",
        "canonical_name_ar": "عرض الواردات",
        "canonical_name_en": "Imports Inspection Review",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["عرض الواردات", "عرض الواردات + اعتماد الايباك", "عرض واردات", "فحص واردات"],
    },
    {
        "code": "PROC-EILAF-APPROVAL",
        "canonical_name_ar": "اعتماد الايلاف",
        "canonical_name_en": "Eilaf Approval",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["اعتماد الايلاف", "اعتماد الايباك", "اعتماد الإيلاك", "اعتماد الايلاك", "اعتماد ايباك"],
    },
    {
        "code": "PROC-ACID",
        "canonical_name_ar": "ACID",
        "canonical_name_en": "ACID Registration",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": False,
        "recognition_patterns": ["ACID تسجيل الشحنة الجمركي المبدئي", "ACID", "تسجيل ACID", "بند ACID", "ACID رسوم استخراج وإصدار"],
    },
    {
        "code": "PROC-AGRI-INSPECT",
        "canonical_name_ar": "زراعة",
        "canonical_name_en": "Agricultural Inspection",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["زراعة", "زراعة ومهمل وسيل", "عرض زراعة", "كشف زراعي"],
    },
    {
        "code": "PROC-VET-INSPECT",
        "canonical_name_ar": "مهيل (بيطري)",
        "canonical_name_en": "Veterinary Inspection",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["مهيل (بيطري)", "مهيل", "مهمل بيطري", "كشف بيطري", "زراعة ومهمل وسيل"],
    },
    {
        "code": "PROC-QUARANTINE",
        "canonical_name_ar": "سيل (حجر صحي)",
        "canonical_name_en": "Quarantine Seal",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["سيل (حجر صحي)", "سيل حجر صحي", "حجر صحي", "زراعة ومهمل وسيل"],
    },
    {
        "code": "PROC-SECURITY-GENERAL",
        "canonical_name_ar": "أمن عام",
        "canonical_name_en": "General Security",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["أمن عام", "امن عام", "امن عام ( اسكندرية - كفر الشيخ - البحيرة )", "أمن عام + مندوب الأمن العام"],
    },
    {
        "code": "PROC-SECURITY-DELEGATE",
        "canonical_name_ar": "مندوب الأمن العام",
        "canonical_name_en": "Security Delegate",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["مندوب الأمن العام", "مندوب امن عام", "امن عام كفر الشيخ", "أمن عام مندوب"],
    },
    {
        "code": "PROC-PORT-DATA-PULL",
        "canonical_name_ar": "سحب بيانات الموانئ",
        "canonical_name_en": "Port Data Pull",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": False,
        "recognition_patterns": ["سحب بيانات الموانئ", "سحب بيانات ميناء", "سحب بيانات", "امن عام البحيرة"],
    },
    {
        "code": "PROC-INSURANCE-DOC",
        "canonical_name_ar": "وثيقة تأمين",
        "canonical_name_en": "Insurance Document",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": False,
        "recognition_patterns": ["وثيقة تأمين", "وثيقة تامين", "اصدار وثيقة تامين"],
    },
    {
        "code": "PROC-SECURITY-CAIRO",
        "canonical_name_ar": "عرض أمن عام للقاهرة",
        "canonical_name_en": "Cairo Security Review",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": False,
        "recognition_patterns": ["عرض أمن عام للقاهرة", "عرض امن عام القاهره", "امن عام قاهرة"],
    },
    {
        "code": "PROC-XRAY",
        "canonical_name_ar": "عرض أكس راي",
        "canonical_name_en": "X-Ray Inspection",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": False,
        "recognition_patterns": ["عرض أكس راي", "عرض اكس راي", "(X-Ray) عرض إكس راي", "فحص اكس راي"],
    },
    {
        "code": "PROC-AGREEMENTS",
        "canonical_name_ar": "تطبيق الاتفاقيات",
        "canonical_name_en": "Trade Agreements Application",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": False,
        "recognition_patterns": ["تطبيق الاتفاقيات", "تطبيق اتفاقيات", "تطبيق الاتفاقيات التفضيلية"],
    },
    {
        "code": "PROC-CONDITIONAL-RELEASE",
        "canonical_name_ar": "الإفراج تحت التحفظ",
        "canonical_name_en": "Conditional Release",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": False,
        "recognition_patterns": ["الإفراج تحت التحفظ", "الافراج تحت التحفظ", "إفراج تحت التحفظ", "الافراج تحت التحلظ", "التحلظ", "ال ل ل"],
    },
    {
        "code": "PROC-CUSTOMS-SEAL",
        "canonical_name_ar": "سيل جمركي",
        "canonical_name_en": "Customs Seal",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": False,
        "recognition_patterns": ["سيل جمركي", "سيل الجمرك والترصيص", "غسيل جمركي", "ترصيص وسيل", "سيل الجمركي", "يل الجمركي", "الن"],
    },
    {
        "code": "PROC-FIRE-DEPT",
        "canonical_name_ar": "مطافي",
        "canonical_name_en": "Fire Department",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["مطافي", "مطافئ", "مطافي ومفرقعات ودمغة موازين", "كشف مطافي"],
    },
    {
        "code": "PROC-SCALE-STAMP",
        "canonical_name_ar": "دعمة وموازين",
        "canonical_name_en": "Scale Stamp",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["دعمة وموازين", "دمغة وموازين", "دمغة موازين", "مطافي ومفرقعات ودمغة موازين"],
    },
    {
        "code": "PROC-DOCS-SPLIT",
        "canonical_name_ar": "مفرقات",
        "canonical_name_en": "Document Splitting / Explosives",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["مفرقات", "مفرقعات", "مطافي ومفرقعات ودمغة موازين", "كشف مفرقعات"],
    },
    {
        "code": "PROC-FINAL-RELEASE",
        "canonical_name_ar": "إفراج نهائي",
        "canonical_name_en": "Final Release",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["إفراج نهائي", "افراج نهائي", "افراج نهائي واشعاع وكيمياء", "إنهاء إفراج", "افراج نهاني", "ال ل"],
    },
    {
        "code": "PROC-SHAMAA",
        "canonical_name_ar": "شماع",
        "canonical_name_en": "Radiation Inspection",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["شماع", "إشعاع", "اشعاع", "افراج نهائي واشعاع وكيمياء", "فحص اشعاع"],
    },
    {
        "code": "PROC-AGRI-COMPREHENSIVE",
        "canonical_name_ar": "عرض زراعة مشمول",
        "canonical_name_en": "Comprehensive Agricultural Review",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["عرض زراعة مشمول", "زراعة مشمول", "كشف زراعة مشمول"],
    },
    {
        "code": "PROC-CHEMICAL-AUTHORITY",
        "canonical_name_ar": "عرض على مصلحة الكيماء",
        "canonical_name_en": "Chemical Authority Review",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["عرض على مصلحة الكيماء", "عرض مصلحة الكيمياء", "فحص كيمياء", "كيمياء"],
    },
    {
        "code": "PROC-PERMIT-WITHDRAWAL",
        "canonical_name_ar": "سحب إذن",
        "canonical_name_en": "Delivery Order Withdrawal",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["سحب إذن", "سحب اذن", "سحب اذن تسليم", "سحب اذن تسليم وتصوير ومنافستو", "سحب إذن / تصوير / تعديل منافستو", "توكيل", "مصاريف توكيل"],
    },
    {
        "code": "PROC-PHOTOGRAPHY",
        "canonical_name_ar": "ثمن التصوير",
        "canonical_name_en": "Document Photography Fee",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["ثمن التصوير", "تصوير مستندات", "تصوير", "سحب اذن تسليم وتصوير ومنافستو"],
    },
    {
        "code": "PROC-DISPUTE-ADJUSTMENT",
        "canonical_name_ar": "مصاريف تعديل مناقشة",
        "canonical_name_en": "Manifest / Dispute Adjustment",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": True,
        "recognition_patterns": ["مصاريف تعديل مناقشة", "منافستو", "مصاريف تعديل منافستو", "سحب اذن تسليم وتصوير ومنافستو"],
    },
    {
        "code": "PROC-MISC-REVIEW",
        "canonical_name_ar": "بخلاف أي عرض",
        "canonical_name_en": "Miscellaneous Review",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": False,
        "recognition_patterns": ["بخلاف أي عرض", "بخلاف اي عرض", "لجنة فحص خارجي", "اكراميات ولجان", "أتعاب فتح شهادة الترانزيت ونقل جمركي", "شهادة ترانزيت ونقل جمركي", "فتح شهادة الترانزيت"],
    },
    {
        "code": "PROC-WEIGHT-EXCESS",
        "canonical_name_ar": "إنهاء إجراءات زيادة الوزن",
        "canonical_name_en": "Overweight Clearance Procedures",
        "category": "Procedures & Approvals",
        "unit_type": "fixed",
        "allow_composite": False,
        "recognition_patterns": ["إنهاء إجراءات زيادة الوزن", "انهاء اجراءات زيادة الوزن", "زيادة الوزن"],
    },

    # ── Inland Transport (10 items) ──
    {
        "code": "TRANS-VEH-1T",
        "canonical_name_ar": "نقل سيارة 1 طن دبابة",
        "canonical_name_en": "1-Ton Pickup Truck Transport",
        "category": "Inland Transport",
        "unit_type": "per_vehicle",
        "allow_composite": False,
        "recognition_patterns": ["نقل سيارة 1 طن دبابة للقاهرة", "نقل سيارة 1 طن دبابة", "سيارة 1 طن (دبابة) إسكندرية - قاهرة", "سيارة 1 طن دبابة"],
    },
    {
        "code": "TRANS-VEH-JUMBO-4T",
        "canonical_name_ar": "نقل سيارة جامبو حتى 4 طن",
        "canonical_name_en": "Jumbo Truck Transport (Up to 4T)",
        "category": "Inland Transport",
        "unit_type": "per_vehicle",
        "allow_composite": False,
        "recognition_patterns": ["نقل سيارة جامبو حتى 4 طن للقاهرة", "نقل سيارة جامبو حتى 4 طن", "سيارة جامبو حتى 4 طن إسكندرية - قاهرة", "جامبو حتى 4 طن"],
    },
    {
        "code": "TRANS-VEH-TRAILER-7T",
        "canonical_name_ar": "نقل سيارة تريلا حتى 7 طن",
        "canonical_name_en": "Trailer Truck Transport (Up to 7T)",
        "category": "Inland Transport",
        "unit_type": "per_vehicle",
        "allow_composite": False,
        "recognition_patterns": ["نقل سيارة فرداني حتى 7 طن للقاهرة", "نقل سيارة تريلا حتى 7 طن", "سيارة فرداني حتى 7 طن إسكندرية - قاهرة", "فرداني حتى 7 طن"],
    },
    {
        "code": "TRANS-CONT20-UP10T",
        "canonical_name_ar": "نقل حاوية 20 قدم حتى 10 طن",
        "canonical_name_en": "20ft Container Transport (Under 10T)",
        "category": "Inland Transport",
        "unit_type": "per_container",
        "allow_composite": False,
        "recognition_patterns": ["نقل حاوية 20 قدم وزن اقل من 10 طن للقاهرة", "نقل حاوية 20 قدم حتى 10 طن", "حاوية 20 قدم حتى 10 طن إسكندرية - قاهرة", "20 قدم وزن اقل من 10 طن"],
    },
    {
        "code": "TRANS-CONT20-OVER10T",
        "canonical_name_ar": "نقل حاوية 20 قدم أكثر من 10 طن",
        "canonical_name_en": "20ft Container Transport (Over 10T)",
        "category": "Inland Transport",
        "unit_type": "per_container",
        "allow_composite": False,
        "recognition_patterns": ["نقل حاوية 20 قدم وزن اكبر من 10 طن للقاهرة", "نقل حاوية 20 قدم أكثر من 10 طن", "حاوية 20 قدم أكثر من 10 طن إسكندرية - قاهرة", "20 قدم وزن اكبر من 10 طن"],
    },
    {
        "code": "TRANS-CONT-2X20",
        "canonical_name_ar": "نقل حاويتين 2×20",
        "canonical_name_en": "Dual 2x20ft Container Transport",
        "category": "Inland Transport",
        "unit_type": "per_shipment",
        "allow_composite": False,
        "recognition_patterns": ["نقل حاوية 20*2 للقاهرة", "نقل حاويتين 2×20", "حاويتين 20*2 قدم إسكندرية - قاهرة", "نقل 20*2", "الحاويه ٢٢", "الحاوية 22", "الحاوية ٢٢", "الحاويه 2*20"],
    },
    {
        "code": "TRANS-CONT40",
        "canonical_name_ar": "نقل حاوية 40 قدم",
        "canonical_name_en": "40ft Container Transport",
        "category": "Inland Transport",
        "unit_type": "per_container",
        "allow_composite": False,
        "recognition_patterns": ["نقل حاوية 40 قدم للقاهرة", "نقل حاوية 40 قدم", "حاوية 40 قدم إسكندرية - قاهرة", "نقل 40 قدم", "الحاوية ٤ قدم"],
    },
    {
        "code": "TRANS-DEMURRAGE-NIGHT-2X20",
        "canonical_name_ar": "بياتة حاويتين 2×20",
        "canonical_name_en": "Overnight Demurrage - 2x20ft",
        "category": "Inland Transport",
        "unit_type": "per_night",
        "allow_composite": False,
        "recognition_patterns": ["بياتة شاحنة 20*2", "بياتة حاويتين 2×20", "بياتة 20*2", "بياتة الحاويات ٢  ٢", "بياتة الحاويات 2*20", "بياتة الحاويات 2 2", "Overnight Demurrage 2x20ft"],
    },
    {
        "code": "TRANS-DEMURRAGE-NIGHT-40",
        "canonical_name_ar": "بياتة حاوية 1×40",
        "canonical_name_en": "Overnight Demurrage - 1x40ft",
        "category": "Inland Transport",
        "unit_type": "per_night",
        "allow_composite": False,
        "recognition_patterns": ["بياتة شاحنة 40*1", "بياتة حاوية 1×40", "بياتة 40*1", "بياتة حاوية 40", "بياتة الحاويات ٤١", "بياتة الحاويات 1*40", "بباتة الحاويات ٤١", "Overnight Demurrage 40ft"],
    },
    {
        "code": "TRANS-DEMURRAGE-NIGHT-20",
        "canonical_name_ar": "بياتة حاوية 1×20",
        "canonical_name_en": "Overnight Demurrage - 1x20ft",
        "category": "Inland Transport",
        "unit_type": "per_night",
        "allow_composite": False,
        "recognition_patterns": ["بياتة شاحنة 20*1", "بياتة حاوية 1×20", "بياتة الحاويات 1×20", "بياتة حاوية 20", "بياتة الحاويات ١ ٢", "بياتة الحاويات 1*20", "بياتة الحاويات ٢١", "تبييت حاوية 20 قدم", "Overnight Demurrage 20ft"],
    },

    # ── Port & Handling (3 items) ──
    {
        "code": "PORT-WEIGHT-CHECK",
        "canonical_name_ar": "مصاريف وزن فاش داخل الميناء",
        "canonical_name_en": "In-Port Weight Scale Inspection",
        "category": "Port & Handling",
        "unit_type": "fixed",
        "allow_composite": False,
        "recognition_patterns": ["مصاريف وزن فاش داخل الميناء", "مصاريف وزن قماش داخل الميناء", "مصاريف وزن قماش", "وزن قماش داخل الميناء", "وزن قماش", "وزن فاش", "اريف وزن قماش"],
    },
    {
        "code": "PORT-ABUQIR-RELEASE",
        "canonical_name_ar": "تعتيق ميناء أبوقير",
        "canonical_name_en": "Abu Qir Port Handling & Stevedoring",
        "category": "Port & Handling",
        "unit_type": "per_shipment",
        "allow_composite": False,
        "recognition_patterns": ["تعتيق ميناء أبوقير", "تعتيق ميناء ابوقير", "كارتة ابوقير", "كارتة أبوقير", "تعتيق ابوقير", "تفريغ", "تفريغ وتعتيق", "لعتيق ميناء ابوقير", "ريقوبا ءانيم قيتعت"],
    },
    {
        "code": "PORT-CONT-WEIGHT-TRANSFER",
        "canonical_name_ar": "نقل الحاوية للوزن داخل الميناء",
        "canonical_name_en": "In-Port Container Weight Transfer",
        "category": "Port & Handling",
        "unit_type": "per_container",
        "allow_composite": False,
        "recognition_patterns": ["نقل الحاوية للوزن داخل الميناء", "قيمة نقل الحاوية للوزن داخل الميناء", "قيمة نقل الحاوبة للوزن داخل الميناء", "تعتيق ونقل وزن داخل الميناء ( قماش )", "نقل وزن داخل الميناء", "تعتيق ونقل وزن", "الحاوبة للوزن"],
    },

    # ── Other Fees (2 items) ──
    {
        "code": "OTHER-CLARK-LABOR",
        "canonical_name_ar": "كشف واستخدام العمال والكلارك",
        "canonical_name_en": "Forklift & Labor Handling",
        "category": "Other Fees",
        "unit_type": "range",
        "allow_composite": False,
        "recognition_patterns": ["كشف واستخدام العمال والكلارك", "كشف عمال وكلارك", "بخلاف مصاريف كشف الحاويات المشتركة", "رسوم كشف وكلارك وتعتيق"],
    },
    {
        "code": "OTHER-CLIENT-KNOWLEDGE",
        "canonical_name_ar": "مصاريف موادة بمعرفة العميل",
        "canonical_name_en": "Client-Managed Logistics Expenses",
        "category": "Other Fees",
        "unit_type": "range",
        "allow_composite": False,
        "recognition_patterns": ["مصاريف موادة بمعرفة العميل", "بمعرفة العميل", "بخلاف كشف التجميع للحاويات", "بخلاف رسوم المعامل وفحص العينات الكيماوية"],
    },
]
